{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-runtime",
    "version": "2.10.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.10.0-alpha02-sources.jar",
          "url": "work-runtime-2.10.0-alpha02-sources.jar",
          "size": 297743,
          "sha512": "67afdeaf228f717a4ce6e73e6e5f6acc9228eef754b693c0905ef2c0afa0b8f0f68f9a4f9f4a638b4b9e5afc5872460397fd00b8c65ae4cce873639b376cda8f",
          "sha256": "fa02958fdc0780c15bcf35354ec4fb1ddad809b8e9e08a929870f1a5add94095",
          "sha1": "2a0358fbee6ac77708e3fe4a413217e580b63c19",
          "md5": "a97e6b4dc62dc16a4a9be770e1ec397c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.10.0-alpha02.aar",
          "url": "work-runtime-2.10.0-alpha02.aar",
          "size": 1965509,
          "sha512": "2dce98b835cb3d58485dc280125216fea95a61deb6d8555928c554c587211fe2a1c3522860cf4373641542e43a62a342c1c1e87e4ba7e7399c33bb7528479177",
          "sha256": "df4a2199696888a3f39d1e571550a966b00b387dba3001ffb2a17ce3b5216ec9",
          "sha1": "d3af980d55f9a4307b4fc52fa27f88b80f37667d",
          "md5": "dd6b052075945936181259fb12535880"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.10.0-alpha02.aar",
          "url": "work-runtime-2.10.0-alpha02.aar",
          "size": 1965509,
          "sha512": "2dce98b835cb3d58485dc280125216fea95a61deb6d8555928c554c587211fe2a1c3522860cf4373641542e43a62a342c1c1e87e4ba7e7399c33bb7528479177",
          "sha256": "df4a2199696888a3f39d1e571550a966b00b387dba3001ffb2a17ce3b5216ec9",
          "sha1": "d3af980d55f9a4307b4fc52fa27f88b80f37667d",
          "md5": "dd6b052075945936181259fb12535880"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.10.0-alpha02-versionMetadata.json",
          "url": "work-runtime-2.10.0-alpha02-versionMetadata.json",
          "size": 37451,
          "sha512": "bef3bb907beb02bd799c870080e65e4e1dbfb45960156a0ad7af4b38e1e3c27f6b65ba40fbae56904be401b2d61d61476d98c3fddb70d80a917f47cd07cee7cf",
          "sha256": "e13240b1226abb5c9dbd7653eb454558f0a48dfecdfc945250a7b6187f18b710",
          "sha1": "1e5f57da76c68cc22d396fdeaef9ff00e8be13d1",
          "md5": "837b725db26609c2ba74726602d2035b"
        }
      ]
    }
  ]
}