{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.biometric",
    "module": "biometric",
    "version": "1.2.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "biometric-1.2.0-alpha06.aar",
          "url": "biometric-1.2.0-alpha06.aar",
          "size": 245183,
          "sha512": "a676ab6f6f9d6dbb37d1a00b8e10567b296da16bb6a7a2749b7deb4ce4171493b1a7bd63f282780bc7d58aa80a8007355f22cac3701aa9a50f40ef6096151400",
          "sha256": "90829d7e6be034614a62ecc97d41d0c35309eb2e4189ec94841ec1a011d2cca3",
          "sha1": "c3ba540decc69cec52fcd87d7d19a8706f97cc8e",
          "md5": "e769296adc0a67812124a31269d37fab"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.biometric",
          "module": "biometric-ktx",
          "version": {
            "requires": "1.2.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "biometric-1.2.0-alpha06.aar",
          "url": "biometric-1.2.0-alpha06.aar",
          "size": 245183,
          "sha512": "a676ab6f6f9d6dbb37d1a00b8e10567b296da16bb6a7a2749b7deb4ce4171493b1a7bd63f282780bc7d58aa80a8007355f22cac3701aa9a50f40ef6096151400",
          "sha256": "90829d7e6be034614a62ecc97d41d0c35309eb2e4189ec94841ec1a011d2cca3",
          "sha1": "c3ba540decc69cec52fcd87d7d19a8706f97cc8e",
          "md5": "e769296adc0a67812124a31269d37fab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "biometric-1.2.0-alpha06-sources.jar",
          "url": "biometric-1.2.0-alpha06-sources.jar",
          "size": 70030,
          "sha512": "9a67b0f20e7b99b7aa21367cfcbbd8747b10692e4a4adeb7f97f10869605aee0fdd9e02218d76c4924aab65208ae8583fc347182b90235caa7424ff11cc4bf41",
          "sha256": "48395b813ba5a21d7c2b3314c37623c47d0d5e0c9bba3cc7f0d24d133688238c",
          "sha1": "bb9039b77fd65fdbf7aa84f8ec57236ba0c6d3b2",
          "md5": "b6f1a69ecc2f74a0e23a1bfa764361ff"
        }
      ]
    }
  ]
}