{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.emoji",
    "module": "emoji-bundled",
    "version": "1.2.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "emoji-bundled-1.2.0-alpha03-sources.jar",
          "url": "emoji-bundled-1.2.0-alpha03-sources.jar",
          "size": 1845,
          "sha512": "c98b5e49a0a867044769c659d8fc510992a382565e399e25af75bfbde9e103029af3fdd85c32738b58bd1fa1a0c4de48d5514cda61481e0011c22e8c61c977bc",
          "sha256": "0f790daf951acb93dfa72d615167c52675fa355420881b8d5cf9acdd3d3c0783",
          "sha1": "34897e0dac1d2e45a831ff6ae174fc4052035b80",
          "md5": "9e587ecd324b133e0fd73168dca3b4f0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.emoji",
          "module": "emoji",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "emoji-bundled-1.2.0-alpha03.aar",
          "url": "emoji-bundled-1.2.0-alpha03.aar",
          "size": 9868843,
          "sha512": "77d55d785cdfbe65c26e15a475070e938d13649fc50c41742b21815abae575d1b2aea7d4af16ce13141cd045797c8ad4a4be327e07800c8bb40d9f129ca7df71",
          "sha256": "3ae018e6e3fccb19dadbebf7ba916dcf8655d171c6060b55dfea978763571bfa",
          "sha1": "18be513aaa24d67662db84de911825c30ace9734",
          "md5": "6fb45d694383ab8495c80b6475a58d4f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.emoji",
          "module": "emoji",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "emoji-bundled-1.2.0-alpha03.aar",
          "url": "emoji-bundled-1.2.0-alpha03.aar",
          "size": 9868843,
          "sha512": "77d55d785cdfbe65c26e15a475070e938d13649fc50c41742b21815abae575d1b2aea7d4af16ce13141cd045797c8ad4a4be327e07800c8bb40d9f129ca7df71",
          "sha256": "3ae018e6e3fccb19dadbebf7ba916dcf8655d171c6060b55dfea978763571bfa",
          "sha1": "18be513aaa24d67662db84de911825c30ace9734",
          "md5": "6fb45d694383ab8495c80b6475a58d4f"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "emoji-bundled-1.2.0-alpha03-versionMetadata.json",
          "url": "emoji-bundled-1.2.0-alpha03-versionMetadata.json",
          "size": 184,
          "sha512": "337b63372a2ebcc4335116c35441584ce7043dde18130ed6d3cd26f961f46aacdbc958ad0dcdfce430a9c7ee9e10a8f6d418373aed069980da4ff425aa9846ad",
          "sha256": "4e34177d9c083f721fc6b2a9af34e5b141d032e9c73034ae74c1d1cee7a3cea6",
          "sha1": "6bbf7e36f9c2bc09635a1d59970d098ddd161394",
          "md5": "f8bf058da86cd0a791ffd8e5c109cf1b"
        }
      ]
    }
  ]
}