{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lifecycle-viewmodel/2.9.0-alpha01/lifecycle-viewmodel-2.9.0-alpha01.module",
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel",
    "version": "2.9.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-release.aar",
          "url": "lifecycle-viewmodel-android-2.9.0-alpha01.aar",
          "size": 56326,
          "sha512": "d2b9dbf90127ce3e7083a9a8f912fe7067864f3d7d7b44c58142fd2148100fb92dc9b9b797057f5b2813f327327f6ff0080d384d71793e9adef18fc206801a04",
          "sha256": "258e0ff21be1a80ac5ac4c2089157c63574ed254e47827ef553b910baa96f425",
          "sha1": "8fc0715416ba38a8278df8d0af2934a93793894b",
          "md5": "4927c6abb809c0d9862338b736dca4a1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-release.aar",
          "url": "lifecycle-viewmodel-android-2.9.0-alpha01.aar",
          "size": 56326,
          "sha512": "d2b9dbf90127ce3e7083a9a8f912fe7067864f3d7d7b44c58142fd2148100fb92dc9b9b797057f5b2813f327327f6ff0080d384d71793e9adef18fc206801a04",
          "sha256": "258e0ff21be1a80ac5ac4c2089157c63574ed254e47827ef553b910baa96f425",
          "sha1": "8fc0715416ba38a8278df8d0af2934a93793894b",
          "md5": "4927c6abb809c0d9862338b736dca4a1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-android-2.9.0-alpha01-sources.jar",
          "url": "lifecycle-viewmodel-android-2.9.0-alpha01-sources.jar",
          "size": 34988,
          "sha512": "e9d0f9e6856ef2d272318238476bb7e98fc2066bbea2260e4088d1f6c36635cb6beed35252010eea0c3d837608d6ec01d65d5aa8f575c154b1d9e99728de0d24",
          "sha256": "0cfe281e96bd4aedd2df3b6d620bbbc80a3d98386d958baea62af708cbc33139",
          "sha1": "dcd581253bf44622fcb4e5f31fa4d4ada1e9819d",
          "md5": "56db01d62250f83201c3e280871bf150"
        }
      ]
    }
  ]
}