version: "1.2.0-rc01"
dependency_list {
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime"
    version: "1.0.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui"
    version: "1.0.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.hilt"
    artifact_id: "hilt-navigation"
    version: "1.2.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-viewmodel-compose"
    version: "2.6.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-compose"
    version: "2.5.1"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.hilt"
group_id: "androidx.hilt"
artifact_id: "hilt-navigation-compose"
path: "/hilt/hilt-navigation-compose"
sha: "6b7a6df015aa856a7d6a61df2bfb8cd5f4abf905"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.hilt-hilt-navigation-compose-all-11875385-1.2.0-rc01.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
