{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.hilt",
    "module": "hilt-navigation-compose",
    "version": "1.2.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hilt-navigation-compose-1.2.0-rc01-sources.jar",
          "url": "hilt-navigation-compose-1.2.0-rc01-sources.jar",
          "size": 2132,
          "sha512": "aeca5f59d67cdf86e1d0f4f8493bc0d083e75776b88ff23bfb7928bcb6fab88d0b4dcb97a25f392bb661bf682c91a63a0d772e14fe58f348bcf2b3dc316c2d5f",
          "sha256": "5e6272ad60781eb48126484218dd993a4c68c553456b711a1cae796760c128e8",
          "sha1": "3316ba490a3081b6cfa8fa21c29a48a6a2e35e2f",
          "md5": "a240ab079d55e3323f73e74293cec608"
        },
        {
          "name": "hilt-navigation-compose-1.2.0-rc01-samples-sources.jar",
          "url": "hilt-navigation-compose-1.2.0-rc01-samples-sources.jar",
          "size": 1898,
          "sha512": "0a0905f1cc7a345ed27a71ae97de5dada2e54bdee5b83f54d8639716f8550cbd375d5015301a6f123429556164ead709617e9d134bff30c3b6ea7ccfeaf921e7",
          "sha256": "0507e71e839567ee9e51119edd9ab1db6c8279b675fef03417199227275ce58d",
          "sha1": "b8667dbea736b4b1387ebc43139a8298992e5b88",
          "md5": "671550a9b2f932ac53668f0d379b6881"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-navigation",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-navigation-compose-1.2.0-rc01.aar",
          "url": "hilt-navigation-compose-1.2.0-rc01.aar",
          "size": 4600,
          "sha512": "f76556149bb0a1cfb1cc4cab952ed0577589352d70008450e5e4e1f5f6e4b1a328d57b0e36e1007bd05dd79275e44f9d9803fe776101b187d00140019b3c1509",
          "sha256": "dbd9906f1004ec9fb79389496a2df738098b4c38343dcc8551bb6e0b7386b5a1",
          "sha1": "b558add62f515fbaf40b1c70f8b5d8edad826d4a",
          "md5": "0da6b0ca45627254eac6c511299ba14e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-navigation",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-navigation-compose-1.2.0-rc01.aar",
          "url": "hilt-navigation-compose-1.2.0-rc01.aar",
          "size": 4600,
          "sha512": "f76556149bb0a1cfb1cc4cab952ed0577589352d70008450e5e4e1f5f6e4b1a328d57b0e36e1007bd05dd79275e44f9d9803fe776101b187d00140019b3c1509",
          "sha256": "dbd9906f1004ec9fb79389496a2df738098b4c38343dcc8551bb6e0b7386b5a1",
          "sha1": "b558add62f515fbaf40b1c70f8b5d8edad826d4a",
          "md5": "0da6b0ca45627254eac6c511299ba14e"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "hilt-navigation-compose-1.2.0-rc01-versionMetadata.json",
          "url": "hilt-navigation-compose-1.2.0-rc01-versionMetadata.json",
          "size": 615,
          "sha512": "82e69bb971f55ed87b7c44d1a15496ce6ea4e198604fc338242628fc300504b87ac757c487bb0d6f6ddeff8f954982d98009dfb557e01810513ee69a4f780795",
          "sha256": "7f50f62211d01905a5f990045353079b2c9e9c57ab4f10f67c6a40c56a6faef0",
          "sha1": "01793aa24a377766050bdcce2f293bf0abcdd74d",
          "md5": "0e0dd71f5bd27ff7c5e865ecf05c95ba"
        }
      ]
    }
  ]
}