{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.ui",
    "module": "ui-client",
    "version": "1.0.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ui-client is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-provider",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ui-client is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-client-1.0.0-alpha07.aar",
          "url": "ui-client-1.0.0-alpha07.aar",
          "size": 52166,
          "sha512": "cf42a4b1a6b67aaa16993c13ae64c7d8bab72112b963261cbb7d99a9faf7d07d5cf88f396d5a8a23b165369f818ef55ff97fcb832f92d48d9020915282c9083a",
          "sha256": "b2f445b3c7c5e87f4c026aaf755872a5153473e2583d984f16d4943cfd2d5d87",
          "sha1": "9099955f7468d8593ee3a6440b02d1e9c6367352",
          "md5": "a85b2cbdd26c19188a286a3000d91df4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview-poolingcontainer",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-client",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ui-client is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-provider",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ui-client is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-client-1.0.0-alpha07.aar",
          "url": "ui-client-1.0.0-alpha07.aar",
          "size": 52166,
          "sha512": "cf42a4b1a6b67aaa16993c13ae64c7d8bab72112b963261cbb7d99a9faf7d07d5cf88f396d5a8a23b165369f818ef55ff97fcb832f92d48d9020915282c9083a",
          "sha256": "b2f445b3c7c5e87f4c026aaf755872a5153473e2583d984f16d4943cfd2d5d87",
          "sha1": "9099955f7468d8593ee3a6440b02d1e9c6367352",
          "md5": "a85b2cbdd26c19188a286a3000d91df4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ui-client is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-provider",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ui-client is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-client-1.0.0-alpha07-sources.jar",
          "url": "ui-client-1.0.0-alpha07-sources.jar",
          "size": 12831,
          "sha512": "a44f3c1fc2d34b723fa12c71c4fa859bd33bd0cf81d668ba6a80c6bda74f0f05b2f28ccacb209b5ccee45d71b8398380b7595019a1c8e4e16ed69e91fc420b27",
          "sha256": "82b6d2fd0aa661e0af914d8816e81247d29341a1d547e428f4cf11bf3064dcc3",
          "sha1": "d0ca1b8a05cf4293a1cb100de86acb4740996833",
          "md5": "68d635ac8f94c763ee303a1b88033e42"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ui-client is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-provider",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ui-client is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-client-1.0.0-alpha07-versionMetadata.json",
          "url": "ui-client-1.0.0-alpha07-versionMetadata.json",
          "size": 2923,
          "sha512": "c4773900c8e6ed0fcfa472ce3ae9b8918987c5d8f048ba21e0d7735cb75010db7a50e824492df13e1ceb64155a9ec0e11c43251cc779788b5149cfe0fa20434f",
          "sha256": "30a07a5c5e8bb8d66ce755c843f088dd23cdd7056b88c08252589c9a0d2b8e66",
          "sha1": "d4b6447a86e7ab66c9df5c487d5dc4b661f7aec3",
          "md5": "d60e2764734bc7018a784abfaf7421c0"
        }
      ]
    }
  ]
}