{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-icons-core/1.7.0-alpha01/material-icons-core-1.7.0-alpha01.module",
    "group": "androidx.compose.material",
    "module": "material-icons-core",
    "version": "1.7.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.7.0-alpha01"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.0-alpha01"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.0-alpha01"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        }
      ],
      "files": [
        {
          "name": "material-icons-core-release.aar",
          "url": "material-icons-core-android-1.7.0-alpha01.aar",
          "size": 822418,
          "sha512": "e71acfee6a2a98ea4ee7037b437ecc77e2e259d6492faca364c2fc2dac9ffd241bf1daa42c257ae2d25e573f65179384e4b6c97081a6d5a0998b4bd8a4bafb32",
          "sha256": "9b3ae37a3d3658d312f6058579913e8ddb88cacf317c1e89ea4e6622c793158b",
          "sha1": "deb251b1ed298a336514026bbe01c92ce4b13af3",
          "md5": "410d4178183f001dde71a7e34b29d396"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.7.0-alpha01"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.0-alpha01"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.0-alpha01"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        }
      ],
      "files": [
        {
          "name": "material-icons-core-release.aar",
          "url": "material-icons-core-android-1.7.0-alpha01.aar",
          "size": 822418,
          "sha512": "e71acfee6a2a98ea4ee7037b437ecc77e2e259d6492faca364c2fc2dac9ffd241bf1daa42c257ae2d25e573f65179384e4b6c97081a6d5a0998b4bd8a4bafb32",
          "sha256": "9b3ae37a3d3658d312f6058579913e8ddb88cacf317c1e89ea4e6622c793158b",
          "sha1": "deb251b1ed298a336514026bbe01c92ce4b13af3",
          "md5": "410d4178183f001dde71a7e34b29d396"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.7.0-alpha01"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.0-alpha01"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.0-alpha01"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        }
      ],
      "files": [
        {
          "name": "material-icons-core-android-1.7.0-alpha01-sources.jar",
          "url": "material-icons-core-android-1.7.0-alpha01-sources.jar",
          "size": 284048,
          "sha512": "2803312f6e4dfb1b2501b44f47eb72fd02212e41a18c5dcbec7b7e280612b486d23b72d50688a2fb3776b1582ae63ec923fd3f39bdbc4e951a779dc133495f64",
          "sha256": "b3f1be7fda4d13a6d938bb918275ddc143e9d6a2007727f284778480526f5f16",
          "sha1": "e518df0d8a19c3833f72a24ff667853015e340fd",
          "md5": "6f8dfe229b864de0e1deaa71ad0c1434"
        }
      ]
    }
  ]
}