version: "1.7.0-beta02"
dependency_list {
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-android"
    version: "1.7.0-beta02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-desktop"
    version: "1.7.0-beta02"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.compose.runtime"
group_id: "androidx.compose.runtime"
artifact_id: "runtime"
path: "/compose/runtime/runtime"
sha: "3264c1f21ddfe2acf96a1d034f78367662cf9f65"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.compose.runtime-runtime-all-11879057-1.7.0-beta02.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-livedata"
    version: "1.7.0-beta02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-rxjava2"
    version: "1.7.0-beta02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-rxjava3"
    version: "1.7.0-beta02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-saveable"
    version: "1.7.0-beta02"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: true
