{
  "formatVersion": "1.1",
  "component": {
    "url": "../../room-common/2.7.0-alpha03/room-common-2.7.0-alpha03.module",
    "group": "androidx.room",
    "module": "room-common",
    "version": "2.7.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-common-jvm-2.7.0-alpha03.jar",
          "url": "room-common-jvm-2.7.0-alpha03.jar",
          "size": 61554,
          "sha512": "70e589f99098029841d0fa0418accdd21b34af9034824d3a125b187a2a15290072b1b1ba1f0ce9164b592f11d2d7a07726bc4fb3d438dbfbdf396eee11933bf2",
          "sha256": "13d3232d123ac28508cd31a022e461f7f3d92250f169c904ac1f20257b4a54fa",
          "sha1": "f1644b5a6e8d227fa506b36e19153f14b9c2ce75",
          "md5": "cbeb07fb56e7e6341d04b1c91417f1b3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-common-jvm-2.7.0-alpha03.jar",
          "url": "room-common-jvm-2.7.0-alpha03.jar",
          "size": 61554,
          "sha512": "70e589f99098029841d0fa0418accdd21b34af9034824d3a125b187a2a15290072b1b1ba1f0ce9164b592f11d2d7a07726bc4fb3d438dbfbdf396eee11933bf2",
          "sha256": "13d3232d123ac28508cd31a022e461f7f3d92250f169c904ac1f20257b4a54fa",
          "sha1": "f1644b5a6e8d227fa506b36e19153f14b9c2ce75",
          "md5": "cbeb07fb56e7e6341d04b1c91417f1b3"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-common is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-common-jvm-2.7.0-alpha03-sources.jar",
          "url": "room-common-jvm-2.7.0-alpha03-sources.jar",
          "size": 65895,
          "sha512": "1fdcd53ba16ff6c7fd6d89d001715eff6cfcf7a74c8d871a611cf4acb529904dd5f0d91bf4f34a973e4ed52a1f6e5b97bd0759c36c87475c6fb3fb11169f2120",
          "sha256": "85c51be2c9217eb620e456c9e5b7cbfa3d57e890301364dbd2fc85e8cc5f1e2e",
          "sha1": "5ecfb653d16d5940e3acc505d11aeb7a90ec08e2",
          "md5": "7831ef52ec254f7a7cdd9451ed6adad5"
        }
      ]
    }
  ]
}