{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.watchface",
    "module": "watchface",
    "version": "1.3.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-1.3.0-alpha03-sources.jar",
          "url": "watchface-1.3.0-alpha03-sources.jar",
          "size": 129102,
          "sha512": "a5d491bf5ef6cab38ae44a7d4bcf7c65feba23b26d776fe4f4fa9b3b364aebb285e7a4bc09f70cc3070031fe997a08d69c560e777bb92b34c242adfb9ddca0f2",
          "sha256": "52440a80baa9d7ac5c17fc1158a9a967e3fc5ac409e59e24303cd7f05088a7f1",
          "sha1": "64a8e95e9d9c37dee24b957974b9fd8675b1a09b",
          "md5": "a3a09d03ebf4122621e0898570c2e010"
        },
        {
          "name": "watchface-1.3.0-alpha03-samples-sources.jar",
          "url": "watchface-1.3.0-alpha03-samples-sources.jar",
          "size": 42650,
          "sha512": "5f745025ce6b1669f29da7d745db07e4ddd17ebe090710ebe1add468833ccc21d0cd5241ae751a01c32d21daeca9b7d7606aef3dcdcd22c072cdd233052672f3",
          "sha256": "0a5bcbbdf7e835f45c64b7d1866c042dccc9b423322e854a9af6a8c3c5ddb19c",
          "sha1": "8506845a42296313d73a004aaf0fc0a609b2ef12",
          "md5": "cf9db229b9eb75058fa3a8052ed14ea3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-1.3.0-alpha03.aar",
          "url": "watchface-1.3.0-alpha03.aar",
          "size": 544115,
          "sha512": "02bdb444d439717d55d4454fc33504dd33d36a822de31611effe78092b820fb33fa8ace59729791a6850ab2edffab3a45c21457469432f002db2545f9715c641",
          "sha256": "4960076a3eb055024089717132bd8d8d60da4b428268ce5291c17d2056f0d3a6",
          "sha1": "e60dbadfba96d40aabfcc5889b85dbce112ddcfc",
          "md5": "1753f366999b565f81d7def254525122"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-1.3.0-alpha03.aar",
          "url": "watchface-1.3.0-alpha03.aar",
          "size": 544115,
          "sha512": "02bdb444d439717d55d4454fc33504dd33d36a822de31611effe78092b820fb33fa8ace59729791a6850ab2edffab3a45c21457469432f002db2545f9715c641",
          "sha256": "4960076a3eb055024089717132bd8d8d60da4b428268ce5291c17d2056f0d3a6",
          "sha1": "e60dbadfba96d40aabfcc5889b85dbce112ddcfc",
          "md5": "1753f366999b565f81d7def254525122"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-1.3.0-alpha03-versionMetadata.json",
          "url": "watchface-1.3.0-alpha03-versionMetadata.json",
          "size": 33140,
          "sha512": "70affef38b9b71e930e39b367632ce462664a146cbe13e6912600774940f51fc4dba9a0934fe9036875c858dca344edbd65b89d4574463ba75d0e4a19c3654e6",
          "sha256": "69d8a199b448356721e83a4cc63dfb912cffa420edf1137f5435e940ef56dbc8",
          "sha1": "51e3a507b21800e48583692ee3964db9347a98e1",
          "md5": "38da78eb9830c70bb5d6d4f9b5bb6faa"
        }
      ]
    }
  ]
}