{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-testing",
    "version": "2.8.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-testing-2.8.0-alpha03.aar",
          "url": "navigation-testing-2.8.0-alpha03.aar",
          "size": 18891,
          "sha512": "42fedbfaba3c058623eda29610bcfd4634a0c51ce24cbe1f56a6bb477a5f5c56cf17c7af8332b74041d6a87926d23e6301f4b119d548e07cad32b54b2bb2db74",
          "sha256": "265bbaf557ed496cf44c7e7d60f1bd26221139236fd874b8adc251cfde943476",
          "sha1": "b07dbcbf391f908b2a8e3a2d4b933fd0ef2f6598",
          "md5": "983eaea582d660562635cbe8421b05e4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-testing-2.8.0-alpha03.aar",
          "url": "navigation-testing-2.8.0-alpha03.aar",
          "size": 18891,
          "sha512": "42fedbfaba3c058623eda29610bcfd4634a0c51ce24cbe1f56a6bb477a5f5c56cf17c7af8332b74041d6a87926d23e6301f4b119d548e07cad32b54b2bb2db74",
          "sha256": "265bbaf557ed496cf44c7e7d60f1bd26221139236fd874b8adc251cfde943476",
          "sha1": "b07dbcbf391f908b2a8e3a2d4b933fd0ef2f6598",
          "md5": "983eaea582d660562635cbe8421b05e4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-testing-2.8.0-alpha03-sources.jar",
          "url": "navigation-testing-2.8.0-alpha03-sources.jar",
          "size": 4988,
          "sha512": "323f34f95329677333aa03dd43a6c03e0c94cf9d32d77500e5791219ae0065c0b958886deb620eb6a624f424b09b58cdaf2278694e0c49b7790b74a660bbba17",
          "sha256": "34fe062a60013fecd81ba84d0df1ed71e0b326df93833079591a8e6b661c4763",
          "sha1": "551ae6fc097c0584ef9df480f0bffea954af0c5e",
          "md5": "ce02c3d4163524ebe0eec27c99461829"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-testing is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-testing-2.8.0-alpha03-versionMetadata.json",
          "url": "navigation-testing-2.8.0-alpha03-versionMetadata.json",
          "size": 1063,
          "sha512": "2d431e8237d1be867e80a99b979cd8ba905b3c23b198580765b1647ee47a3aaea8d02fe357a491d72a7e575ad8aa02ad81e76cf2e12f0021bb1ef0e37699576b",
          "sha256": "3e48139ed6256aa5a93b5b0462954101d8be1943e9610ad3c8c1cf44264652bb",
          "sha1": "429f605d2b8f61bb1ad7737c47cb1177e8b3a643",
          "md5": "a9b4559f91ad3d0a00ddb08ccb110ac9"
        }
      ]
    }
  ]
}