{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.emoji2",
    "module": "emoji2-views-helper",
    "version": "1.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        }
      ],
      "files": [
        {
          "name": "emoji2-views-helper-1.5.0-alpha01.aar",
          "url": "emoji2-views-helper-1.5.0-alpha01.aar",
          "size": 20553,
          "sha512": "2993df6511ca08f8ed7347b14098e05a40aa1a9f72e6865db89e1b3925c14dc512dac53781c890caf75192381b607fc5f33a5d369e9a018f36816897bcdc887a",
          "sha256": "8bd1edc69524d9258df5f964d9d4b668287e4178ec83499aca82290354e67e88",
          "sha1": "f699e7b0fef11fd5b0dca62e5d5002ab7c274687",
          "md5": "162c09e42831164cd86809efd9e2220b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        }
      ],
      "files": [
        {
          "name": "emoji2-views-helper-1.5.0-alpha01.aar",
          "url": "emoji2-views-helper-1.5.0-alpha01.aar",
          "size": 20553,
          "sha512": "2993df6511ca08f8ed7347b14098e05a40aa1a9f72e6865db89e1b3925c14dc512dac53781c890caf75192381b607fc5f33a5d369e9a018f36816897bcdc887a",
          "sha256": "8bd1edc69524d9258df5f964d9d4b668287e4178ec83499aca82290354e67e88",
          "sha1": "f699e7b0fef11fd5b0dca62e5d5002ab7c274687",
          "md5": "162c09e42831164cd86809efd9e2220b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        }
      ],
      "files": [
        {
          "name": "emoji2-views-helper-1.5.0-alpha01-sources.jar",
          "url": "emoji2-views-helper-1.5.0-alpha01-sources.jar",
          "size": 17149,
          "sha512": "0cf785fe74f053b90f7d66506bc774272c35dd5039bfca4f2c519425a976ede6f23dec170201591a233f1103c3e7c945f9fdd244ab65e066f57fa6cee6d5ba02",
          "sha256": "e7f28ac0b8f55fa781b32b3701982600434b63f20ca9700a2b74262db92e9822",
          "sha1": "3ddd6ec3be1071d74da264c4a245d1539ebf1100",
          "md5": "801da01f754858f9185ff54c7bd579bd"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        }
      ],
      "files": [
        {
          "name": "emoji2-views-helper-1.5.0-alpha01-versionMetadata.json",
          "url": "emoji2-views-helper-1.5.0-alpha01-versionMetadata.json",
          "size": 1317,
          "sha512": "373f7f35002fa483145bcff32c864e10c06b59335a323c3c92fbe06b6d07aeed673103b89a500a4be6e5a931c2bdee756e49cde4d02bd2776212188ae8688adf",
          "sha256": "1f92fa04d9b57998b04776788753148c92eff2c012570e80754280edeba340df",
          "sha1": "a34522e3fe38ef005ebba2d790a230d697238073",
          "md5": "5d097511c796eb7bcf0e1fac28aaabef"
        }
      ]
    }
  ]
}