{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.ui",
    "module": "ui-client",
    "version": "1.0.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "ui-client is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-provider",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "ui-client is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-client-1.0.0-alpha08-sources.jar",
          "url": "ui-client-1.0.0-alpha08-sources.jar",
          "size": 13260,
          "sha512": "6f512800ee3561c921ae1b34b05cd827d417eea9544f62f9877ad8af59bd8ec1341a9670307019ddd37a8bcfa9524588b23e67610719e6d45dfaf4bf2a3451fb",
          "sha256": "e19934f966c5220ed25795bf83b5700689940b6ebc7792bb6f852eaa799aec41",
          "sha1": "342005a3caedcf072cf86a5eeeb99f30d6127800",
          "md5": "e74d3955674ac7999cf5e70be62a484b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "ui-client is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-provider",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "ui-client is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-client-1.0.0-alpha08.aar",
          "url": "ui-client-1.0.0-alpha08.aar",
          "size": 56971,
          "sha512": "94378fa815b5ea22326a4f5fdacdab45e496a2b1cf8b3be3a5fea8253ef82eb85da9152bf10dfaed51d329b0828efea453c9510ccd4706e808e15df46a0f2605",
          "sha256": "5da1faf32468889ce44322cab09aad035e352ac0122d97369d437f128da7b645",
          "sha1": "ffe594736e26ca3ef8379bd752cf0596420951fb",
          "md5": "00ef5761345b146685edfbba1a287f8d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview-poolingcontainer",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-client",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "ui-client is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-provider",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "ui-client is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-client-1.0.0-alpha08.aar",
          "url": "ui-client-1.0.0-alpha08.aar",
          "size": 56971,
          "sha512": "94378fa815b5ea22326a4f5fdacdab45e496a2b1cf8b3be3a5fea8253ef82eb85da9152bf10dfaed51d329b0828efea453c9510ccd4706e808e15df46a0f2605",
          "sha256": "5da1faf32468889ce44322cab09aad035e352ac0122d97369d437f128da7b645",
          "sha1": "ffe594736e26ca3ef8379bd752cf0596420951fb",
          "md5": "00ef5761345b146685edfbba1a287f8d"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "ui-client is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-provider",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "ui-client is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-client-1.0.0-alpha08-versionMetadata.json",
          "url": "ui-client-1.0.0-alpha08-versionMetadata.json",
          "size": 2923,
          "sha512": "f781e028c49dbfea0900d5687deeba40dfd9ff0e3f1be303abdff35d6791434e4457685c9fca88a8389b82b0f1fd2b60842f1b782b24db2faf14bf1edea1cdc3",
          "sha256": "206f7ef54d7af7ddc4e056bb77f7c4244b7fe57a7be34b17884b79735f0766cc",
          "sha1": "6b625914ca4db4ffc7c4f03db07947f155cbd66d",
          "md5": "bc2896537dc43a9f80d1570049543b2f"
        }
      ]
    }
  ]
}