{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-compose",
    "version": "2.8.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-2.8.0-alpha02.aar",
          "url": "lifecycle-runtime-compose-2.8.0-alpha02.aar",
          "size": 54271,
          "sha512": "f6783f85f46e7de9fdd24666210dd4363238d0c0f2d4050d1f84aebf895302ff624319a79a414027c7bccea021d6c88eb0ce57e7887bbd989247ba343d09be7d",
          "sha256": "03d9f31a4b4470a82b22c51af747fd5f680fd0a965c37f1c0622fa4030f748e7",
          "sha1": "e12c1ace731fa9b1cb85cc1d5a403614c38517a2",
          "md5": "ef3a75534c2a6086f586d6d3284efc85"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-2.8.0-alpha02.aar",
          "url": "lifecycle-runtime-compose-2.8.0-alpha02.aar",
          "size": 54271,
          "sha512": "f6783f85f46e7de9fdd24666210dd4363238d0c0f2d4050d1f84aebf895302ff624319a79a414027c7bccea021d6c88eb0ce57e7887bbd989247ba343d09be7d",
          "sha256": "03d9f31a4b4470a82b22c51af747fd5f680fd0a965c37f1c0622fa4030f748e7",
          "sha1": "e12c1ace731fa9b1cb85cc1d5a403614c38517a2",
          "md5": "ef3a75534c2a6086f586d6d3284efc85"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-2.8.0-alpha02-sources.jar",
          "url": "lifecycle-runtime-compose-2.8.0-alpha02-sources.jar",
          "size": 8035,
          "sha512": "6337a4e090504925d2647305a26ab52dad1b06d5ee3c1406a1c150bfa1991c0404aa300a587cbd16b2c1e5900f873bd7f9de003a291ab9e1f793451df03ada3c",
          "sha256": "ed371828df00729d97a4cf812a516dc3527908f6eaf3ee3d126f588b76e0898f",
          "sha1": "a42b20e6985353485ccfdacbecd233e5fb38a42d",
          "md5": "e45f3f71a2877c45390d0ca33935ea1b"
        },
        {
          "name": "lifecycle-runtime-compose-2.8.0-alpha02-samples-sources.jar",
          "url": "lifecycle-runtime-compose-2.8.0-alpha02-samples-sources.jar",
          "size": 2798,
          "sha512": "cbf1343692fbbb0ae6be6349e1e112e89ea98715015def740025c5b5ae155110bc8a8dcccb7462d5b320fc39c3129d5c531892762cbaf625fd05fc6fd86ec5b4",
          "sha256": "c9722f19c81a97b7c63bb9806a068191df6ffa1586803359551ba2da2a32371c",
          "sha1": "f5d7e9e3a63f480e6c86da0e50035dab77b8ce8b",
          "md5": "449617061481013c2b5274eb4c39f38d"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-2.8.0-alpha02-versionMetadata.json",
          "url": "lifecycle-runtime-compose-2.8.0-alpha02-versionMetadata.json",
          "size": 5774,
          "sha512": "f1f96de8bef0f006f13d64e4ebea381bd8187d56a24b363347b275598dee4c4c8efca78e67c9300e446c98477f01f192f4fdaa1c1b4d6ff56ce446b80320b33e",
          "sha256": "2d989106eb0bba491396711cbad8e3c03c90b004ff80b7cc0a2ade1743abc48e",
          "sha1": "ed1cc7b20e2ca7d0e7ae63a5cc223cd6f8e67f1c",
          "md5": "e36c2d885c78b5c08cbffe13fbdb05c8"
        }
      ]
    }
  ]
}