{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.protolayout",
    "module": "protolayout-proto",
    "version": "1.2.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-proto-1.2.0-alpha04.jar",
          "url": "protolayout-proto-1.2.0-alpha04.jar",
          "size": 1180773,
          "sha512": "8bceaeee6d173e3ad7c322ec6005882911c4ceb1f72a473d5b055127c0460b2f99cbf6c768faae307d797c75e435939b9bd961bc548298851b5e4921a793b274",
          "sha256": "762ef52a53c29d23050e22084c355b656c426480bcc0d4a128b2d146d2695a3c",
          "sha1": "6dfe7d811a5d27c6cb0af589f2c37847bca06428",
          "md5": "bbcfe78635a5d3fc7ad56307d9323938"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-proto-1.2.0-alpha04.jar",
          "url": "protolayout-proto-1.2.0-alpha04.jar",
          "size": 1180773,
          "sha512": "8bceaeee6d173e3ad7c322ec6005882911c4ceb1f72a473d5b055127c0460b2f99cbf6c768faae307d797c75e435939b9bd961bc548298851b5e4921a793b274",
          "sha256": "762ef52a53c29d23050e22084c355b656c426480bcc0d4a128b2d146d2695a3c",
          "sha1": "6dfe7d811a5d27c6cb0af589f2c37847bca06428",
          "md5": "bbcfe78635a5d3fc7ad56307d9323938"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-proto-1.2.0-alpha04-sources.jar",
          "url": "protolayout-proto-1.2.0-alpha04-sources.jar",
          "size": 578665,
          "sha512": "afbb2a0bd7a5b59e90359613cdda32e32245d50a0472f7098d8869e6053ac7869d70bb8c2248ecfcd494edbd4cba2ad14c07291d6c89d2df84dce15cc9fa74c2",
          "sha256": "ee0919effd77755d8160071be9f761847b9cb0bba372d1a300d178bb8e68142c",
          "sha1": "b6f3a5a78dee6ff807b7972f84d786773a1310e7",
          "md5": "ce809dcee175c1b2e9f49c72af7430ce"
        }
      ]
    }
  ]
}