{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core",
    "version": "1.13.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.13.0-beta01.aar",
          "url": "core-1.13.0-beta01.aar",
          "size": 1278643,
          "sha512": "12e0f14ef62304b436adfbf5087a7f1e2308d95b218e680b9e7c744365464370db3b6e883d49a0d8be0292ff46c4bb3a935fc65a976ccc79669640ed4bdecdc6",
          "sha256": "9df8cb6811da0890f4054ad15b23201b0625d33c0fcff9209c200d3f412dc370",
          "sha1": "e77b335c9c699265d47b0d7cfc3d9673c668684e",
          "md5": "81e49cd9ea91210381325c4732aa6096"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.interpolator",
          "module": "interpolator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0-beta01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-testing",
          "version": {
            "requires": "1.13.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.13.0-beta01.aar",
          "url": "core-1.13.0-beta01.aar",
          "size": 1278643,
          "sha512": "12e0f14ef62304b436adfbf5087a7f1e2308d95b218e680b9e7c744365464370db3b6e883d49a0d8be0292ff46c4bb3a935fc65a976ccc79669640ed4bdecdc6",
          "sha256": "9df8cb6811da0890f4054ad15b23201b0625d33c0fcff9209c200d3f412dc370",
          "sha1": "e77b335c9c699265d47b0d7cfc3d9673c668684e",
          "md5": "81e49cd9ea91210381325c4732aa6096"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.13.0-beta01-sources.jar",
          "url": "core-1.13.0-beta01-sources.jar",
          "size": 935782,
          "sha512": "f7124162fad133172a0d8b8274fd490660c914e54e2dd644583fc2ad3e4c5ea8fdddeded784c0cad5d5c886ccf2cf0ed50d9b4892ec6a0e5890e80642259333b",
          "sha256": "e3a7e28a5f80b29d64ee5a56ce3dba40447b5fcbb459f5fd997a32ff6a7642b3",
          "sha1": "b7eeff8cd6827ca8366e96b65847e57dc12a34ef",
          "md5": "e6b1945d5657b391d1156e9f2aace884"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-1.13.0-beta01-versionMetadata.json",
          "url": "core-1.13.0-beta01-versionMetadata.json",
          "size": 261348,
          "sha512": "7786941a59a188234d56a5d57ee8c95a3e131c045656faf39ea918831c046c6da3da98f0d550da19f40ed866f556a5a7ab1014a1a9a07a351db4fdf4ae82ed89",
          "sha256": "5aac9b85c287d302171c1852d48ce77b2c3ea012c0cfa0c7fbd84fb08610b059",
          "sha1": "8f5ab82d03b4584bf8e13a37ad7b4622c342767c",
          "md5": "0965b0df6b8a553caab8a0dd7d0bcfb3"
        }
      ]
    }
  ]
}