{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.savedstate",
    "module": "savedstate",
    "version": "1.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-1.3.0-alpha01.aar",
          "url": "savedstate-1.3.0-alpha01.aar",
          "size": 20195,
          "sha512": "09b21e6c673e18b690eda81e80ef1c604bb24adb3be366d751c63d2a0f5dc73725db325e01e7e1b70d9d6286cc9ff0e41d98b93488fd6d4850d4e422b432298e",
          "sha256": "9d8da90e5d0ce98a82597e67cd1c1918fe87db44081f35c63818e219a30f5286",
          "sha1": "2b068728592605b2b0a4cb628d08ebe506e805ac",
          "md5": "9dfa6657c30635014a977b9bca86d38c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-1.3.0-alpha01.aar",
          "url": "savedstate-1.3.0-alpha01.aar",
          "size": 20195,
          "sha512": "09b21e6c673e18b690eda81e80ef1c604bb24adb3be366d751c63d2a0f5dc73725db325e01e7e1b70d9d6286cc9ff0e41d98b93488fd6d4850d4e422b432298e",
          "sha256": "9d8da90e5d0ce98a82597e67cd1c1918fe87db44081f35c63818e219a30f5286",
          "sha1": "2b068728592605b2b0a4cb628d08ebe506e805ac",
          "md5": "9dfa6657c30635014a977b9bca86d38c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-1.3.0-alpha01-sources.jar",
          "url": "savedstate-1.3.0-alpha01-sources.jar",
          "size": 8862,
          "sha512": "cff741a7e1850425e03a9c2d5baa9e972b35c966551d36b6beaa692fdea00016b4a809d948c3368a5f88857f084f4307a9af3130263977d40d4dcfe185c85878",
          "sha256": "d0ce71cd4aa5eef5bef2591f7ed48945392088296cc4ad4273b8dbe5dfeeb72b",
          "sha1": "a29c8311ab1a9ef67f167f56d781b910c6e05571",
          "md5": "67828594e6be3d20724e2c4480fb7423"
        }
      ]
    }
  ]
}