{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.glance",
    "module": "glance-appwidget-preview",
    "version": "1.1.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-preview-1.1.0-rc01-sources.jar",
          "url": "glance-appwidget-preview-1.1.0-rc01-sources.jar",
          "size": 4999,
          "sha512": "d6e22b3e5723a7f827f36af703146aefc703c58ffd6d41ad28bbe88fe2cfdba76f692302330d15482e99f0aa65633d1a1ab5d0ab865cab10b9e5c0cd614484ea",
          "sha256": "d53d8673efe9b3218b2813c7779ddbcf4c3ae3772af201ab668071fecdb3a5a5",
          "sha1": "b8a5a96a86403a859ac8fd81c61bce02ecaf4913",
          "md5": "6065a16fb4550375a353989815970164"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-preview-1.1.0-rc01.aar",
          "url": "glance-appwidget-preview-1.1.0-rc01.aar",
          "size": 14948,
          "sha512": "b10876673da9f15b53c4eddf8496f8146e4da451852410eb87aec848909dceced264a67f8e37f113d8a8a5d611896da320268abe4a1ad65d3da13fb4e71be524",
          "sha256": "b5c8c22120b0ee130997d2893c7ac30158ca75fd308c4829c098a5054a6cca06",
          "sha1": "01af5b754408f4f8cb1eb80f31fe9b290a2d4fe5",
          "md5": "6caf361d039bc5e1164f56737928ffca"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-preview-1.1.0-rc01.aar",
          "url": "glance-appwidget-preview-1.1.0-rc01.aar",
          "size": 14948,
          "sha512": "b10876673da9f15b53c4eddf8496f8146e4da451852410eb87aec848909dceced264a67f8e37f113d8a8a5d611896da320268abe4a1ad65d3da13fb4e71be524",
          "sha256": "b5c8c22120b0ee130997d2893c7ac30158ca75fd308c4829c098a5054a6cca06",
          "sha1": "01af5b754408f4f8cb1eb80f31fe9b290a2d4fe5",
          "md5": "6caf361d039bc5e1164f56737928ffca"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-preview is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-preview-1.1.0-rc01-versionMetadata.json",
          "url": "glance-appwidget-preview-1.1.0-rc01-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}