{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.javascriptengine",
    "module": "javascriptengine",
    "version": "1.0.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "javascriptengine-1.0.0-beta01-sources.jar",
          "url": "javascriptengine-1.0.0-beta01-sources.jar",
          "size": 44223,
          "sha512": "8ab3a5788cd50d7e4e22bc4c2c6f338f74997e65515a57d06fd63ff2467b49862bc94710f5b350ce220bfc3137f9cddffb9d1f542a51c76c34d18f85dcdad60c",
          "sha256": "384084540dedc522c113aee9bd9669231f02ee35fafaf019fd6e297d16760f74",
          "sha1": "888aea34578c93feedbe2246f2807351300a3c41",
          "md5": "96fd5a1cd6c2aa16c4f45414ef194a9f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-android"
          }
        }
      ],
      "files": [
        {
          "name": "javascriptengine-1.0.0-beta01.aar",
          "url": "javascriptengine-1.0.0-beta01.aar",
          "size": 72634,
          "sha512": "6adf492936835e764daae617c70eb49fb57bd4384e9b07888a88414c8f3449651d08aa5abf8368745d8f7a1fc2ba5055cc032116eca5bc1f76ee2aab85a1d56a",
          "sha256": "773cc3cdea8b573caa879bfad9bb92d3c3c7e961dd81e8c49628ff6dc6a5a1e4",
          "sha1": "81964937cbdb1559bb8a0872ffb64cc267e57309",
          "md5": "7060aac3398cefe5700b39327edfd250"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-android"
          }
        }
      ],
      "files": [
        {
          "name": "javascriptengine-1.0.0-beta01.aar",
          "url": "javascriptengine-1.0.0-beta01.aar",
          "size": 72634,
          "sha512": "6adf492936835e764daae617c70eb49fb57bd4384e9b07888a88414c8f3449651d08aa5abf8368745d8f7a1fc2ba5055cc032116eca5bc1f76ee2aab85a1d56a",
          "sha256": "773cc3cdea8b573caa879bfad9bb92d3c3c7e961dd81e8c49628ff6dc6a5a1e4",
          "sha1": "81964937cbdb1559bb8a0872ffb64cc267e57309",
          "md5": "7060aac3398cefe5700b39327edfd250"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "javascriptengine-1.0.0-beta01-versionMetadata.json",
          "url": "javascriptengine-1.0.0-beta01-versionMetadata.json",
          "size": 6312,
          "sha512": "503ecd92804478a8687aea16ca4f4370827249e9fa51f58911a4834fe4bb6ee7cabc793f1541b76987626982d7d36372fcb94e4d272df5a8bed56cf4ecf9440f",
          "sha256": "bbf00815b2a445778e6fbc115024b7dbe0b747d19970a1d8355919d5d2f1c085",
          "sha1": "ba0a38a15cb81601f22215ce83c8886dd6aabdb3",
          "md5": "a45c105f77f13bd6ab1e63c68fe0e42f"
        }
      ]
    }
  ]
}