version: "2.7.0-alpha03"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.room"
    artifact_id: "room-common"
    version: "2.7.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.room"
    artifact_id: "room-runtime-android"
    version: "2.7.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.room"
    artifact_id: "room-runtime-jvm"
    version: "2.7.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.room"
    artifact_id: "room-runtime-linuxx64"
    version: "2.7.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite"
    version: "2.5.0-alpha03"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.room"
group_id: "androidx.room"
artifact_id: "room-runtime"
path: "/room/room-runtime"
sha: "6a85f1fcebea213d864708625843f2cfb0bf24d4"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.room-room-runtime-all-11894512-2.7.0-alpha03.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
  dependency {
    group_id: "androidx.room"
    artifact_id: "room-common"
    version: "2.7.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.room"
    artifact_id: "room-compiler"
    version: "2.7.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.room"
    artifact_id: "room-compiler-processing"
    version: "2.7.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.room"
    artifact_id: "room-compiler-processing-testing"
    version: "2.7.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.room"
    artifact_id: "room-external-antlr"
    version: "2.7.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.room"
    artifact_id: "room-gradle-plugin"
    version: "2.7.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.room"
    artifact_id: "room-guava"
    version: "2.7.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.room"
    artifact_id: "room-ktx"
    version: "2.7.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.room"
    artifact_id: "room-migration"
    version: "2.7.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.room"
    artifact_id: "room-paging"
    version: "2.7.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.room"
    artifact_id: "room-paging-guava"
    version: "2.7.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.room"
    artifact_id: "room-paging-rxjava2"
    version: "2.7.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.room"
    artifact_id: "room-paging-rxjava3"
    version: "2.7.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.room"
    artifact_id: "room-rxjava2"
    version: "2.7.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.room"
    artifact_id: "room-rxjava3"
    version: "2.7.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.room"
    artifact_id: "room-testing"
    version: "2.7.0-alpha03"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: true
