version: "1.7.0-alpha03"
dependency_list {
  dependency {
    group_id: "androidx.compose.animation"
    artifact_id: "animation-android"
    version: "1.7.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.animation"
    artifact_id: "animation-core"
    version: "1.7.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.animation"
    artifact_id: "animation-desktop"
    version: "1.7.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.foundation"
    artifact_id: "foundation-layout"
    version: "1.6.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime"
    version: "1.6.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui"
    version: "1.6.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-geometry"
    version: "1.6.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.compose.animation"
group_id: "androidx.compose.animation"
artifact_id: "animation"
path: "/compose/animation/animation"
sha: "6051cad23e2ba97fd1fdeea218cec5119d8213de"
require_same_version_group_build: true
group_zip_path: "per-group-zips/gmaven-androidx-compose-animation-11436812.zip"
project_zip_path: "per-project-zips/androidx.compose.animation-animation-all-11436812-1.7.0-alpha03.zip"
kotlin_version: "1.9.22"
dependency_constraint_list {
  dependency {
    group_id: "androidx.compose.animation"
    artifact_id: "animation-core"
    version: "1.7.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.animation"
    artifact_id: "animation-graphics"
    version: "1.7.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.animation"
    artifact_id: "animation-tooling-internal"
    version: "1.7.0-alpha03"
    is_tip_of_tree: true
  }
}
