version: "1.0.0"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-experimental"
    version: "1.4.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.8.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.graphics"
group_id: "androidx.graphics"
artifact_id: "graphics-core"
path: "/graphics/graphics-core"
sha: "8e24ec7cf4ee1c5afe2b4a3a108f926420140662"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.graphics-graphics-core-all-11954666-1.0.0.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
