{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation/1.7.0-alpha03/foundation-1.7.0-alpha03.module",
    "group": "androidx.compose.foundation",
    "module": "foundation",
    "version": "1.7.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-release.aar",
          "url": "foundation-android-1.7.0-alpha03.aar",
          "size": 4678507,
          "sha512": "1f758bbea2e98f5a237b768995a93df48912ee2b8a8eaaa461337ef4fbbce173a77104e344d290ffaf2489ecc983a894aa8bba90748836caf1209eb7ff899f48",
          "sha256": "794a084ccb24472d96fc278526e8a1251f792fbe1fd3c83de14ec29e739d4356",
          "sha1": "7cbd78ccff55b50f5d5cd1fa50d7548cafb2d709",
          "md5": "f85237c09c08055e2f0e8ca3d23aa269"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-release.aar",
          "url": "foundation-android-1.7.0-alpha03.aar",
          "size": 4678507,
          "sha512": "1f758bbea2e98f5a237b768995a93df48912ee2b8a8eaaa461337ef4fbbce173a77104e344d290ffaf2489ecc983a894aa8bba90748836caf1209eb7ff899f48",
          "sha256": "794a084ccb24472d96fc278526e8a1251f792fbe1fd3c83de14ec29e739d4356",
          "sha1": "7cbd78ccff55b50f5d5cd1fa50d7548cafb2d709",
          "md5": "f85237c09c08055e2f0e8ca3d23aa269"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-android-1.7.0-alpha03-sources.jar",
          "url": "foundation-android-1.7.0-alpha03-sources.jar",
          "size": 821142,
          "sha512": "749a0c1d7a767805c79bf219f4dc9b102308ccda6dde2dea876400b1f53cedc01bb1d117b5018432cfc0df11057a2db279d187774b824adaa34a0e86d0ac2a17",
          "sha256": "5d1ea03238f40713c42176a72a2e45c07d017e118fe3b3d2f0ea7c54126f9e3f",
          "sha1": "86f29b2e81e23cead013c8d00db87c3f82e2be15",
          "md5": "ee0cbfbeee6c499a609b5f0c901db2b2"
        }
      ]
    }
  ]
}