{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-animation",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-animation-1.0.0-sources.jar",
          "url": "core-animation-1.0.0-sources.jar",
          "size": 115942,
          "sha512": "27c69f53b4970085618090c2bbf1bc838afc0a662e9fdef095d444ffa48732e0997dbbbe480e985cd5ea904eb6d45eac9e00acbd20d6d769916eeed39e592acd",
          "sha256": "d624a7ac204e2d5b351a4d58fabe5ee39696dab8e036baa19a3ae195edc74334",
          "sha1": "f369e89643e2710b875a2db1a838e7b648c2b5cd",
          "md5": "e50d483bc83fcae47f8e92ffb47e20eb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-animation-1.0.0.aar",
          "url": "core-animation-1.0.0.aar",
          "size": 121862,
          "sha512": "2a1aa5e2b039cbf2791333a3aadfde8c2df095db5fb1163d1c8d5a5709645e0037130519892619c53f8d8f31edcd8e9dd9f8742e4e8aea0a4da15ee7820acbae",
          "sha256": "3aae7d58ad645bf2e4181a05506d327605d0c0d03b81bbdd128b065f37a74c71",
          "sha1": "79d6687bf67d1d6cdd52d4c0b273d0c2a194711b",
          "md5": "5af7873480b5e438064d135d73bb2e2d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-animation-1.0.0.aar",
          "url": "core-animation-1.0.0.aar",
          "size": 121862,
          "sha512": "2a1aa5e2b039cbf2791333a3aadfde8c2df095db5fb1163d1c8d5a5709645e0037130519892619c53f8d8f31edcd8e9dd9f8742e4e8aea0a4da15ee7820acbae",
          "sha256": "3aae7d58ad645bf2e4181a05506d327605d0c0d03b81bbdd128b065f37a74c71",
          "sha1": "79d6687bf67d1d6cdd52d4c0b273d0c2a194711b",
          "md5": "5af7873480b5e438064d135d73bb2e2d"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-animation-1.0.0-versionMetadata.json",
          "url": "core-animation-1.0.0-versionMetadata.json",
          "size": 21867,
          "sha512": "02932f278bd7755cc69f5d7b62ac3c8f9cd7169b05f04d375c22e9009ccb78008625bc2ef62663dfc7bc54911846e29fe7d1f604ffebb96cb5ea6d8e1a1a5640",
          "sha256": "599dfe381b3642e00c714e7991b21bc70241f9a04a53fb89c8ca65b35de603b4",
          "sha1": "f83cc09d568397ef0c731d75a9021a4683283e72",
          "md5": "836f97e2ec2a21d08b77e5806d4529ac"
        }
      ]
    }
  ]
}