{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-paging-guava",
    "version": "2.7.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-paging-guava-2.7.0-alpha03-sources.jar",
          "url": "room-paging-guava-2.7.0-alpha03-sources.jar",
          "size": 2850,
          "sha512": "2a92e7b857544e5dff4819bd1d50cbf14075df5e6f96770786ccca2be2142cb33e217a551d132f55b092a81311323066f51d2cc24040757704b1037c4bb9f1e9",
          "sha256": "a0bc4b8731307c923032ec4713781e89b068c07d522856f50114a3c45e751cc6",
          "sha1": "6290cb9c0ae524ce3aa24a69268b1a6b62ff5099",
          "md5": "eb7e1557389af503bc95939625173b4a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-paging-guava-2.7.0-alpha03.aar",
          "url": "room-paging-guava-2.7.0-alpha03.aar",
          "size": 10106,
          "sha512": "88a536cdf5a3cce878d628a799c4a5edad13b0878274301a77c7cba5555c04b955bdc2f8651865dbe24f902cff9ecef33457ec4f0a5482eff6da5bc4375498d6",
          "sha256": "d97331aa4af7827b1e0cd78daf8354c624f10103534a8730af4f32212d454e0b",
          "sha1": "54b8db3dad15045cf3e23e02dfa1d12b795be215",
          "md5": "ac37a8f088c41846d6d91d2efa2bb896"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha03"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-paging-guava-2.7.0-alpha03.aar",
          "url": "room-paging-guava-2.7.0-alpha03.aar",
          "size": 10106,
          "sha512": "88a536cdf5a3cce878d628a799c4a5edad13b0878274301a77c7cba5555c04b955bdc2f8651865dbe24f902cff9ecef33457ec4f0a5482eff6da5bc4375498d6",
          "sha256": "d97331aa4af7827b1e0cd78daf8354c624f10103534a8730af4f32212d454e0b",
          "sha1": "54b8db3dad15045cf3e23e02dfa1d12b795be215",
          "md5": "ac37a8f088c41846d6d91d2efa2bb896"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-paging-guava-2.7.0-alpha03-versionMetadata.json",
          "url": "room-paging-guava-2.7.0-alpha03-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}