version: "1.3.0-alpha02"
dependency_list {
  dependency {
    group_id: "androidx.tracing"
    artifact_id: "tracing"
    version: "1.3.0-alpha02"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.tracing"
group_id: "androidx.tracing"
artifact_id: "tracing-ktx"
path: "/tracing/tracing-ktx"
sha: "ad6bfd28037d5d5295d6de24cd2754dceb712b74"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.tracing-tracing-ktx-all-11623079-1.3.0-alpha02.zip"
kotlin_version: "1.9.23"
dependency_constraint_list {
  dependency {
    group_id: "androidx.tracing"
    artifact_id: "tracing"
    version: "1.3.0-alpha02"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
