{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.emoji",
    "module": "emoji",
    "version": "1.2.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "emoji-1.2.0-alpha03.aar",
          "url": "emoji-1.2.0-alpha03.aar",
          "size": 141602,
          "sha512": "ff3c5375cad715faae7e5a2a5a433bc2f9bc6b1613eebfbc4c9bc05da98247af5c6b346e299b585c3015e1d85cde2d7f41ead47dd11a6469b99de911c3bc0867",
          "sha256": "cf477362154f212a1c8e00ef09c1f4b08f45badb301c2c4a30fad4517ef60d3d",
          "sha1": "7f2b54772a3fe8e1823a2e2d0ea6f0632ecf8362",
          "md5": "ecd6c85c73cf3c1792a230b0eb8d48ab"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "emoji-1.2.0-alpha03.aar",
          "url": "emoji-1.2.0-alpha03.aar",
          "size": 141602,
          "sha512": "ff3c5375cad715faae7e5a2a5a433bc2f9bc6b1613eebfbc4c9bc05da98247af5c6b346e299b585c3015e1d85cde2d7f41ead47dd11a6469b99de911c3bc0867",
          "sha256": "cf477362154f212a1c8e00ef09c1f4b08f45badb301c2c4a30fad4517ef60d3d",
          "sha1": "7f2b54772a3fe8e1823a2e2d0ea6f0632ecf8362",
          "md5": "ecd6c85c73cf3c1792a230b0eb8d48ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "emoji-1.2.0-alpha03-sources.jar",
          "url": "emoji-1.2.0-alpha03-sources.jar",
          "size": 58945,
          "sha512": "985c6860239a4f84891bb7607b781729ee64bc38345f8a4925b2fc4de2975eb9eda98f1da61aecaf9ac99ea6f3a73b427b5626c9686aab3a5fc16392cf8f332b",
          "sha256": "e4f3262cd4f0c9a0ac79ed079c9a7f17bf555bf64b9e75091aa6459bcc82aa22",
          "sha1": "ee6199342b8442b47aff84a438cebe7c861f6afa",
          "md5": "3c64cee341a1b2c2bb3356c52223e78e"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "emoji-1.2.0-alpha03-versionMetadata.json",
          "url": "emoji-1.2.0-alpha03-versionMetadata.json",
          "size": 8269,
          "sha512": "ecd6b9bdccbb58465da0a77eca85391d02a6c2b3a2d84ce5480c7807decdd053f12a711b29f722827b4348245343b84c9c0fecc42bc607b51885f5ff58f07542",
          "sha256": "deae0a8dc6f3d55e4771fc700a80417e9d09e9d10485339d6192e1926ca496a7",
          "sha1": "ebaa01620c84b7ff310297e4488042ab205bd3de",
          "md5": "8f0e7e1223db0cd90469451fa8601f43"
        }
      ]
    }
  ]
}