version: "1.1.0-beta01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.1.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-runtime"
    version: "2.5.1"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.hilt"
group_id: "androidx.hilt"
artifact_id: "hilt-navigation"
path: "/hilt/hilt-navigation"
sha: "465f5655706f58911cf75e9b2e0eb13b9363a36a"
require_same_version_group_build: false
group_zip_path: "per-group-zips/gmaven-androidx-hilt-11013992.zip"
project_zip_path: "per-project-zips/androidx.hilt-hilt-navigation-all-11013992-1.1.0-beta01.zip"
kotlin_version: "1.9.10"
dependency_constraint_list {
}
