{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-fragment-ktx",
    "version": "2.8.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-ktx-2.8.0-beta03-sources.jar",
          "url": "navigation-fragment-ktx-2.8.0-beta03-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-beta03"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "Mirror navigation-fragment dependency graph for -ktx artifacts"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-ktx-2.8.0-beta03.aar",
          "url": "navigation-fragment-ktx-2.8.0-beta03.aar",
          "size": 1348,
          "sha512": "ed030294e397580666e56af7d2da63c1c554dadba6834e61959e97042b323de25ac00b7ff4fc9185fc9da42ced4346ed097e0f5ade120dc3e91958eb439ed441",
          "sha256": "318efd693d3a1813f3c2a706302114612ffcd38d96228433daacc65f76a55002",
          "sha1": "40961e8ef087c8df66b2bdf791aacf20423ac818",
          "md5": "2136baee212181e963677da6972193ef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-beta03"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "Mirror navigation-fragment dependency graph for -ktx artifacts"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-ktx-2.8.0-beta03.aar",
          "url": "navigation-fragment-ktx-2.8.0-beta03.aar",
          "size": 1348,
          "sha512": "ed030294e397580666e56af7d2da63c1c554dadba6834e61959e97042b323de25ac00b7ff4fc9185fc9da42ced4346ed097e0f5ade120dc3e91958eb439ed441",
          "sha256": "318efd693d3a1813f3c2a706302114612ffcd38d96228433daacc65f76a55002",
          "sha1": "40961e8ef087c8df66b2bdf791aacf20423ac818",
          "md5": "2136baee212181e963677da6972193ef"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-ktx-2.8.0-beta03-versionMetadata.json",
          "url": "navigation-fragment-ktx-2.8.0-beta03-versionMetadata.json",
          "size": 3940,
          "sha512": "479e68a1bc895eedfc5a278ea3043cc0192449480b791c45eae572d25de8bf0e259c7b332476e8bd7948d0676af5f97af718bc34c4a2c7d358a38c51bd1311a7",
          "sha256": "b34485ebe0f3fee192573065288ea48db4c524e3a7be43a8cf51033b04306410",
          "sha1": "6da3af1a51cd71422c6413d6d81111ad5a108efb",
          "md5": "eab5779d224a2e384a04b72235fabb82"
        }
      ]
    }
  ]
}