{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media2",
    "module": "media2-exoplayer",
    "version": "1.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.media2",
          "module": "media2-common",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "androidx.media2",
          "module": "media2-player",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "androidx.media2",
          "module": "media2-session",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "androidx.media2",
          "module": "media2-widget",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "media2-exoplayer-1.3.0-alpha01.aar",
          "url": "media2-exoplayer-1.3.0-alpha01.aar",
          "size": 1234060,
          "sha512": "ca55b98c1043de00ecfa98f0e4438124e3b6ca685366075f82714fabfb4c141300ff464ad5ebca60b79758ea5b6379b55a5b1e960f0bfba412a24bc2885ea3a1",
          "sha256": "7aa3aa71010fbc9f3279adbecc8bfded377188173dd0223b165e81361c7ecc9e",
          "sha1": "c72dd7437ca0d217d97a4e5b4308ea4eb6d20891",
          "md5": "72a0f7226c1fdb8f2408ebc20e878e0e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.media2",
          "module": "media2-common",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "androidx.media2",
          "module": "media2-player",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "androidx.media2",
          "module": "media2-session",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "androidx.media2",
          "module": "media2-widget",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "media2-exoplayer-1.3.0-alpha01.aar",
          "url": "media2-exoplayer-1.3.0-alpha01.aar",
          "size": 1234060,
          "sha512": "ca55b98c1043de00ecfa98f0e4438124e3b6ca685366075f82714fabfb4c141300ff464ad5ebca60b79758ea5b6379b55a5b1e960f0bfba412a24bc2885ea3a1",
          "sha256": "7aa3aa71010fbc9f3279adbecc8bfded377188173dd0223b165e81361c7ecc9e",
          "sha1": "c72dd7437ca0d217d97a4e5b4308ea4eb6d20891",
          "md5": "72a0f7226c1fdb8f2408ebc20e878e0e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.media2",
          "module": "media2-common",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "androidx.media2",
          "module": "media2-player",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "androidx.media2",
          "module": "media2-session",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "androidx.media2",
          "module": "media2-widget",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "media2-exoplayer-1.3.0-alpha01-sources.jar",
          "url": "media2-exoplayer-1.3.0-alpha01-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}