{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.constraintlayout",
    "module": "constraintlayout-core",
    "version": "1.1.0-alpha13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "constraintlayout-core-1.1.0-alpha13.jar",
          "url": "constraintlayout-core-1.1.0-alpha13.jar",
          "size": 581175,
          "sha512": "59a9fa3e7ad7720c0b95bf5780bfbf059ffe5b016bfc0bc42bf708e6b29e887ea1b13ab02a77840fe58ba9c41ab84140ff7c8442a9d09f868d2e542bf72e467a",
          "sha256": "d582ff98d0a37a2b289f47510e688d6b756b5557bab0328e4bb23b2848d28910",
          "sha1": "26cefda7f907c9bd64dd8d1508ae32ab06f84ab1",
          "md5": "3d648f2f7d02b4397a1d939bfa377dc0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "constraintlayout-core-1.1.0-alpha13.jar",
          "url": "constraintlayout-core-1.1.0-alpha13.jar",
          "size": 581175,
          "sha512": "59a9fa3e7ad7720c0b95bf5780bfbf059ffe5b016bfc0bc42bf708e6b29e887ea1b13ab02a77840fe58ba9c41ab84140ff7c8442a9d09f868d2e542bf72e467a",
          "sha256": "d582ff98d0a37a2b289f47510e688d6b756b5557bab0328e4bb23b2848d28910",
          "sha1": "26cefda7f907c9bd64dd8d1508ae32ab06f84ab1",
          "md5": "3d648f2f7d02b4397a1d939bfa377dc0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "constraintlayout-core-1.1.0-alpha13-sources.jar",
          "url": "constraintlayout-core-1.1.0-alpha13-sources.jar",
          "size": 356481,
          "sha512": "769fd0778b109e0d15e668b3deb06a537e0d5982750d6280e97384b87a4723e81b23bafed84596f6ff322094bd18337883d253109732df51d2e455c82eb69a44",
          "sha256": "b292351ffa01e4adcbd692c0d14bf2361a9429a6b08a4327e074b24a6930bf68",
          "sha1": "07444ab79385e7dc5b06e381e2095e4c7c669903",
          "md5": "39c3826f7caedee6ed4a1769be6ab313"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "constraintlayout-core-1.1.0-alpha13-versionMetadata.json",
          "url": "constraintlayout-core-1.1.0-alpha13-versionMetadata.json",
          "size": 209225,
          "sha512": "5c8051e0346eda928021aaff3c6310c8a6afaa2cf21821e48c9901d6b677d5f0b807dec5e933581ed0da2f14a304dfe7729cfd2eb2d3ea1d4c4318b38f0e2671",
          "sha256": "142808e521fd498612393e2350f4d5f22c6687b822526e62f2ad161ec865133a",
          "sha1": "90e1d0df7db178c77dd8a46628613d60f8caca09",
          "md5": "e299a5be461d1b9f1d457c4c1e369ef9"
        }
      ]
    }
  ]
}