{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.recyclerview",
    "module": "recyclerview",
    "version": "1.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recyclerview-1.4.0-alpha01-sources.jar",
          "url": "recyclerview-1.4.0-alpha01-sources.jar",
          "size": 336584,
          "sha512": "d0314b5769870192e6bcdde69782856a26afb50ec38c329fc09f736c5ec01a9529acfc8943ce84818266cc88ba777ea0ec719bd252845b83024341b27ee1679e",
          "sha256": "aac3228f332b8e17aba0ae934d9eef37c28667ecfe3f50aa6e7a4469097edb39",
          "sha1": "ea7b4a02c59db599375f52b26f70e71158c700c9",
          "md5": "403db96b2262ef1c0bb206ecd318cb1b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.14.0-alpha01"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.4.0-alpha01.aar",
          "url": "recyclerview-1.4.0-alpha01.aar",
          "size": 423113,
          "sha512": "c822e57299e9e0d4fc68b8fff2144f16a8aa2f107834d329227dded229476ab60428adbb9d969626e3f1ec6c1552415a6e47eaef865e02fa1913e594558f7c9c",
          "sha256": "897bf86b3e82803969c18aec7081840002ac3cac5b50c0eb0810827477763590",
          "sha1": "2cf93cc8c78f328862dcb0ea4c083b0adac3c60a",
          "md5": "78c20211a4bbebecece19367e2913e04"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.14.0-alpha01"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview-poolingcontainer",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.4.0-alpha01.aar",
          "url": "recyclerview-1.4.0-alpha01.aar",
          "size": 423113,
          "sha512": "c822e57299e9e0d4fc68b8fff2144f16a8aa2f107834d329227dded229476ab60428adbb9d969626e3f1ec6c1552415a6e47eaef865e02fa1913e594558f7c9c",
          "sha256": "897bf86b3e82803969c18aec7081840002ac3cac5b50c0eb0810827477763590",
          "sha1": "2cf93cc8c78f328862dcb0ea4c083b0adac3c60a",
          "md5": "78c20211a4bbebecece19367e2913e04"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "recyclerview-1.4.0-alpha01-versionMetadata.json",
          "url": "recyclerview-1.4.0-alpha01-versionMetadata.json",
          "size": 75101,
          "sha512": "bc30150541e61678b0d3ccaf044a2b9e7f26846ab5f86a12d813748b439efc96cd77770736bafaf297223bd9d07f9e6d2c9f360b414b0321209b93b488c2d390",
          "sha256": "c704f5a13a8abbb95e8ecdc53a96725ff2c6fab94a26b57a537c035af5d77a8d",
          "sha1": "b99ab3d85ab5c949414e084b8bc41fa108ffc9a8",
          "md5": "14dc97d05aa07129f15a85fd7426487d"
        }
      ]
    }
  ]
}