{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-migration",
    "version": "2.7.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-migration-2.7.0-alpha01.jar",
          "url": "room-migration-2.7.0-alpha01.jar",
          "size": 44953,
          "sha512": "462a39f54dab84ac56ba64f89b4247480ff2945c485c375c5b784163324dc217d002a860f2233f8299e5903210022bc597363357597779fcfad4afbf0a4562f5",
          "sha256": "645c63aa615e0ec1c3a1237be94707984318fd9988b95e02a9f09a3b4612e1e5",
          "sha1": "9438b225624b1a65c7fad559967c49685ced8d19",
          "md5": "34b6ee9bc27fbfd8a2175eb63e634bd9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha01"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-migration-2.7.0-alpha01.jar",
          "url": "room-migration-2.7.0-alpha01.jar",
          "size": 44953,
          "sha512": "462a39f54dab84ac56ba64f89b4247480ff2945c485c375c5b784163324dc217d002a860f2233f8299e5903210022bc597363357597779fcfad4afbf0a4562f5",
          "sha256": "645c63aa615e0ec1c3a1237be94707984318fd9988b95e02a9f09a3b4612e1e5",
          "sha1": "9438b225624b1a65c7fad559967c49685ced8d19",
          "md5": "34b6ee9bc27fbfd8a2175eb63e634bd9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-migration-2.7.0-alpha01-sources.jar",
          "url": "room-migration-2.7.0-alpha01-sources.jar",
          "size": 16537,
          "sha512": "f9c7e16b17c8a7a8da2a3f42a3e57e92add24df15567f8c3e6bbeb2f3a750f04649bff58aa8c592e88f4b7b227ddeb00022ebc305e528201f002e504fdca47bc",
          "sha256": "7e6d7ed8ef5fbdad051a04164db40e89c2c81736d4ca0dea1b69fb881ce7bc4f",
          "sha1": "a488712f9a891028f4a647b56ba9ee06ff6f81e5",
          "md5": "30fea6645faeff9ee34452f0055f1641"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-migration is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-migration-2.7.0-alpha01-versionMetadata.json",
          "url": "room-migration-2.7.0-alpha01-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}