version: "1.0.0-alpha13"
dependency_list {
  dependency {
    group_id: "androidx.activity"
    artifact_id: "activity"
    version: "1.8.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.6.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.12.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core-ktx"
    version: "1.12.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.privacysandbox.sdkruntime"
group_id: "androidx.privacysandbox.sdkruntime"
artifact_id: "sdkruntime-core"
path: "/privacysandbox/sdkruntime/sdkruntime-core"
sha: "319668a0bb17aaa0caa7dda23b37b170b1bf02cd"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.privacysandbox.sdkruntime-sdkruntime-core-all-11904167-1.0.0-alpha13.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
  dependency {
    group_id: "androidx.privacysandbox.sdkruntime"
    artifact_id: "sdkruntime-client"
    version: "1.0.0-alpha13"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.sdkruntime"
    artifact_id: "sdkruntime-provider"
    version: "1.0.0-alpha13"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
