{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-fragment",
    "version": "2.8.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.8.0-beta03-sources.jar",
          "url": "navigation-fragment-2.8.0-beta03-sources.jar",
          "size": 28197,
          "sha512": "53e09b3bc9fd93f967ce8756c324da13a3cad949382d789a8479cc38c6ae5375010d21771b7305fb8082b4e44b181702dfc311038fa95e3f7381f0cf441cdadf",
          "sha256": "c49ec68718c7917d080c4b839481614d22ea88608e3d68cd56cc11e7bf0c19e9",
          "sha1": "93a8cc0f4a24653a175a680d4e40b90aad379092",
          "md5": "589e9aff86b410e8052b981adf5704cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          }
        },
        {
          "group": "androidx.slidingpanelayout",
          "module": "slidingpanelayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.8.0-beta03.aar",
          "url": "navigation-fragment-2.8.0-beta03.aar",
          "size": 95671,
          "sha512": "edf3bdf0c8a2f16a93af3b603b0046fe6e18911c0652355a9342a90a90933e90b08d0bf3ccec1e61df8f1f66cbd980f02adcd085838170882ea5a6c4203f65f0",
          "sha256": "a755f1920fdf848d74e27a13d217ffae1fbf4361ddc16284497a925eb0c19ea9",
          "sha1": "0cfe6c43faf9e1d71b9fa1db19a4753e59a9013f",
          "md5": "3ea9f54c01ad43fb34752836e60976d9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          }
        },
        {
          "group": "androidx.slidingpanelayout",
          "module": "slidingpanelayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.8.0-beta03.aar",
          "url": "navigation-fragment-2.8.0-beta03.aar",
          "size": 95671,
          "sha512": "edf3bdf0c8a2f16a93af3b603b0046fe6e18911c0652355a9342a90a90933e90b08d0bf3ccec1e61df8f1f66cbd980f02adcd085838170882ea5a6c4203f65f0",
          "sha256": "a755f1920fdf848d74e27a13d217ffae1fbf4361ddc16284497a925eb0c19ea9",
          "sha1": "0cfe6c43faf9e1d71b9fa1db19a4753e59a9013f",
          "md5": "3ea9f54c01ad43fb34752836e60976d9"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.8.0-beta03-versionMetadata.json",
          "url": "navigation-fragment-2.8.0-beta03-versionMetadata.json",
          "size": 12494,
          "sha512": "bf9d05a95010ec64344ab1352f901ecc34a2dfb384be8ea613feccd456d725b57b94e4bbaa666f9edb28a992eef622ace186bb5a57c139625f8f241c4e9096f1",
          "sha256": "2fdf0c267c2b7127e92de91a21c8fd7cc803a21bfd7f4aef3a7b4a005283be1c",
          "sha1": "9fb32cbd08fed879e8212c3ed2adbaa4b5120573",
          "md5": "2434dca795aaec27fe24923cdf71f8e4"
        }
      ]
    }
  ]
}