{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.watchface",
    "module": "watchface-data",
    "version": "1.3.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-data-1.3.0-alpha03-sources.jar",
          "url": "watchface-data-1.3.0-alpha03-sources.jar",
          "size": 74323,
          "sha512": "51c1b9e1841b40432e9d1d3156a950cbe94bb65ab134c6a2c0df62846bb1a4effdaa53f9705a422c56079fc3d9185cb8918fd80b93fc33b09fb577a59df82a24",
          "sha256": "5e44c4c0e9e245d55bdaa743b069accf11c5fa7a7b41856da9032f17d2f00111",
          "sha1": "a7f77f98b01d6336286d5b0106dd0e4c007f8d67",
          "md5": "26089516605972d497101f0453c12673"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-data-1.3.0-alpha03.aar",
          "url": "watchface-data-1.3.0-alpha03.aar",
          "size": 221429,
          "sha512": "4e371bade5ff49fa86c3c15a7bae3b91f9865cb3d783796aca8b40387d6a5e92664ddb490c598edd500bdfeb90a70e82dc88305dcac3babb9452a026932bea1a",
          "sha256": "e7f1e4986a19daddc355ee16a72629b63e1cf4ed0bdfe0aadabf20226b7c4b97",
          "sha1": "5cfc0b9223abdcfedd034bd2fef1728b261b4b1c",
          "md5": "67cea3967cb91f14fa910eea69d0fc9d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-data-1.3.0-alpha03.aar",
          "url": "watchface-data-1.3.0-alpha03.aar",
          "size": 221429,
          "sha512": "4e371bade5ff49fa86c3c15a7bae3b91f9865cb3d783796aca8b40387d6a5e92664ddb490c598edd500bdfeb90a70e82dc88305dcac3babb9452a026932bea1a",
          "sha256": "e7f1e4986a19daddc355ee16a72629b63e1cf4ed0bdfe0aadabf20226b7c4b97",
          "sha1": "5cfc0b9223abdcfedd034bd2fef1728b261b4b1c",
          "md5": "67cea3967cb91f14fa910eea69d0fc9d"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-data is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-data-1.3.0-alpha03-versionMetadata.json",
          "url": "watchface-data-1.3.0-alpha03-versionMetadata.json",
          "size": 966,
          "sha512": "e7217587f6d32cdaadce7b3c5208c98832b3fab706a9c8324ea85ec774e76f4e0feb0c04e10d3f636285649f55f582fd868a105dd5641471eebc794694a9d21c",
          "sha256": "86450630ab481cbb356a7a812e5204777a43aef33d68549eff3baf5dc719c1f1",
          "sha1": "bf5af23401c59ebe7b96cc04ac2e491a70a23180",
          "md5": "1299ccdbb5bab7579f8bc5c3d89d615b"
        }
      ]
    }
  ]
}