{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window",
    "version": "1.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.5.0-alpha01.aar",
          "url": "window-1.5.0-alpha01.aar",
          "size": 470946,
          "sha512": "a6b518138f9c8bc89bdeb7481893b4ba6fe6b9a245b748f2bb3cbe4353dea6c1230e4c8820e31ea0c85a9eeae1c94d62babab0e6fdbcadffd2da37679c2e6bb4",
          "sha256": "fb1fc30f3cd2be79d7a674222e39bf0772f3461e80074b3f170ba46c037e60bb",
          "sha1": "1253e19d4e5e9e4ac7d8fb1ffbc2a904f81c7eac",
          "md5": "009f39844deb2851f9d2ed68488c8899"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.window.extensions.core",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.5.0-alpha01.aar",
          "url": "window-1.5.0-alpha01.aar",
          "size": 470946,
          "sha512": "a6b518138f9c8bc89bdeb7481893b4ba6fe6b9a245b748f2bb3cbe4353dea6c1230e4c8820e31ea0c85a9eeae1c94d62babab0e6fdbcadffd2da37679c2e6bb4",
          "sha256": "fb1fc30f3cd2be79d7a674222e39bf0772f3461e80074b3f170ba46c037e60bb",
          "sha1": "1253e19d4e5e9e4ac7d8fb1ffbc2a904f81c7eac",
          "md5": "009f39844deb2851f9d2ed68488c8899"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.5.0-alpha01-versionMetadata.json",
          "url": "window-1.5.0-alpha01-versionMetadata.json",
          "size": 31835,
          "sha512": "f226d10785ed2e3edd47da5ea41b6938419eb4fda4c482bd73e71b50c4a4d736c002d9cad3922cd6b4dae63b7471d87dda039aeaa1a2e79eeea1d5e269e5e057",
          "sha256": "03755a5c74e350274a6fc4e76a53e53dbedb67452357cdef9b26cb426c27c854",
          "sha1": "eaca6979b61c6fd0d75378b3f4d05d45ec915ff6",
          "md5": "9b09d59bd9b9fc8cdf95d5f3c714e2f2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.5.0-alpha01-sources.jar",
          "url": "window-1.5.0-alpha01-sources.jar",
          "size": 191503,
          "sha512": "9f890b33f05cced2a4fad113963fb649e3aa8775ba12bc28a91d6dd902b1ce3f7d1e7d2cc2534171e8ef33429cbcc10d4d992c207d3741adb173bff574150528",
          "sha256": "757c18c14abda95c2ea79a555dbd425700da17a3e82fbd11e0af36a3332fe687",
          "sha1": "fe54b053c45b187775b4040d24d138486a19ec31",
          "md5": "e4bd4b5e38e528af4d758e0a8b47b30c"
        },
        {
          "name": "window-1.5.0-alpha01-samples-sources.jar",
          "url": "window-1.5.0-alpha01-samples-sources.jar",
          "size": 6846,
          "sha512": "80fd35de3e5712a009a76fbd1c794b31ef52245cbdb0f39cc8fe85cb4e5a60d4102e6256a173d0c9d7d630a18183a651627a79f49611cada062d2013a122558f",
          "sha256": "3977c10d311cbd24abb970b335b0279b31e4e07c756c63b65d57da4f9bf284f9",
          "sha1": "63e5a7c792bd1b9409f888cc4b00f10e9ae44ee7",
          "md5": "b30a888eee11232f1a85d6421243a316"
        }
      ]
    }
  ]
}