version: "1.0.0"
dependency_list {
}
release_checklist {
}
build_id: "androidx.tracing"
group_id: "androidx.tracing"
artifact_id: "tracing-perfetto-binary"
path: "/tracing/tracing-perfetto-binary"
sha: "a0ec9dc0763af4507de3604aed283a57843bb85f"
require_same_version_group_build: true
group_zip_path: "per-group-zips/gmaven-androidx-tracing-11472573.zip"
project_zip_path: "per-project-zips/androidx.tracing-tracing-perfetto-binary-all-11472573-1.0.0.zip"
kotlin_version: "1.9.22"
dependency_constraint_list {
  dependency {
    group_id: "androidx.tracing"
    artifact_id: "tracing-perfetto"
    version: "1.0.0"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.tracing"
    artifact_id: "tracing-perfetto-handshake"
    version: "1.0.0"
    is_tip_of_tree: true
  }
}
