{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tracing",
    "module": "tracing-perfetto-binary",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto-binary is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-handshake",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto-binary is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-binary-1.0.0.aar",
          "url": "tracing-perfetto-binary-1.0.0.aar",
          "size": 4340342,
          "sha512": "8a8467454e791de47bd263e407fe023bbafd7e872dc94fdace21f35e4fee323b0579e9c7f0cb54b6e543d2d74e329ff259d686d37d928b7aa6c7366efba558c0",
          "sha256": "aad14298cdfa50f561e72aa3be516bd675c4932dae1a3ccb2d44cb2a034d0ade",
          "sha1": "2f2976f9905e2d1b1dd1142567249b81e7ffdcca",
          "md5": "71647d641a05257216453f4cc7c69043"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto-binary is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-handshake",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto-binary is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-binary-1.0.0.aar",
          "url": "tracing-perfetto-binary-1.0.0.aar",
          "size": 4340342,
          "sha512": "8a8467454e791de47bd263e407fe023bbafd7e872dc94fdace21f35e4fee323b0579e9c7f0cb54b6e543d2d74e329ff259d686d37d928b7aa6c7366efba558c0",
          "sha256": "aad14298cdfa50f561e72aa3be516bd675c4932dae1a3ccb2d44cb2a034d0ade",
          "sha1": "2f2976f9905e2d1b1dd1142567249b81e7ffdcca",
          "md5": "71647d641a05257216453f4cc7c69043"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto-binary is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-handshake",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto-binary is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-binary-1.0.0-sources.jar",
          "url": "tracing-perfetto-binary-1.0.0-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto-binary is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-handshake",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto-binary is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-binary-1.0.0-versionMetadata.json",
          "url": "tracing-perfetto-binary-1.0.0-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}