{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-ktx",
    "version": "2.8.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.8.0-alpha02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.8.0-alpha02.aar",
          "url": "lifecycle-livedata-ktx-2.8.0-alpha02.aar",
          "size": 2155,
          "sha512": "bc8c7fdfc9dfe6e36ec23b6f0ba15586be28358c4c9b9fd3b89053e421e3454345fc432cae04f536f4be20b44cc4ea2b7a39fb1a585d9f2c0409350f59296795",
          "sha256": "012c3ae0db464206b0cddf730f5b4fc8b3f3b68708e477fbfca2b6baa19e9401",
          "sha1": "dc04b890c5b8035c4ab26ef58048a0379f6a7397",
          "md5": "1bc6fed81e38d67fc97977c194954ef2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.8.0-alpha02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.8.0-alpha02.aar",
          "url": "lifecycle-livedata-ktx-2.8.0-alpha02.aar",
          "size": 2155,
          "sha512": "bc8c7fdfc9dfe6e36ec23b6f0ba15586be28358c4c9b9fd3b89053e421e3454345fc432cae04f536f4be20b44cc4ea2b7a39fb1a585d9f2c0409350f59296795",
          "sha256": "012c3ae0db464206b0cddf730f5b4fc8b3f3b68708e477fbfca2b6baa19e9401",
          "sha1": "dc04b890c5b8035c4ab26ef58048a0379f6a7397",
          "md5": "1bc6fed81e38d67fc97977c194954ef2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.8.0-alpha02-sources.jar",
          "url": "lifecycle-livedata-ktx-2.8.0-alpha02-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.0-alpha02"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.8.0-alpha02-versionMetadata.json",
          "url": "lifecycle-livedata-ktx-2.8.0-alpha02-versionMetadata.json",
          "size": 2097,
          "sha512": "14230a2f97721bb605b5a54bb36576da7600dfb4f4351253d0f5de2564f47f4e6ab1d7e542f2314ba6fbf22fe9b3f7daf2517dd726b7c323b98102a69758ca45",
          "sha256": "26f750bdf35afe0013268ff5b20b9c84d1e0346497042bdf3c7995db663c4d97",
          "sha1": "cf4e4f082641bd9284e3e3f22bed1e44974551f3",
          "md5": "c921c372c7db86aec6d7c04e905974d0"
        }
      ]
    }
  ]
}