{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.tiles",
    "module": "tiles-proto",
    "version": "1.4.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles-proto is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles-proto is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles-proto is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles-proto is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles-proto is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles-proto is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-proto-1.4.0-alpha04.jar",
          "url": "tiles-proto-1.4.0-alpha04.jar",
          "size": 59771,
          "sha512": "ab88f7e4cc1774c4b1163f13b102662035e3f6780cefb3e25c7bc0f157703d191e268e08db99ad02bd13dcb055e9878b83aefd19adb30bbdbdbcb03c888a792c",
          "sha256": "6bf0dc7330f885724f6454a44e7356388109f036669982e0c8712e27398155e6",
          "sha1": "167f01680bb9815735d7b1e3806457e6eea8655f",
          "md5": "dec0754f0e99ee26f988bdddfa810b37"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles-proto is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles-proto is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles-proto is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles-proto is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles-proto is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles-proto is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-proto-1.4.0-alpha04.jar",
          "url": "tiles-proto-1.4.0-alpha04.jar",
          "size": 59771,
          "sha512": "ab88f7e4cc1774c4b1163f13b102662035e3f6780cefb3e25c7bc0f157703d191e268e08db99ad02bd13dcb055e9878b83aefd19adb30bbdbdbcb03c888a792c",
          "sha256": "6bf0dc7330f885724f6454a44e7356388109f036669982e0c8712e27398155e6",
          "sha1": "167f01680bb9815735d7b1e3806457e6eea8655f",
          "md5": "dec0754f0e99ee26f988bdddfa810b37"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles-proto is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles-proto is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles-proto is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles-proto is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles-proto is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles-proto is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-proto-1.4.0-alpha04-sources.jar",
          "url": "tiles-proto-1.4.0-alpha04-sources.jar",
          "size": 32813,
          "sha512": "58a31f0cf8a3ce5270c49047f5deea2c6fe6d805bf8f600d8e02f8993df7cbe7e3127b91a2feaa2fbb9e527ed15fc1635c8b4ffd26d366de170ddf6693d1d038",
          "sha256": "4bf85ec36c3c90fd9853aaab1578800292e18655a435d8005bb40e4920c069ae",
          "sha1": "e120a9fa1a538ba04b67add24b19f1ed557220a2",
          "md5": "5f5ca1e771081114f0b6f12f993d0dc7"
        }
      ]
    }
  ]
}