{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation-graphics/1.7.0-beta02/animation-graphics-1.7.0-beta02.module",
    "group": "androidx.compose.animation",
    "module": "animation-graphics",
    "version": "1.7.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-graphics-release.aar",
          "url": "animation-graphics-android-1.7.0-beta02.aar",
          "size": 105591,
          "sha512": "3a21564c64fa2d321a24f7d18f218ef4acea31e28495f83c6f648906d4dbf3b642b76e378ff80a5f43e28dcb76d39c65b343cbb682dfe394770739ebb435a91e",
          "sha256": "1f060726ec62c629d583425077d5a00103c7b2cdb94536f733c0a81e4bbfd4fb",
          "sha1": "1d9da5bfa3caef97ce5d5f8f164a088b6521a993",
          "md5": "4f7b800af4b226f38d38dc3b6046f534"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-graphics-release.aar",
          "url": "animation-graphics-android-1.7.0-beta02.aar",
          "size": 105591,
          "sha512": "3a21564c64fa2d321a24f7d18f218ef4acea31e28495f83c6f648906d4dbf3b642b76e378ff80a5f43e28dcb76d39c65b343cbb682dfe394770739ebb435a91e",
          "sha256": "1f060726ec62c629d583425077d5a00103c7b2cdb94536f733c0a81e4bbfd4fb",
          "sha1": "1d9da5bfa3caef97ce5d5f8f164a088b6521a993",
          "md5": "4f7b800af4b226f38d38dc3b6046f534"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-graphics-1.7.0-beta02-samples-sources.jar",
          "url": "animation-graphics-android-1.7.0-beta02-samples-sources.jar",
          "size": 1904,
          "sha512": "c18fad718bdf26fb40230ba195b9cd5efdea14d7f6ed255a25872a79bfce4e3ad285d4e94cd93d1f980de8e7a0d6d3a56dc270933a228adff36ab3ab37e615dd",
          "sha256": "8c3fe29b648846f8e535d42e0c84f87e6328479569fc26125385ff82eb487039",
          "sha1": "eaaf8cde7045c83b9c0f1ebb4726f70e24b15c4b",
          "md5": "982acda41e185e887d60862f0bb2273a"
        },
        {
          "name": "animation-graphics-android-1.7.0-beta02-sources.jar",
          "url": "animation-graphics-android-1.7.0-beta02-sources.jar",
          "size": 23176,
          "sha512": "1bb275981c7c3caaf09d891908d1f1edcd4f2fda3bb4f6ac1a8b37057ef95f59db6e59daa9ef1fd77e3d95043cb69de08d1b20cbec5f2533d40f8ceab9ccd5d9",
          "sha256": "fa13bd2d1f469a1d163726b4852f9298130d986813a5e0b07bc1582200a6f148",
          "sha1": "e9149566ea46a97fe24729a432cc2ae2260f9e4b",
          "md5": "113b57fe39dd71dd2a3983ea8ccf1e0a"
        }
      ]
    }
  ]
}