{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material-core",
    "version": "1.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.5.0-alpha01-sources.jar",
          "url": "compose-material-core-1.5.0-alpha01-sources.jar",
          "size": 31873,
          "sha512": "85f2408843db2cc230057b740e4ff8b84cb89c4f0e9eb393bebdb951bae4de77f2ab6ba27acf807e5e47d08f1f73214cf6282a9c84830e4fcabdf0ea56196782",
          "sha256": "be32aa21a92b4ec42ac45fbefe9355467b36dbf1b96e370bc56b8b1c9e0636a2",
          "sha1": "76d6ffa1bd71f0ca1028938c56ceb1ccd22f6458",
          "md5": "d1b0d50ba6aaa570aa3db6245dff147e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.5.0-alpha01.aar",
          "url": "compose-material-core-1.5.0-alpha01.aar",
          "size": 169423,
          "sha512": "0688c57463c727a82cae23bafc5764e66e918f17a188a2e5e509d634ef7fd4ca4306a32dfbf87a50bcf42e2ecdc2c3f8acdfb10068d9062892d53e353a8a0ca2",
          "sha256": "fa6aa5fee5df505bde799aa670d0446c3d3d7db7679c40fecefe6eac4b89f9b7",
          "sha1": "6ecf859e56daa7f64f1e8731ba39acd97883c37c",
          "md5": "5ddc5a5e9fcdb757e0f6fedc0471bbd1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.5.0-alpha01.aar",
          "url": "compose-material-core-1.5.0-alpha01.aar",
          "size": 169423,
          "sha512": "0688c57463c727a82cae23bafc5764e66e918f17a188a2e5e509d634ef7fd4ca4306a32dfbf87a50bcf42e2ecdc2c3f8acdfb10068d9062892d53e353a8a0ca2",
          "sha256": "fa6aa5fee5df505bde799aa670d0446c3d3d7db7679c40fecefe6eac4b89f9b7",
          "sha1": "6ecf859e56daa7f64f1e8731ba39acd97883c37c",
          "md5": "5ddc5a5e9fcdb757e0f6fedc0471bbd1"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.5.0-alpha01-versionMetadata.json",
          "url": "compose-material-core-1.5.0-alpha01-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}