{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.protolayout",
    "module": "protolayout",
    "version": "1.2.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-1.2.0-alpha04-sources.jar",
          "url": "protolayout-1.2.0-alpha04-sources.jar",
          "size": 76901,
          "sha512": "aa496f3829d530fd8b529136a60f01d2be2b2d0772de25af4a73a17e71a1ea17ec58b85d8329c964a0c899d01c002a7f0c3f6668d98810b92e9134cea285b76a",
          "sha256": "a9382e7fb41dfcf9aaf4a2ce33753d805d28a0556b3f3a19dab56d653db82070",
          "sha1": "1ab66631f0d67df505bf64ac9930c4aea78c96d6",
          "md5": "8c373b48f2ec4d2b48e749a35155be6c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-1.2.0-alpha04.aar",
          "url": "protolayout-1.2.0-alpha04.aar",
          "size": 337370,
          "sha512": "13a25525446beab1ff62f4e6a59913e93e27b39b5c4be025c9e19a55d90077426f14f7127fc850f509f15f725570a70b05ee3eb64c4a289c419ed0faca595048",
          "sha256": "d090f67bcca46b62eb6164d6b107b0bbe2575c1e122852b1ef5c2544f6d6b536",
          "sha1": "6e296dc2983553d6b03fbf74ddecc0340a83955c",
          "md5": "7596fd574eb3b0bac5b53afac1c9f8d6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-1.2.0-alpha04.aar",
          "url": "protolayout-1.2.0-alpha04.aar",
          "size": 337370,
          "sha512": "13a25525446beab1ff62f4e6a59913e93e27b39b5c4be025c9e19a55d90077426f14f7127fc850f509f15f725570a70b05ee3eb64c4a289c419ed0faca595048",
          "sha256": "d090f67bcca46b62eb6164d6b107b0bbe2575c1e122852b1ef5c2544f6d6b536",
          "sha1": "6e296dc2983553d6b03fbf74ddecc0340a83955c",
          "md5": "7596fd574eb3b0bac5b53afac1c9f8d6"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-1.2.0-alpha04-versionMetadata.json",
          "url": "protolayout-1.2.0-alpha04-versionMetadata.json",
          "size": 74927,
          "sha512": "4d235936e7bcbe8634bc4988cf4caf2bc0933da97d2f59fa6fbffea974dc89581bac1fab305af9c661c75017cd83496fba7a03b6aada7d366a52a6e7b7aa4dde",
          "sha256": "e984f6a4ee87587104eed0f4671cd0db7547c202014b84a7f29c6364d40ba977",
          "sha1": "dac192f2bbdc9ca21c672af44b36640bade1db8d",
          "md5": "579a0f71a5638781e718c7afbe5f6537"
        }
      ]
    }
  ]
}