{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-test-manifest",
    "version": "1.7.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-1.7.0-alpha03.aar",
          "url": "ui-test-manifest-1.7.0-alpha03.aar",
          "size": 9390,
          "sha512": "7b227dc04d6faa33e783dbf604ae5ba74fdeff713945b0a1dadb19ac14ab6170aad9daf9ba75f274d8280f5892b895f3f308fca4a5b19a99510ffa7a95b061a1",
          "sha256": "7ed8d3c73fa27280fe9427ec22ce4c9fe3c5b3a477655a67dc4d05dded5f355b",
          "sha1": "b21400f6dd8f0c33d2775d210b0606c42b79dbbb",
          "md5": "1e52141cb9b78e3955f8b5f7335cba70"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-1.7.0-alpha03.aar",
          "url": "ui-test-manifest-1.7.0-alpha03.aar",
          "size": 9390,
          "sha512": "7b227dc04d6faa33e783dbf604ae5ba74fdeff713945b0a1dadb19ac14ab6170aad9daf9ba75f274d8280f5892b895f3f308fca4a5b19a99510ffa7a95b061a1",
          "sha256": "7ed8d3c73fa27280fe9427ec22ce4c9fe3c5b3a477655a67dc4d05dded5f355b",
          "sha1": "b21400f6dd8f0c33d2775d210b0606c42b79dbbb",
          "md5": "1e52141cb9b78e3955f8b5f7335cba70"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-1.7.0-alpha03-sources.jar",
          "url": "ui-test-manifest-1.7.0-alpha03-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-1.7.0-alpha03-versionMetadata.json",
          "url": "ui-test-manifest-1.7.0-alpha03-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}