{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-foundation",
    "version": "1.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-foundation-1.5.0-alpha01-sources.jar",
          "url": "compose-foundation-1.5.0-alpha01-sources.jar",
          "size": 113686,
          "sha512": "66d382c832b530a08a82e6971cfb507b271de05cff333772a8eaba44eef8c32dd54fedbf3fc2c542e5123a8c3af3a6152c5ef8ff2cf1a7feb41e83a979cfdaaf",
          "sha256": "b1f98b970717617de2914ade14539096460294c3c82f459f71e62a5976623ac4",
          "sha1": "0c8ae8dd7f69c38eb469d97dc358c822bc89de12",
          "md5": "94544682da6407fe2189c435ae12bc39"
        },
        {
          "name": "compose-foundation-1.5.0-alpha01-samples-sources.jar",
          "url": "compose-foundation-1.5.0-alpha01-samples-sources.jar",
          "size": 12945,
          "sha512": "00b4606a93ca8a3b5dce1b5f40e3bda615417010f6b25674f7dd99a7318e77ef831c9eefc838a26244495b1465e71b4facde91e320d3d71d37a2d406526fb475",
          "sha256": "7947fc8d951501d8dd2246add8761ed82b9fcf27f507b34f97b8e7f194449557",
          "sha1": "9eb68aa5a8452419920cae5bc737b8d15c09c3e2",
          "md5": "57574a12d5f05ecc288e3c8d3806d142"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-foundation-1.5.0-alpha01.aar",
          "url": "compose-foundation-1.5.0-alpha01.aar",
          "size": 637252,
          "sha512": "deedac8209040614da0d91483b6987d6d7a2cf20216144295e8a12f80790c7bb7dc3a9180b9b8b00000206a9204852ed01b35a956bc91e3863a6f9f79147e904",
          "sha256": "70fcf690fd067eb5f8e2f18eab0eae2af770b9f6647e193a75abae7d3bb71f1b",
          "sha1": "a4a68b23f9138a4cfa215ab3520370fdcf6348fa",
          "md5": "dce134ff488b3ab76863ac3184d95cb6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-foundation-1.5.0-alpha01.aar",
          "url": "compose-foundation-1.5.0-alpha01.aar",
          "size": 637252,
          "sha512": "deedac8209040614da0d91483b6987d6d7a2cf20216144295e8a12f80790c7bb7dc3a9180b9b8b00000206a9204852ed01b35a956bc91e3863a6f9f79147e904",
          "sha256": "70fcf690fd067eb5f8e2f18eab0eae2af770b9f6647e193a75abae7d3bb71f1b",
          "sha1": "a4a68b23f9138a4cfa215ab3520370fdcf6348fa",
          "md5": "dce134ff488b3ab76863ac3184d95cb6"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-foundation-1.5.0-alpha01-versionMetadata.json",
          "url": "compose-foundation-1.5.0-alpha01-versionMetadata.json",
          "size": 28256,
          "sha512": "ddc7948b181814c340f8202d0855a8dd616cc9081fd3b902447b2ff037b69327e24731e1af22b75e3013eef439c3b8d9ada6e8ff704cd2e699a2ca21a6346b7f",
          "sha256": "514758db9f2e4eec6bcab74f73b67c465b8cab363ed426ce4ede6c5914aac984",
          "sha1": "19bbc3a3184d9fa75598bad44be77c5db43d9fbb",
          "md5": "95b1ecb8674abf72ba5c30798b127864"
        }
      ]
    }
  ]
}