{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sqlite/2.5.0-alpha01/sqlite-2.5.0-alpha01.module",
    "group": "androidx.sqlite",
    "module": "sqlite",
    "version": "2.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.0-alpha01"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0-alpha01"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0-alpha01"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-release.aar",
          "url": "sqlite-android-2.5.0-alpha01.aar",
          "size": 30239,
          "sha512": "efd58e99f42b8a554d90a32c3a8bee41c5f688099459299edc84f3edb05ead2c3e947db07c6f17bbd71c11daa79e4479c5537350610679afd7d01aac040b1332",
          "sha256": "15d42b192e893ca33db0652b8b624408991669de1a2b3a4bbd702d47e4d5686c",
          "sha1": "9382a0c375a929695a0c3efe5b66c4c2ddaea01b",
          "md5": "7306d89b9256f72e6e7ac4c990dae014"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.0-alpha01"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0-alpha01"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0-alpha01"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-release.aar",
          "url": "sqlite-android-2.5.0-alpha01.aar",
          "size": 30239,
          "sha512": "efd58e99f42b8a554d90a32c3a8bee41c5f688099459299edc84f3edb05ead2c3e947db07c6f17bbd71c11daa79e4479c5537350610679afd7d01aac040b1332",
          "sha256": "15d42b192e893ca33db0652b8b624408991669de1a2b3a4bbd702d47e4d5686c",
          "sha1": "9382a0c375a929695a0c3efe5b66c4c2ddaea01b",
          "md5": "7306d89b9256f72e6e7ac4c990dae014"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.0-alpha01"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0-alpha01"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0-alpha01"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-android-2.5.0-alpha01-sources.jar",
          "url": "sqlite-android-2.5.0-alpha01-sources.jar",
          "size": 25735,
          "sha512": "9f1c42ec9e5bbc6700a48ecf843be7bf64eb6adc0383f9b863f0ea60bb0b4faf137f574dc66105eaac333e870d8e4f707e9a9bf579113f17e47fe6541f6b127a",
          "sha256": "295c39b23cbec1c04ebae6745f2903a6bafe7bd221978a73897fd6233c098dee",
          "sha1": "7d062e6fdcbefdbf12ab15fd7d0a62cd4e3f97ab",
          "md5": "7610713abeaecacd2411fcc7ecb3d5c9"
        }
      ]
    }
  ]
}