{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-ktx",
    "version": "2.7.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha01"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-ktx-2.7.0-alpha01.aar",
          "url": "room-ktx-2.7.0-alpha01.aar",
          "size": 2496,
          "sha512": "f01ec2a300fa5a4e29cc361ec9091e99124d632495915a8d9b353d40dc596c9bb590d375796dd7124f92143e959c1c0691ff85106dc0f2268ce93acf3a2b46c9",
          "sha256": "4d805436950335d6f3f10b9bc630e7176ddb376b1756ca6d1a3ac8d8221facf2",
          "sha1": "6e4da0db0b1bc73964c029358e211a7adb14c464",
          "md5": "249d89bbd683fa3d745c0ab396d802f5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha01"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-ktx-2.7.0-alpha01.aar",
          "url": "room-ktx-2.7.0-alpha01.aar",
          "size": 2496,
          "sha512": "f01ec2a300fa5a4e29cc361ec9091e99124d632495915a8d9b353d40dc596c9bb590d375796dd7124f92143e959c1c0691ff85106dc0f2268ce93acf3a2b46c9",
          "sha256": "4d805436950335d6f3f10b9bc630e7176ddb376b1756ca6d1a3ac8d8221facf2",
          "sha1": "6e4da0db0b1bc73964c029358e211a7adb14c464",
          "md5": "249d89bbd683fa3d745c0ab396d802f5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-ktx-2.7.0-alpha01-sources.jar",
          "url": "room-ktx-2.7.0-alpha01-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-ktx-2.7.0-alpha01-versionMetadata.json",
          "url": "room-ktx-2.7.0-alpha01-versionMetadata.json",
          "size": 814,
          "sha512": "1c94a33cd9b1fbf050412e6cb6ea9da9a8502b88a79f92a5c3e34a48abab58b8b2cb7629609339e4f6507d21f82adcc68e78db6069c605f931f9d289b2e38405",
          "sha256": "354f00f9f639395f1b3b7b67f1b347930877a53d5478ee774a0fe2d0bff0e4a5",
          "sha1": "f30bf3b8e6bbd1c7e2f14f55088451a93592b71b",
          "md5": "6c27c68f0c9e5a610e3f76c99bb34c56"
        }
      ]
    }
  ]
}