{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.ads",
    "module": "ads-adservices-java",
    "version": "1.1.0-beta07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices",
          "version": {
            "requires": "1.1.0-beta07"
          },
          "reason": "ads-adservices-java is in atomic group androidx.privacysandbox.ads"
        }
      ],
      "files": [
        {
          "name": "ads-adservices-java-1.1.0-beta07-sources.jar",
          "url": "ads-adservices-java-1.1.0-beta07-sources.jar",
          "size": 15900,
          "sha512": "adb83d2269b1d761394279f4290f261cb369ee5fe4f3be3e24f246fb329232317d04c1634ff098624f55c3d0c062c2cd3c8ca6212da344b8205797b1b2804c00",
          "sha256": "137bc0fcab8ccd93ef8f46d9e88839c3555ec0306f036b43245db2e70fb61d79",
          "sha1": "9dccfa45423f5b97204a0dd42501f05eb1a2f60d",
          "md5": "7a43747563684f4ad6135f9721c6e7bb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices",
          "version": {
            "requires": "1.1.0-beta07"
          },
          "reason": "ads-adservices-java is in atomic group androidx.privacysandbox.ads"
        }
      ],
      "files": [
        {
          "name": "ads-adservices-java-1.1.0-beta07.aar",
          "url": "ads-adservices-java-1.1.0-beta07.aar",
          "size": 63021,
          "sha512": "4c2635e70794c381d0dfd01e835dc9c9527c545bc4d223b17b552d05af1d1bd8689a4d2a7fb110b87db590656f9c852587f310a4f59411c3acf526bd4b8445d1",
          "sha256": "e92094cc30f8b1e45978f13d847b56639069238dfdb58956b543e19baf7d8c15",
          "sha1": "cf8ec329f0c38a368bf5100a0632b96bf6367e56",
          "md5": "b9279eb06bb71d23c2e85d6c3ca71221"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices",
          "version": {
            "requires": "1.1.0-beta07"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices",
          "version": {
            "requires": "1.1.0-beta07"
          },
          "reason": "ads-adservices-java is in atomic group androidx.privacysandbox.ads"
        }
      ],
      "files": [
        {
          "name": "ads-adservices-java-1.1.0-beta07.aar",
          "url": "ads-adservices-java-1.1.0-beta07.aar",
          "size": 63021,
          "sha512": "4c2635e70794c381d0dfd01e835dc9c9527c545bc4d223b17b552d05af1d1bd8689a4d2a7fb110b87db590656f9c852587f310a4f59411c3acf526bd4b8445d1",
          "sha256": "e92094cc30f8b1e45978f13d847b56639069238dfdb58956b543e19baf7d8c15",
          "sha1": "cf8ec329f0c38a368bf5100a0632b96bf6367e56",
          "md5": "b9279eb06bb71d23c2e85d6c3ca71221"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices",
          "version": {
            "requires": "1.1.0-beta07"
          },
          "reason": "ads-adservices-java is in atomic group androidx.privacysandbox.ads"
        }
      ],
      "files": [
        {
          "name": "ads-adservices-java-1.1.0-beta07-versionMetadata.json",
          "url": "ads-adservices-java-1.1.0-beta07-versionMetadata.json",
          "size": 4955,
          "sha512": "6dcd869fd8def144c182c0b6e46ab84b7d55c210e03a5f558001ffb0f827f9028a3d9272f9ea1b303788c9e92abbc4089d61e03935200519860cfbd9936a41be",
          "sha256": "0b2c2052603cb337ba0f871d264b2b84886b332916af77173d4bc12c488394e1",
          "sha1": "1b683df4da00dfdb029bd3a91d2393a7b046df1a",
          "md5": "02a082e731cf4197bb8845c2dac71856"
        }
      ]
    }
  ]
}