version: "1.0.0-alpha07"
dependency_list {
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-core"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.privacysandbox.tools"
group_id: "androidx.privacysandbox.tools"
artifact_id: "tools-apigenerator"
path: "/privacysandbox/tools/tools-apigenerator"
sha: "a0ec9dc0763af4507de3604aed283a57843bb85f"
require_same_version_group_build: true
group_zip_path: "per-group-zips/gmaven-androidx-privacysandbox-tools-11472573.zip"
project_zip_path: "per-project-zips/androidx.privacysandbox.tools-tools-apigenerator-all-11472573-1.0.0-alpha07.zip"
kotlin_version: "1.9.22"
dependency_constraint_list {
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-apicompiler"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-apipackager"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-core"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
}
