{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.javascriptengine",
    "module": "javascriptengine",
    "version": "1.0.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "javascriptengine-1.0.0-alpha06.aar",
          "url": "javascriptengine-1.0.0-alpha06.aar",
          "size": 54235,
          "sha512": "aa8c7e8089c1fffb1be13356914ca508e617ab8b8fad5c8a36a71291e90c990637814a721f655c455db1b0366cb9818fe0951262adbec12f825f0ebc46562f87",
          "sha256": "bee42b2461990e40df249761ab0c331cc210786287f17dbce889eba3577064cf",
          "sha1": "75e4078359abec69c20f27661260ce14655718aa",
          "md5": "b9e4b2cea70ce357f12ff3ec97feb058"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-android"
          }
        }
      ],
      "files": [
        {
          "name": "javascriptengine-1.0.0-alpha06.aar",
          "url": "javascriptengine-1.0.0-alpha06.aar",
          "size": 54235,
          "sha512": "aa8c7e8089c1fffb1be13356914ca508e617ab8b8fad5c8a36a71291e90c990637814a721f655c455db1b0366cb9818fe0951262adbec12f825f0ebc46562f87",
          "sha256": "bee42b2461990e40df249761ab0c331cc210786287f17dbce889eba3577064cf",
          "sha1": "75e4078359abec69c20f27661260ce14655718aa",
          "md5": "b9e4b2cea70ce357f12ff3ec97feb058"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "javascriptengine-1.0.0-alpha06-sources.jar",
          "url": "javascriptengine-1.0.0-alpha06-sources.jar",
          "size": 29535,
          "sha512": "e5a4c81c5c469ad803e82c9111c68fc37abc9bbde651c712b1f04e65665b0909fca06bffe10f6b92f92fa280bb7221a42a370d1934f1e68da29d4b15ff30f2e0",
          "sha256": "8081755538d4df4020794ed29f0f6764218ece3b5a63d400599597f7a8f4db5f",
          "sha1": "6212124c09b697d28ff54b4a28112f985388a609",
          "md5": "56b3acc60646c673056f757b17829db1"
        }
      ]
    }
  ]
}