{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-foundation",
    "version": "1.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-foundation-1.4.0-alpha03.aar",
          "url": "compose-foundation-1.4.0-alpha03.aar",
          "size": 523134,
          "sha512": "9c612fa1a90e54d966e8b59e68467be1a268ba086086ddd3e3abbaa728d824c512742fbd71bac1279f3961bae247d3757f317194580d7f7288a40d7330625af1",
          "sha256": "783e4b35eaf03db300dcc09a9b64e8f627c5fed7e741e2f98f9298a8c609ffee",
          "sha1": "567ca7d2683f4a17fc4a0ef0e10c34dc8fdade0e",
          "md5": "526ac9b526e31eb42d43a4b8b4e627fb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-foundation-1.4.0-alpha03.aar",
          "url": "compose-foundation-1.4.0-alpha03.aar",
          "size": 523134,
          "sha512": "9c612fa1a90e54d966e8b59e68467be1a268ba086086ddd3e3abbaa728d824c512742fbd71bac1279f3961bae247d3757f317194580d7f7288a40d7330625af1",
          "sha256": "783e4b35eaf03db300dcc09a9b64e8f627c5fed7e741e2f98f9298a8c609ffee",
          "sha1": "567ca7d2683f4a17fc4a0ef0e10c34dc8fdade0e",
          "md5": "526ac9b526e31eb42d43a4b8b4e627fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-foundation-1.4.0-alpha03-sources.jar",
          "url": "compose-foundation-1.4.0-alpha03-sources.jar",
          "size": 95647,
          "sha512": "8befbe516ecbb8fe47379ea9e5e2a1a748b318a4a0010a1d0fbe6f64dd61c09bf7e24050a17f3dc619f7f026d76ee9c23911258e540a5e2868b9345443abf8f4",
          "sha256": "88ae6cb64ca504ebeabc1bec816be0f3bc429706b0d90d924445eceee966d816",
          "sha1": "ae9adbfb9170914ba816e0a404ba9b74b727397d",
          "md5": "413a73dcaeef735cd4ba44aa5648eaaf"
        },
        {
          "name": "compose-foundation-1.4.0-alpha03-samples-sources.jar",
          "url": "compose-foundation-1.4.0-alpha03-samples-sources.jar",
          "size": 11586,
          "sha512": "10686fd763f93fe3a330cc038c49b25255064bed906ac5c67ecfbc42c98358135cc8a8e40397a6644a1fc9289736d840a020859dd0d45e2477651c859805a21b",
          "sha256": "e83162246153c51ec8ad9187e4f9a980243263ad18f2f309e39167f755edf0a3",
          "sha1": "bcb308881e97bb9882f88f40680ab81aeffe5e24",
          "md5": "8f3a32d85ffc793cd30df16051576092"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-foundation-1.4.0-alpha03-versionMetadata.json",
          "url": "compose-foundation-1.4.0-alpha03-versionMetadata.json",
          "size": 26382,
          "sha512": "10082ef121ab602350eff10909dc36067095723a9e99f19744ce24730d7f87a1ea1e659a36b5b51578bad26ca8ee5c0772aec0af293b623ba09be13b33b96bcf",
          "sha256": "1e136cba74cd80c2cde2ed0f5369a5e18e55fecf965e8dfcfa3bdff7d062966b",
          "sha1": "4fdc9f9f47af7eebfa290772dff423552201cdb9",
          "md5": "a3a4fd554955f33df864b18571a5dffc"
        }
      ]
    }
  ]
}