{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.annotation",
    "module": "annotation-experimental",
    "version": "1.4.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotation-experimental-1.4.0-rc01-sources.jar",
          "url": "annotation-experimental-1.4.0-rc01-sources.jar",
          "size": 5380,
          "sha512": "de91407b5044ad565b732692afac6d1d0dc5ae4ed0e37a81b804deec14d46574e5240fbe5c5da6bf7d2863bfd14f1b7e851f954bea97c7e69d1eb94dcca76c11",
          "sha256": "318f2d29e7c3037c601cf1ba19d60b8093e6db575815150f75b31282e4c05062",
          "sha1": "6b04796890cdf70edd292d53790253401d4b36bd",
          "md5": "0ca7d7665a5b2d0f5ad8b27872a85d43"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-experimental-1.4.0-rc01.aar",
          "url": "annotation-experimental-1.4.0-rc01.aar",
          "size": 40346,
          "sha512": "8910d96af17e12827ff6f4d5ee23ad4776d39441526caf47338e96205fb602245211eaa7643fb904a6991603fb127faf4178fdc81c56f7a24a175474c0b2c7b8",
          "sha256": "4a2d3a5bab8e76883a21f136b7ef3baedc533b24e16c6532dc3021c164698e2d",
          "sha1": "9e8a33a2dfd10eac574f05ac7a7423e2585d1b74",
          "md5": "65f84d3afa0c2e7936ba0dd92704179a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-experimental-1.4.0-rc01.aar",
          "url": "annotation-experimental-1.4.0-rc01.aar",
          "size": 40346,
          "sha512": "8910d96af17e12827ff6f4d5ee23ad4776d39441526caf47338e96205fb602245211eaa7643fb904a6991603fb127faf4178fdc81c56f7a24a175474c0b2c7b8",
          "sha256": "4a2d3a5bab8e76883a21f136b7ef3baedc533b24e16c6532dc3021c164698e2d",
          "sha1": "9e8a33a2dfd10eac574f05ac7a7423e2585d1b74",
          "md5": "65f84d3afa0c2e7936ba0dd92704179a"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "annotation-experimental-1.4.0-rc01-versionMetadata.json",
          "url": "annotation-experimental-1.4.0-rc01-versionMetadata.json",
          "size": 1287,
          "sha512": "34e5b2bb9e8e57bb48de87c35da3e20276c85453804a6ba5c073b3a3ec553e1e6b9cc0e783da02278dcc445143a5eac5bc1851e0f1ee0321d85e18c841ce45b5",
          "sha256": "5c3e7593bdbd619e45f857f18051156b0163c7d26a4886f929a706668d27d5e8",
          "sha1": "49c73908cb59481260427de1bed1de97e1c94dd9",
          "md5": "6234d9bf6ddf64308dc62ed8acf51ea0"
        }
      ]
    }
  ]
}