version: "1.4.0-rc01"
dependency_list {
}
release_checklist {
}
build_id: "androidx.annotation"
group_id: "androidx.annotation"
artifact_id: "annotation-experimental"
path: "/annotation/annotation-experimental"
sha: "8e24ec7cf4ee1c5afe2b4a3a108f926420140662"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.annotation-annotation-experimental-all-11954666-1.4.0-rc01.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
