version: "1.1.0-beta04"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.2.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.concurrent"
    artifact_id: "concurrent-futures"
    version: "1.1.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core-ktx"
    version: "1.8.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.privacysandbox.ads"
    artifact_id: "ads-adservices"
    version: "1.1.0-beta04"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.privacysandbox.ads"
group_id: "androidx.privacysandbox.ads"
artifact_id: "ads-adservices-java"
path: "/privacysandbox/ads/ads-adservices-java"
sha: "a0ec9dc0763af4507de3604aed283a57843bb85f"
require_same_version_group_build: true
group_zip_path: "per-group-zips/gmaven-androidx-privacysandbox-ads-11472573.zip"
project_zip_path: "per-project-zips/androidx.privacysandbox.ads-ads-adservices-java-all-11472573-1.1.0-beta04.zip"
kotlin_version: "1.9.22"
dependency_constraint_list {
  dependency {
    group_id: "androidx.privacysandbox.ads"
    artifact_id: "ads-adservices"
    version: "1.1.0-beta04"
    is_tip_of_tree: true
  }
}
