version: "1.7.0-beta02"
dependency_list {
  dependency {
    group_id: "androidx.activity"
    artifact_id: "activity"
    version: "1.2.1"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.compose.ui"
group_id: "androidx.compose.ui"
artifact_id: "ui-test-manifest"
path: "/compose/ui/ui-test-manifest"
sha: "3264c1f21ddfe2acf96a1d034f78367662cf9f65"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.compose.ui-ui-test-manifest-all-11879057-1.7.0-beta02.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui"
    version: "1.7.0-beta02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-geometry"
    version: "1.7.0-beta02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-graphics"
    version: "1.7.0-beta02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-test"
    version: "1.7.0-beta02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-test-junit4"
    version: "1.7.0-beta02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-text"
    version: "1.7.0-beta02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-text-google-fonts"
    version: "1.7.0-beta02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-tooling"
    version: "1.7.0-beta02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-tooling-data"
    version: "1.7.0-beta02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-tooling-preview"
    version: "1.7.0-beta02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-unit"
    version: "1.7.0-beta02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-util"
    version: "1.7.0-beta02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-viewbinding"
    version: "1.7.0-beta02"
    is_tip_of_tree: true
  }
}
should_publish_docs: false
is_kmp: false
