{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-test-manifest",
    "version": "1.7.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-1.7.0-beta02-sources.jar",
          "url": "ui-test-manifest-1.7.0-beta02-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-1.7.0-beta02.aar",
          "url": "ui-test-manifest-1.7.0-beta02.aar",
          "size": 8629,
          "sha512": "cc766a0262beb8231976efdf92de63fd73e53c159c8d1f6765b11be73227acdc6a47eb98cb8bc2320a0bcefc8d21487efc31c7a894bdc944f9c2d3597d8052b5",
          "sha256": "df6effc0f8b6fc84bde3fe9bf890e13d179b21fcff7ccae7709f4aedba45b621",
          "sha1": "2ef4a05bff33239589164c07aab693bbbd1ce4d3",
          "md5": "e86df8c7242d28f7cace8c931c49c283"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-1.7.0-beta02.aar",
          "url": "ui-test-manifest-1.7.0-beta02.aar",
          "size": 8629,
          "sha512": "cc766a0262beb8231976efdf92de63fd73e53c159c8d1f6765b11be73227acdc6a47eb98cb8bc2320a0bcefc8d21487efc31c7a894bdc944f9c2d3597d8052b5",
          "sha256": "df6effc0f8b6fc84bde3fe9bf890e13d179b21fcff7ccae7709f4aedba45b621",
          "sha1": "2ef4a05bff33239589164c07aab693bbbd1ce4d3",
          "md5": "e86df8c7242d28f7cace8c931c49c283"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-1.7.0-beta02-versionMetadata.json",
          "url": "ui-test-manifest-1.7.0-beta02-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}