{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-video",
    "version": "1.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-video-1.4.0-beta01-sources.jar",
          "url": "camera-video-1.4.0-beta01-sources.jar",
          "size": 281946,
          "sha512": "8c55dd3435beaa6adb6d6412163ba93b8b5c48d97b9901ce29497c49201d4677702f007362f1267b9653b90e6e024694d94ebda4855e1edbf1667f0f5b34cc4c",
          "sha256": "a1d47cb2fda8fb9cb36b9fc9931144b4b5644a576b7e1b9017773ae7c8e2ec1c",
          "sha1": "6d98ed4530852f676f7a0e716b559302cc02577f",
          "md5": "ec1f8ed7cb4c595b3f4a7549261d1edf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-video-1.4.0-beta01.aar",
          "url": "camera-video-1.4.0-beta01.aar",
          "size": 380022,
          "sha512": "f346de74d163e735be2ad6e7c726de103bb861b6261d7fd38e3feeaefc6593d85ab741a5ea978260fbe9efdc2cb262d9ce30c54aa63ef84f9e295b1cb2b46516",
          "sha256": "0a4fdfaf92b61fb462d4d415eaca8fb0e701c9bfa848fa3bfafb2432f90c44a0",
          "sha1": "64c357bca45fcef9a5f2be37944ca5001c28c382",
          "md5": "c14891d5d890355a52463b3bb9aa712a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-video-1.4.0-beta01.aar",
          "url": "camera-video-1.4.0-beta01.aar",
          "size": 380022,
          "sha512": "f346de74d163e735be2ad6e7c726de103bb861b6261d7fd38e3feeaefc6593d85ab741a5ea978260fbe9efdc2cb262d9ce30c54aa63ef84f9e295b1cb2b46516",
          "sha256": "0a4fdfaf92b61fb462d4d415eaca8fb0e701c9bfa848fa3bfafb2432f90c44a0",
          "sha1": "64c357bca45fcef9a5f2be37944ca5001c28c382",
          "md5": "c14891d5d890355a52463b3bb9aa712a"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-video-1.4.0-beta01-versionMetadata.json",
          "url": "camera-video-1.4.0-beta01-versionMetadata.json",
          "size": 10655,
          "sha512": "2520212f53b458a3d1ba756bebebfc3f5477d4c27156858a30e826b86518caad6d9f32413a88f4fc40fbfe816cc51c3fbcdf6349e9887e3bb036ca6c9ba9b6e9",
          "sha256": "cbac5ea6684bcbf6ce7b85533ce2b7c91d597e5434f88ac331fa6e1716a5f377",
          "sha1": "5ccb3641b0f09922484ad1894e150469ac68a002",
          "md5": "6d62f0e75e717b9e19a029668736e889"
        }
      ]
    }
  ]
}