{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.ads",
    "module": "ads-adservices",
    "version": "1.1.0-beta07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices-java",
          "version": {
            "requires": "1.1.0-beta07"
          },
          "reason": "ads-adservices is in atomic group androidx.privacysandbox.ads"
        }
      ],
      "files": [
        {
          "name": "ads-adservices-1.1.0-beta07-sources.jar",
          "url": "ads-adservices-1.1.0-beta07-sources.jar",
          "size": 94297,
          "sha512": "3545ec2510e4632cb719a1fa114a8b86dc4d2c34ca7aa8e001bc619b79cb684f142c91c6acc0f38bb5ee782d5a7daa86c3d24bb4619489481878825b27719efe",
          "sha256": "183c1ebed8a4155963eaa9868f7f3afb47e9783a35671b594db27dd9077208fe",
          "sha1": "415e7d4c83634c1bcdb0394733f3a6af953dddab",
          "md5": "71a4a06a9ffe1e0143d0126cc3ceaaae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices-java",
          "version": {
            "requires": "1.1.0-beta07"
          },
          "reason": "ads-adservices is in atomic group androidx.privacysandbox.ads"
        }
      ],
      "files": [
        {
          "name": "ads-adservices-1.1.0-beta07.aar",
          "url": "ads-adservices-1.1.0-beta07.aar",
          "size": 202880,
          "sha512": "93df935be08d6db43f1d15f78739614025c811a5865f10547022611e8ed3886165d76c8e6c0e11b23d8cd45a9b2c3ae1f427714df4a51a86bd7187370f278646",
          "sha256": "3c6e4713974dcdaf350cacf33293ab32cd068bc35adec0261a8ab1c4e931c96c",
          "sha1": "f24bf701ce8ed166b55306990f2bda3c4582a43d",
          "md5": "0eb403916c1287a6150fb02efcea40b0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices-java",
          "version": {
            "requires": "1.1.0-beta07"
          },
          "reason": "ads-adservices is in atomic group androidx.privacysandbox.ads"
        }
      ],
      "files": [
        {
          "name": "ads-adservices-1.1.0-beta07.aar",
          "url": "ads-adservices-1.1.0-beta07.aar",
          "size": 202880,
          "sha512": "93df935be08d6db43f1d15f78739614025c811a5865f10547022611e8ed3886165d76c8e6c0e11b23d8cd45a9b2c3ae1f427714df4a51a86bd7187370f278646",
          "sha256": "3c6e4713974dcdaf350cacf33293ab32cd068bc35adec0261a8ab1c4e931c96c",
          "sha1": "f24bf701ce8ed166b55306990f2bda3c4582a43d",
          "md5": "0eb403916c1287a6150fb02efcea40b0"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices-java",
          "version": {
            "requires": "1.1.0-beta07"
          },
          "reason": "ads-adservices is in atomic group androidx.privacysandbox.ads"
        }
      ],
      "files": [
        {
          "name": "ads-adservices-1.1.0-beta07-versionMetadata.json",
          "url": "ads-adservices-1.1.0-beta07-versionMetadata.json",
          "size": 26871,
          "sha512": "8f1bb6a3629dae8df2d574cf73775c5160cb89fb43a9132ac276497a4d6fdd9b3de2364f17348aa22771c3fb1a2e759faff905faa28df92582909d64f8e63b2a",
          "sha256": "178f53c582352a06365652c70fb93b01b5318e8ac79bbd1cf6b26ba2dd92ee15",
          "sha1": "03a93cdedecdfb1aea6024c9e99344e174360940",
          "md5": "5d605c5e2d6c41c7ecf471fd721c5290"
        }
      ]
    }
  ]
}