{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.tiles",
    "module": "tiles",
    "version": "1.4.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-1.4.0-alpha04-sources.jar",
          "url": "tiles-1.4.0-alpha04-sources.jar",
          "size": 71788,
          "sha512": "f81005ac02800ebbbe58698a1841af719c0576aa4066349036a7428fdb956a31da446ac7843673ce86af6e8ab5b295e4e6e38ee7195d4a6a8b807d2e5cd2d392",
          "sha256": "6a943c7756798adc1c828aa90d737b2bbc804b57c5a5246e3932697667f99341",
          "sha1": "92010a55cd7c9b3c875a44c880b80a8505b13ce7",
          "md5": "30ad6a6bcd31db6d36909956782bb491"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-1.4.0-alpha04.aar",
          "url": "tiles-1.4.0-alpha04.aar",
          "size": 252753,
          "sha512": "53c32d712fded18477d6293c6b211235c18727d0347f63eaab6628cc420b2fe5875aed33635a5edf3fe58c7870b6817d4b5edefdba9fa5a9b7810de0ce10d148",
          "sha256": "7b3a8218f188e4ff4defc3e008a4817a37e3ad1eccf884fcb6648026b4b70714",
          "sha1": "5b50e48dd3b35780b1a837d7fa39b1f2b676f58f",
          "md5": "f9b72240f02f568db0f8ec41bcd7db6a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.4.0-alpha04"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-1.4.0-alpha04.aar",
          "url": "tiles-1.4.0-alpha04.aar",
          "size": 252753,
          "sha512": "53c32d712fded18477d6293c6b211235c18727d0347f63eaab6628cc420b2fe5875aed33635a5edf3fe58c7870b6817d4b5edefdba9fa5a9b7810de0ce10d148",
          "sha256": "7b3a8218f188e4ff4defc3e008a4817a37e3ad1eccf884fcb6648026b4b70714",
          "sha1": "5b50e48dd3b35780b1a837d7fa39b1f2b676f58f",
          "md5": "f9b72240f02f568db0f8ec41bcd7db6a"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-1.4.0-alpha04-versionMetadata.json",
          "url": "tiles-1.4.0-alpha04-versionMetadata.json",
          "size": 70560,
          "sha512": "17aa11ded15f835c69ea9b8441203c13593eafd4334317756ded0db531a3180f326f6334a51d9a033a6eacdf9d94f8efcb53bc37deaa4702876cbd082387cf07",
          "sha256": "f35e6637159afb6cfe0c30f1e4e15f127b2b6218a0a10a2dde8c3525b00f1c5b",
          "sha1": "e243cf5fcda2979e28459afeabf278c928064467",
          "md5": "744e5e5c5d71c1af10e8ecffb263d17e"
        }
      ]
    }
  ]
}