version: "1.0.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.2.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.camera"
    artifact_id: "camera-camera2-pipe"
    version: "1.0.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.camera"
    artifact_id: "camera-core"
    version: "1.4.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.concurrent"
    artifact_id: "concurrent-futures-ktx"
    version: "1.2.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.3.2"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-livedata-ktx"
    version: "2.3.1"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.camera"
group_id: "androidx.camera"
artifact_id: "camera-camera2-pipe-integration"
path: "/camera/camera-camera2-pipe-integration"
sha: "2defcd0b1304c392f511d8536e0582143b40edf5"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.camera-camera-camera2-pipe-integration-all-11904523-1.0.0-alpha01.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
  dependency {
    group_id: "androidx.camera"
    artifact_id: "camera-camera2-pipe"
    version: "1.0.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.camera"
    artifact_id: "camera-testing"
    version: "1.0.0-alpha01"
    is_tip_of_tree: true
  }
}
should_publish_docs: false
is_kmp: false
