{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-camera2-pipe-integration",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-testing",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-integration-1.0.0-alpha01-sources.jar",
          "url": "camera-camera2-pipe-integration-1.0.0-alpha01-sources.jar",
          "size": 277981,
          "sha512": "9feee6c9d11b60bbc759e645e499d8a0874aa812681f98749544971d5ecef48941aa55c2734ae47c5c5a35a346a4dc5c7660477927ddf2381791463e830236f9",
          "sha256": "f3f1bad3f5c143cb189b8026adc6e1d9c6ee6bc427ddd013580f9d98864a46ec",
          "sha1": "8a5a45a08c7e5e898c16e947e1105a6c9de0f990",
          "md5": "8d1c82b83278e4ed74bd7c10f54f3baa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-testing",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-integration-1.0.0-alpha01.aar",
          "url": "camera-camera2-pipe-integration-1.0.0-alpha01.aar",
          "size": 937486,
          "sha512": "e5b7c2487a51fa4337caacf0c9950cbf5a7d662dd5b677b3aa6b053d30405af25b19ec852dfffe9efa94f2cb0cdb9307a6340ebe50ad9b910e0cd98da64b2db9",
          "sha256": "fd354dc7728a689df7b9e837f52af0b52bbb306ca2a08ad06289ca56d7a919ed",
          "sha1": "05f88f7e44ca27dcbd239b8084b02bfb35760649",
          "md5": "64d41a3d12f1b6df625285a094b7665e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.0.0-alpha01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.49"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-testing",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-integration-1.0.0-alpha01.aar",
          "url": "camera-camera2-pipe-integration-1.0.0-alpha01.aar",
          "size": 937486,
          "sha512": "e5b7c2487a51fa4337caacf0c9950cbf5a7d662dd5b677b3aa6b053d30405af25b19ec852dfffe9efa94f2cb0cdb9307a6340ebe50ad9b910e0cd98da64b2db9",
          "sha256": "fd354dc7728a689df7b9e837f52af0b52bbb306ca2a08ad06289ca56d7a919ed",
          "sha1": "05f88f7e44ca27dcbd239b8084b02bfb35760649",
          "md5": "64d41a3d12f1b6df625285a094b7665e"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-testing",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-integration-1.0.0-alpha01-versionMetadata.json",
          "url": "camera-camera2-pipe-integration-1.0.0-alpha01-versionMetadata.json",
          "size": 4017,
          "sha512": "efd9809e75691f3ad946b1adc1369b1cfeb3d2f976e7a813bc26df8216745a18a4341792c27280bf08c51fa0443f651ffd8a5c36829e579462ca6a0e96391e48",
          "sha256": "cf64f3ef620f0dd2254bc60c6fac846012d25fd518b3a8253029712ace321a3c",
          "sha1": "8fa26dc17e7d5dafff21916b28a69e2597fa654f",
          "md5": "7b1a3f19da1f03bb292b1980f447e23b"
        }
      ]
    }
  ]
}