{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-camera2-pipe-integration",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-alpha04"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-testing",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder-compose",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-integration-1.0.0-alpha01.aar",
          "url": "camera-camera2-pipe-integration-1.0.0-alpha01.aar",
          "size": 841680,
          "sha512": "cf0654fe8e101a767bd6090151913f0ece56f2c9d8ea443421f5b27f9c2d2168f0d8758a882f7200a3ab6ab3d9e956b4fdb71d1aafdedf51a41010d3ecb684ca",
          "sha256": "62b0d6ff9bc3ce2e09e1ba6c4b2b653e53f895676130f1ab674c8772541e6ce7",
          "sha1": "724b77abafa53eca166ef5f8d38566c67bfaa84d",
          "md5": "96db8083188d8be28c922e59b32c00ba"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.0.0-alpha01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-alpha04"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.49"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-testing",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder-compose",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-integration-1.0.0-alpha01.aar",
          "url": "camera-camera2-pipe-integration-1.0.0-alpha01.aar",
          "size": 841680,
          "sha512": "cf0654fe8e101a767bd6090151913f0ece56f2c9d8ea443421f5b27f9c2d2168f0d8758a882f7200a3ab6ab3d9e956b4fdb71d1aafdedf51a41010d3ecb684ca",
          "sha256": "62b0d6ff9bc3ce2e09e1ba6c4b2b653e53f895676130f1ab674c8772541e6ce7",
          "sha1": "724b77abafa53eca166ef5f8d38566c67bfaa84d",
          "md5": "96db8083188d8be28c922e59b32c00ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-testing",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder-compose",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-integration-1.0.0-alpha01-sources.jar",
          "url": "camera-camera2-pipe-integration-1.0.0-alpha01-sources.jar",
          "size": 261747,
          "sha512": "802047d35406c377c3ffaa5c5e90802b00cbf2184eb822aa264ab0bcc00a69cca41638e17753b477f4e2c890b44a1c8a05f15a856d6f4eb4e6370e455192cb56",
          "sha256": "195df2e8400bc2f485d926192efae6d197bf17ac523382e76db9459d4cc3a793",
          "sha1": "1fca451c89bfc8b57895b7471a49cbc97744aaa9",
          "md5": "285627ef9503467898f6e64bf4a94904"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-testing",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder-compose",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-integration-1.0.0-alpha01-versionMetadata.json",
          "url": "camera-camera2-pipe-integration-1.0.0-alpha01-versionMetadata.json",
          "size": 4017,
          "sha512": "efd9809e75691f3ad946b1adc1369b1cfeb3d2f976e7a813bc26df8216745a18a4341792c27280bf08c51fa0443f651ffd8a5c36829e579462ca6a0e96391e48",
          "sha256": "cf64f3ef620f0dd2254bc60c6fac846012d25fd518b3a8253029712ace321a3c",
          "sha1": "8fa26dc17e7d5dafff21916b28a69e2597fa654f",
          "md5": "7b1a3f19da1f03bb292b1980f447e23b"
        }
      ]
    }
  ]
}