version: "1.1.0-alpha03"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.1.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.concurrent"
    artifact_id: "concurrent-futures-ktx"
    version: "1.1.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core-ktx"
    version: "1.7.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.health"
group_id: "androidx.health"
artifact_id: "health-services-client"
path: "/health/health-services-client"
sha: "532d983f8461184e5a33dce4be7b62053acc967d"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.health-health-services-client-all-11937575-1.1.0-alpha03.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
