{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.health",
    "module": "health-services-client",
    "version": "1.1.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "health-services-client-1.1.0-alpha03-sources.jar",
          "url": "health-services-client-1.1.0-alpha03-sources.jar",
          "size": 177546,
          "sha512": "989b90bfb86bf63f476c12fa1c2d307a2447298d56a097ffe7825403b25e47f527a91bc1c46b2b2d84754a0ab77c833cc889f60b7b9a67a5fc9dbf5ff736682f",
          "sha256": "130dd794640be517c3e838adac58c7e4b57fd4e1bbb0e2d05a64b7af997633b2",
          "sha1": "0069b7e4311a1951cf05830a3d53385b4fde9083",
          "md5": "d6a84ea7318ac5de92178a7c155f43d3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "health-services-client-1.1.0-alpha03.aar",
          "url": "health-services-client-1.1.0-alpha03.aar",
          "size": 1118224,
          "sha512": "1decf815d203955d1133439464fabdcf30f498491d6e7b021c84dbeec724739eee764d770e239209c4418f1e55f5f80e85d454985f4d89bad5e643b3086cc226",
          "sha256": "1cf7b545835270f985ac29e20fec83c53b5b32027cb06ab478b8d46977dbed95",
          "sha1": "a86cb0ce60920dbba6551bd1bc285bd2912db59a",
          "md5": "17f062db59d0907ad05396ea1354df65"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-android"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "health-services-client-1.1.0-alpha03.aar",
          "url": "health-services-client-1.1.0-alpha03.aar",
          "size": 1118224,
          "sha512": "1decf815d203955d1133439464fabdcf30f498491d6e7b021c84dbeec724739eee764d770e239209c4418f1e55f5f80e85d454985f4d89bad5e643b3086cc226",
          "sha256": "1cf7b545835270f985ac29e20fec83c53b5b32027cb06ab478b8d46977dbed95",
          "sha1": "a86cb0ce60920dbba6551bd1bc285bd2912db59a",
          "md5": "17f062db59d0907ad05396ea1354df65"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "health-services-client-1.1.0-alpha03-versionMetadata.json",
          "url": "health-services-client-1.1.0-alpha03-versionMetadata.json",
          "size": 57710,
          "sha512": "c7eb7a4db6221747b2257a76103a2812c0bf81a8cd2ae1603923f359d0526424ba653b5b9a73538f96e81e50dff7c5d48693c3a87ee5668ca7d63ba83c562cd6",
          "sha256": "6345ddf36523484404ad853f6e8024f21c6c2fd24b291730ad20a3a6e82c4135",
          "sha1": "b37b0dc5305ca65cf78edc1279e0b32f906aae3b",
          "md5": "ace063dbbbe05cf44d67f23e73e1a0f4"
        }
      ]
    }
  ]
}