{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window.extensions.core",
    "module": "core",
    "version": "1.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.1.0-alpha01-sources.jar",
          "url": "core-1.1.0-alpha01-sources.jar",
          "size": 3620,
          "sha512": "3bd140372842b5921e1efb168e5540cf24369005fd3db0b79024fd0489450cc5bffa345ad2835aeddfa64f6ccb42f6aa99f9ee3fd4a3d7e8c0998ee15752c4fe",
          "sha256": "95d5005752d513694d7922553af4249855f05a358fff7b2016686c1f3828ebcb",
          "sha1": "cd7d30a01af4580c06bf6e5f1dd09c1471b2ece7",
          "md5": "8ea1e8355ad1d8d68f654620c93b9da1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-1.1.0-alpha01.aar",
          "url": "core-1.1.0-alpha01.aar",
          "size": 2948,
          "sha512": "19a188d6b06297b2a930308c9709a005a408486ac4884c7397b33f97a004ef515e99c19aeb9429d0de345dc26b593af529c3d23bb6973f191a237feaebb244af",
          "sha256": "b504d03a0eba4071107a40c7ad2e7f12d962b10ed3c6b656a2de2ee398c322aa",
          "sha1": "a8d6c60f2dd3b2e8f56975ff2cc81793491a0a95",
          "md5": "ed522b9456751dc8c6c679a3084ef58c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.1.0-alpha01.aar",
          "url": "core-1.1.0-alpha01.aar",
          "size": 2948,
          "sha512": "19a188d6b06297b2a930308c9709a005a408486ac4884c7397b33f97a004ef515e99c19aeb9429d0de345dc26b593af529c3d23bb6973f191a237feaebb244af",
          "sha256": "b504d03a0eba4071107a40c7ad2e7f12d962b10ed3c6b656a2de2ee398c322aa",
          "sha1": "a8d6c60f2dd3b2e8f56975ff2cc81793491a0a95",
          "md5": "ed522b9456751dc8c6c679a3084ef58c"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-1.1.0-alpha01-versionMetadata.json",
          "url": "core-1.1.0-alpha01-versionMetadata.json",
          "size": 449,
          "sha512": "5886cb5b31c6b6d316ed2eb88504f82ac0cf6ba5189ed701db0ec5889c06b6811b217731147c2754debe27e5d72eecc1e72c5409eda8bd5f2968a2214808e916",
          "sha256": "fddaf725f11c8bf2dafbd4bbe45e58a02ef79ca131cf91df37a6018f7f143053",
          "sha1": "c649362b3fe78c53f334d69a2ccf458339d51879",
          "md5": "cda58c7a6f2372c63a5a58ba6b155706"
        }
      ]
    }
  ]
}