{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear",
    "module": "wear",
    "version": "1.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wear-1.4.0-alpha01-sources.jar",
          "url": "wear-1.4.0-alpha01-sources.jar",
          "size": 145640,
          "sha512": "da2289ea622e5dde726b47a136bba8ca4a0b2581ee5b694bdab4356dff3d4d9e6d2ffba193f2408b7c296c210054dcd97a59e4b249818e844f27886be6725c8f",
          "sha256": "40e53eb5804fdc71d4d4906a6ca494b685df79b207ce7f93f6d562cc3f7b0156",
          "sha1": "447ae677c5c0484fd5d373c943015bc76dce6a2f",
          "md5": "994875d75cb023c1e55e5efe2d639901"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "wear-1.4.0-alpha01.aar",
          "url": "wear-1.4.0-alpha01.aar",
          "size": 312070,
          "sha512": "018ee389d43dc6d0782b2cf58aee2ecd370c26a13c99bd90eeb17c0d1f8004760eac0abfa860cf50104a93271e100cea4c95f89a16ccfd31ff00526b3722286e",
          "sha256": "c25f730555317a9a2f70d9e2734e2f1fece96766599341e8ed14b7f94081ffd1",
          "sha1": "f2567e761493a83059c0e86d0bc2e78878fe5760",
          "md5": "6de1c4894447f31b548e0d77a21b3587"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "wear-1.4.0-alpha01.aar",
          "url": "wear-1.4.0-alpha01.aar",
          "size": 312070,
          "sha512": "018ee389d43dc6d0782b2cf58aee2ecd370c26a13c99bd90eeb17c0d1f8004760eac0abfa860cf50104a93271e100cea4c95f89a16ccfd31ff00526b3722286e",
          "sha256": "c25f730555317a9a2f70d9e2734e2f1fece96766599341e8ed14b7f94081ffd1",
          "sha1": "f2567e761493a83059c0e86d0bc2e78878fe5760",
          "md5": "6de1c4894447f31b548e0d77a21b3587"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "wear-1.4.0-alpha01-versionMetadata.json",
          "url": "wear-1.4.0-alpha01-versionMetadata.json",
          "size": 27752,
          "sha512": "173d1ad1b3fe8865316b8c2f3e47c99c7096eb4ad15db70a7f7abe99ad7e28993a5657d75d614fb856e849f80670c2dcde559e66b5f2e8635b3b347132ac6ca3",
          "sha256": "a9efbf6830664fa98ea15b0f52cf0c59ab0352c70660d493c7036f805bf70528",
          "sha1": "d3e0d784f8fbc21ecd3404c25c0778258882d3f9",
          "md5": "0e9eb4dd2813da422d600f8b89825b1a"
        }
      ]
    }
  ]
}