{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tracing",
    "module": "tracing-perfetto",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-binary",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-handshake",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-1.0.0.aar",
          "url": "tracing-perfetto-1.0.0.aar",
          "size": 35955,
          "sha512": "43c685bc1c6edcd001f97e4916eb859ed0951560f424ea6e1f8b95b121106786c28c100dcc830150a27b389315f8a3966cc773381c4378e385c2e572cb382f2d",
          "sha256": "6e91032af886ceede0d38869229255211eab3bbbe6d1023dcf8df2e3456e043d",
          "sha1": "847b3cd1e6c7c59818e332eefb29e184633c7346",
          "md5": "d7b35443b7706ca9073ffe7a2b0b6085"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-binary",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-handshake",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-1.0.0.aar",
          "url": "tracing-perfetto-1.0.0.aar",
          "size": 35955,
          "sha512": "43c685bc1c6edcd001f97e4916eb859ed0951560f424ea6e1f8b95b121106786c28c100dcc830150a27b389315f8a3966cc773381c4378e385c2e572cb382f2d",
          "sha256": "6e91032af886ceede0d38869229255211eab3bbbe6d1023dcf8df2e3456e043d",
          "sha1": "847b3cd1e6c7c59818e332eefb29e184633c7346",
          "md5": "d7b35443b7706ca9073ffe7a2b0b6085"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-binary",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-handshake",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-1.0.0-sources.jar",
          "url": "tracing-perfetto-1.0.0-sources.jar",
          "size": 14487,
          "sha512": "9a6c015446dc683d7b896c66b42f19df67c412ff461090bad6bc43faa338fe4de7f280faa0c7656d1084fdb266f0edba926d6a9c43b7ce0006d8e2b58d4ee881",
          "sha256": "6c655ab68b8845586046196370e14e00e4dee5a6cee5e9cb3e0c9d3ecdaba7fa",
          "sha1": "a58a01f43aa01f543a7189d76d02dc4627c5bb73",
          "md5": "41957a972aa538cd795a0069df445b35"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-binary",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-handshake",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-1.0.0-versionMetadata.json",
          "url": "tracing-perfetto-1.0.0-versionMetadata.json",
          "size": 559,
          "sha512": "b2d8d6146cec2fc2897727c16e9fb9f2d976ad7b1f152886514a4cefe3a552d781c9e3f03aea3d9b3085a884cc6d696ce5435c5d625e9e3f7a989b58b877ace5",
          "sha256": "02ddbc61aef80c7c02487342146a6b19a42b968b74aeec92ecc33418905f7b87",
          "sha1": "c207414efcd035908bc478254f1febb97f9bd05f",
          "md5": "711e5def47468e7ddbdfbee6f6a9b28d"
        }
      ]
    }
  ]
}