{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appcompat",
    "module": "appcompat",
    "version": "1.7.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.7.0-rc01"
          },
          "reason": "appcompat is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-1.7.0-rc01-sources.jar",
          "url": "appcompat-1.7.0-rc01-sources.jar",
          "size": 496408,
          "sha512": "9d37163ca4af0d2d13f87ce88bb9a3c19177de052c9d0b1facd4b1940997312b6dc07e625f6928b8bddde27f7746d4b27932f40a158bfb28446a5145d95e1891",
          "sha256": "6e3d3af46fbd9cb51ce6feb791274a9c2da11b64ba7b967a5dd12915e0aa031a",
          "sha1": "c66c25a939bfe4b18249922dc4e7a19caca8bf68",
          "md5": "acd13fd1ac2f647c1571e05aa01660af"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.7.0-rc01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.cursoradapter",
          "module": "cursoradapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.7.0-rc01"
          },
          "reason": "appcompat is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-1.7.0-rc01.aar",
          "url": "appcompat-1.7.0-rc01.aar",
          "size": 1149032,
          "sha512": "a27b163ca72e7e117b44bcd29382d2122aa3925c0b6794e56064076a0a8203f91ff20af5736c082405de4543d4d5570fc15b164c8a711d2a195497aa3feff377",
          "sha256": "fb0d9c05444c065df1bd8ddd2cd6011c81b52fd01f2de95ded391d52d2c5136c",
          "sha1": "88a786f4f0055cd1e69cdf307c4f943407cea221",
          "md5": "313739c088f076dae823ee871b655f79"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.7.0-rc01"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.cursoradapter",
          "module": "cursoradapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.resourceinspection",
          "module": "resourceinspection-annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.7.0-rc01"
          },
          "reason": "appcompat is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-1.7.0-rc01.aar",
          "url": "appcompat-1.7.0-rc01.aar",
          "size": 1149032,
          "sha512": "a27b163ca72e7e117b44bcd29382d2122aa3925c0b6794e56064076a0a8203f91ff20af5736c082405de4543d4d5570fc15b164c8a711d2a195497aa3feff377",
          "sha256": "fb0d9c05444c065df1bd8ddd2cd6011c81b52fd01f2de95ded391d52d2c5136c",
          "sha1": "88a786f4f0055cd1e69cdf307c4f943407cea221",
          "md5": "313739c088f076dae823ee871b655f79"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.7.0-rc01"
          },
          "reason": "appcompat is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-1.7.0-rc01-versionMetadata.json",
          "url": "appcompat-1.7.0-rc01-versionMetadata.json",
          "size": 69004,
          "sha512": "d2bb8047aced2ef7a857ee52b03f8072f3fd7af0449155ddd766b19a2a8889d0a3a365ef383136b13853c34c60433a304466258f9fd42e37a215f605fb1fa240",
          "sha256": "680cb0f7e25409b2542fc9013265f7a23801297abb9089c42c23fe5dac5a7fb1",
          "sha1": "2d7cc299eadab95d9ccefc2aedd29d560579acb4",
          "md5": "fb9c0d5f27b9d89b3a4cffff600e60f8"
        }
      ]
    }
  ]
}