{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.glance",
    "module": "glance-template",
    "version": "1.0.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "glance-template-1.0.0-alpha06-sources.jar",
          "url": "glance-template-1.0.0-alpha06-sources.jar",
          "size": 19812,
          "sha512": "bd1528326444d8ea139d395006b00a7262995ac8b35706ee81ecc1b717f5b72991b25a5d40232a49a36a1e7c714792bc62f4f0f2a067370c404fb0c6b78ff02f",
          "sha256": "2674ebb9cfccfdc68ca680a467637856009d5bc7a63ba664f2925b3659999814",
          "sha1": "481950014c345f3fcfc28ab109e77e96b728f22e",
          "md5": "c26b29c448c1f1bd23f2ec662d51890d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "glance-template-1.0.0-alpha06.aar",
          "url": "glance-template-1.0.0-alpha06.aar",
          "size": 163200,
          "sha512": "833168d0c100848e60b07251ed0beed1b33efee8215a738e2d8b6a8f10fb1360a18a40057ba101818f3aad551a820a2f2901fe303c71fa53a899bd353958993d",
          "sha256": "d43cb5468260a804e6123dbcc9d5f758fc4fadbb65ab581dc41a497e34d8a0d7",
          "sha1": "71c785196c2bd475c7b82ce3e56f98e6f07d28b2",
          "md5": "0cd243295c2ad678e8d94603e7dc4bf5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "glance-template-1.0.0-alpha06.aar",
          "url": "glance-template-1.0.0-alpha06.aar",
          "size": 163200,
          "sha512": "833168d0c100848e60b07251ed0beed1b33efee8215a738e2d8b6a8f10fb1360a18a40057ba101818f3aad551a820a2f2901fe303c71fa53a899bd353958993d",
          "sha256": "d43cb5468260a804e6123dbcc9d5f758fc4fadbb65ab581dc41a497e34d8a0d7",
          "sha1": "71c785196c2bd475c7b82ce3e56f98e6f07d28b2",
          "md5": "0cd243295c2ad678e8d94603e7dc4bf5"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "glance-template-1.0.0-alpha06-versionMetadata.json",
          "url": "glance-template-1.0.0-alpha06-versionMetadata.json",
          "size": 9944,
          "sha512": "1f2569f7d60e2963fea7a922ac8c8114fa851dc7301684b9691e9c750f8f1bf35a1b3aee531e3a8085c1f0daf63ba2e161d73bb25940eacd554c0bb243db440b",
          "sha256": "63733d965f2444c3803f2f338e030bb7a6fc57f07b7c3e194e18ecb6351fd42c",
          "sha1": "3eb7f2a6aedfa213a153ae50ffd2885fb0d8787b",
          "md5": "09b4f9bf2437827abae6c630fd0b9165"
        }
      ]
    }
  ]
}