{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.car.app",
    "module": "app-automotive",
    "version": "1.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.car.app",
          "module": "app",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.car.app",
          "module": "app",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "androidx.car.app",
          "module": "app-projected",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "androidx.car.app",
          "module": "app-testing",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "app-automotive-1.4.0-alpha01.aar",
          "url": "app-automotive-1.4.0-alpha01.aar",
          "size": 267079,
          "sha512": "54953fe1b91fb218821542ae83016d2e1672e7f4f39038408c6cdd9e6c8e3cdcdff818f63b880adcb74182e5106efca2b8137a8222c5c86b0795277446e6cd32",
          "sha256": "2bf797b279e34ba583ceb68b43cb198f66ef9363b7fd6365be29ec1489b571c8",
          "sha1": "53c665b2b00ffb25520b8bc86ca9b1ed481cd384",
          "md5": "521f00fe15a77263a47bb8885eaacd6a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.car.app",
          "module": "app",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-android"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.car.app",
          "module": "app",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "androidx.car.app",
          "module": "app-projected",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "androidx.car.app",
          "module": "app-testing",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "app-automotive-1.4.0-alpha01.aar",
          "url": "app-automotive-1.4.0-alpha01.aar",
          "size": 267079,
          "sha512": "54953fe1b91fb218821542ae83016d2e1672e7f4f39038408c6cdd9e6c8e3cdcdff818f63b880adcb74182e5106efca2b8137a8222c5c86b0795277446e6cd32",
          "sha256": "2bf797b279e34ba583ceb68b43cb198f66ef9363b7fd6365be29ec1489b571c8",
          "sha1": "53c665b2b00ffb25520b8bc86ca9b1ed481cd384",
          "md5": "521f00fe15a77263a47bb8885eaacd6a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.car.app",
          "module": "app",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "androidx.car.app",
          "module": "app-projected",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "androidx.car.app",
          "module": "app-testing",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "app-automotive-1.4.0-alpha01-sources.jar",
          "url": "app-automotive-1.4.0-alpha01-sources.jar",
          "size": 82649,
          "sha512": "8b4c0b369e97bc91aa81048a6534cf010b8387e4dfdaec27d9515a918ffb1897f8b364b4d9cb1b73f3b5b95cbd091ba91cb394b58f57ba480798c45b0307f9ff",
          "sha256": "ae3c31065dda1e4e96c602513487a22e809a6f5fce9dbd46e06c5ca6691f740c",
          "sha1": "83f9f13fba68d9964373eda1a74da192038f95e3",
          "md5": "97dd8fe2f6be6a6d0214f052eae7a44a"
        }
      ]
    }
  ]
}