{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-animation-testing",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-animation-testing-1.0.0-sources.jar",
          "url": "core-animation-testing-1.0.0-sources.jar",
          "size": 2452,
          "sha512": "5da7787824c8000988f88ad3c93f75cfa1f018afa48ebfdd3c0c82ebb5ec59aa1ffaf3088371b5f50c23fe6a58df07a93274d53da9b42c510b797417973616ab",
          "sha256": "9a3657db22ee30fe64f4713cb3d3a295669652e34352bab2d5cfd29ca441fec0",
          "sha1": "c305a43526c396742fab7fd133ab040cb595de34",
          "md5": "275ba0fb63620f67b1888bab5a4af5dc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-animation-testing-1.0.0.aar",
          "url": "core-animation-testing-1.0.0.aar",
          "size": 4022,
          "sha512": "fabe1818918581e890bd374d3b36a638ae9a16e35bb1443260f7c69efa75e6372096cf6668784c7c47912ee9f1b3413a51de82ba5f9ecdc87a4a4380190c82f1",
          "sha256": "8ca6bf5bba28e59a837ae0ac979092cd46a1358ff89a07d6e9a36d883fc34e7f",
          "sha1": "24e4e2a270d1a134ca58ebe448d059304a86f109",
          "md5": "1cba9be5cf3f6bb4d8dfa5c11e64b78f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-animation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-animation-testing-1.0.0.aar",
          "url": "core-animation-testing-1.0.0.aar",
          "size": 4022,
          "sha512": "fabe1818918581e890bd374d3b36a638ae9a16e35bb1443260f7c69efa75e6372096cf6668784c7c47912ee9f1b3413a51de82ba5f9ecdc87a4a4380190c82f1",
          "sha256": "8ca6bf5bba28e59a837ae0ac979092cd46a1358ff89a07d6e9a36d883fc34e7f",
          "sha1": "24e4e2a270d1a134ca58ebe448d059304a86f109",
          "md5": "1cba9be5cf3f6bb4d8dfa5c11e64b78f"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-animation-testing-1.0.0-versionMetadata.json",
          "url": "core-animation-testing-1.0.0-versionMetadata.json",
          "size": 346,
          "sha512": "f6d79b7347ac7474ca0afdba71c730e9d66995d442865aebd1cc480d4f77c6e084eef8baf78067bab1087a6009efdc55a052710fc5718bcb979beba5db0e3b33",
          "sha256": "0ffee50f9c8484cbda0b38e8ab285ac43c3e9aca3e64e91a2f914af97d5f10d7",
          "sha1": "03b614b7119779b1ec6a457091e09b2843476484",
          "md5": "6176c04e51c44c8f280a199aba3fca18"
        }
      ]
    }
  ]
}