{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.tools",
    "module": "tools-apigenerator",
    "version": "1.0.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-apigenerator-1.0.0-alpha08.jar",
          "url": "tools-apigenerator-1.0.0-alpha08.jar",
          "size": 1183986,
          "sha512": "413bcc38c407dd7d7b369448ad7f5bde81b7a1e2caf1edaefe0b8f7732e303fa9dc964f18effe036d39b3432eca86925faf2ca7b776a065ed709bad31ed0140c",
          "sha256": "30f5c0cf45648de4ea7d48064c2227cefba43a576cda5d4df8bb63ef25c1c829",
          "sha1": "82ea5aaf2b961a3c557ba05141f9b5f745667840",
          "md5": "12f8d20ec9b747ee50c685454228abc8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-apigenerator-1.0.0-alpha08.jar",
          "url": "tools-apigenerator-1.0.0-alpha08.jar",
          "size": 1183986,
          "sha512": "413bcc38c407dd7d7b369448ad7f5bde81b7a1e2caf1edaefe0b8f7732e303fa9dc964f18effe036d39b3432eca86925faf2ca7b776a065ed709bad31ed0140c",
          "sha256": "30f5c0cf45648de4ea7d48064c2227cefba43a576cda5d4df8bb63ef25c1c829",
          "sha1": "82ea5aaf2b961a3c557ba05141f9b5f745667840",
          "md5": "12f8d20ec9b747ee50c685454228abc8"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-apigenerator-1.0.0-alpha08.jar",
          "url": "tools-apigenerator-1.0.0-alpha08.jar",
          "size": 1183986,
          "sha512": "413bcc38c407dd7d7b369448ad7f5bde81b7a1e2caf1edaefe0b8f7732e303fa9dc964f18effe036d39b3432eca86925faf2ca7b776a065ed709bad31ed0140c",
          "sha256": "30f5c0cf45648de4ea7d48064c2227cefba43a576cda5d4df8bb63ef25c1c829",
          "sha1": "82ea5aaf2b961a3c557ba05141f9b5f745667840",
          "md5": "12f8d20ec9b747ee50c685454228abc8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-apigenerator-1.0.0-alpha08-sources.jar",
          "url": "tools-apigenerator-1.0.0-alpha08-sources.jar",
          "size": 9246,
          "sha512": "4cbb45bd1b03baef9f50208a28a9170d7ade76c7e588e63abe30c5bf3b587a6f4d328e3fa409e869f7956ca17ab20dc770a0681cd0cd9e46bef5b605d9ae57b2",
          "sha256": "3ab9fd6743badbb9ef0ce8e691c50c54f1fe8cf57e9485871988d4bd8e9da19c",
          "sha1": "5855fa673d6226d58e3305f8b683998539935547",
          "md5": "b280961dae3c809a61ef72170347c7d8"
        }
      ]
    }
  ]
}