{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.ui",
    "module": "ui-provider",
    "version": "1.0.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "ui-provider is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "ui-provider is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-provider-1.0.0-alpha08-sources.jar",
          "url": "ui-provider-1.0.0-alpha08-sources.jar",
          "size": 6788,
          "sha512": "af962301817145b9abed3e7429cdcdb4d6bb8f0a6f459054aea93322b58107d3092300df6c02d2aa99ecff2f377112aafc218cffb36ee44e3dd73192f162e0a8",
          "sha256": "3b1c17c2458707f1f2154ab590d43acebddbb587bb998cacf53230879031c9a3",
          "sha1": "2a40f9295a0476fe2fe36da96a0d929f7733c97b",
          "md5": "df93098a202bcdd4cd37a6d670b64914"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "ui-provider is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "ui-provider is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-provider-1.0.0-alpha08.aar",
          "url": "ui-provider-1.0.0-alpha08.aar",
          "size": 20081,
          "sha512": "37827e96bd51e704a31287c7384a7f658468503036913bfc3340e956ebfdf47747bdffbb5fd7411c3cec4ef2acf69c6df36ad5d5051f12169e1f6d479f63a09e",
          "sha256": "a1c96d84cfbf10ddaa2ca297a6cd45a7e1f1b0dc35d966204773574a80007eb9",
          "sha1": "89659228380d2f190793e2f0878836c10bf76e09",
          "md5": "b82283ee000b7012316a1ae215e0ac24"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "ui-provider is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "ui-provider is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-provider-1.0.0-alpha08.aar",
          "url": "ui-provider-1.0.0-alpha08.aar",
          "size": 20081,
          "sha512": "37827e96bd51e704a31287c7384a7f658468503036913bfc3340e956ebfdf47747bdffbb5fd7411c3cec4ef2acf69c6df36ad5d5051f12169e1f6d479f63a09e",
          "sha256": "a1c96d84cfbf10ddaa2ca297a6cd45a7e1f1b0dc35d966204773574a80007eb9",
          "sha1": "89659228380d2f190793e2f0878836c10bf76e09",
          "md5": "b82283ee000b7012316a1ae215e0ac24"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "ui-provider is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "ui-provider is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-provider-1.0.0-alpha08-versionMetadata.json",
          "url": "ui-provider-1.0.0-alpha08-versionMetadata.json",
          "size": 591,
          "sha512": "c93654471d68763683616e675c145706d6536ce4fff0a3caf95b1d87ed2f42ac4030805d1bbfa17f262ec9c8b1608ea6815223bda1073e46f4cf12ced4d64b0f",
          "sha256": "4c6a07ad082841be03595b806b464724439ca9c2afb52b5c36675c54219ba939",
          "sha1": "bfba469dc2271cefc34a58e67c7b55a485125e57",
          "md5": "e575779d8d7eb336353df823f6533ec4"
        }
      ]
    }
  ]
}