{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-compose",
    "version": "1.9.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.9.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.0-alpha03"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.9.0-alpha03"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.9.0-alpha03.aar",
          "url": "activity-compose-1.9.0-alpha03.aar",
          "size": 1139062,
          "sha512": "2d6e4a4f3e956085fc8ff02f031dbc8aa425ee06815994eb15e07b478e8e847cc33def97e3e0158e285be9a53ddfdf344c43d0d82a53aba35faeeae18c9a48ce",
          "sha256": "8cec42f749bb9ba22a8647df5e7ab3771402f6fb04a9cfeedf2125ca64ab2164",
          "sha1": "307be1e6b2a41f46a110a9774c1e32415460814a",
          "md5": "75a407ec57e11908f04e4be7509e4163"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.9.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.0-alpha03"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.9.0-alpha03"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.9.0-alpha03.aar",
          "url": "activity-compose-1.9.0-alpha03.aar",
          "size": 1139062,
          "sha512": "2d6e4a4f3e956085fc8ff02f031dbc8aa425ee06815994eb15e07b478e8e847cc33def97e3e0158e285be9a53ddfdf344c43d0d82a53aba35faeeae18c9a48ce",
          "sha256": "8cec42f749bb9ba22a8647df5e7ab3771402f6fb04a9cfeedf2125ca64ab2164",
          "sha1": "307be1e6b2a41f46a110a9774c1e32415460814a",
          "md5": "75a407ec57e11908f04e4be7509e4163"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.0-alpha03"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.9.0-alpha03"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.9.0-alpha03-sources.jar",
          "url": "activity-compose-1.9.0-alpha03-sources.jar",
          "size": 10776,
          "sha512": "00337d440800a902ae81481705444e524e97ba06d03aa0c8886e52173ac3c3790171de2d418ba6efa09afde21701068bd368be59443629d4e2a60e12a25ed746",
          "sha256": "6dd344fde10712c9332a18f69de2a005fb8956c20964fe0c64c65c836ff303ad",
          "sha1": "8bde89d86287051e6a4e6eda6699e128b945b147",
          "md5": "1016aef70e82b1da5d2e98ff31015eea"
        },
        {
          "name": "activity-compose-1.9.0-alpha03-samples-sources.jar",
          "url": "activity-compose-1.9.0-alpha03-samples-sources.jar",
          "size": 3667,
          "sha512": "1140cf2b550b42ce26c25e6eeedbfe42c7118a3ac3610b64e838ae32f95850de5181e476bdb9826a9709498a94413dd8f1876bd00353dff39b784480cb3f6fb8",
          "sha256": "7d865092563b2fb1c0f0714f054f97501b8d0d607d07f5fee415baa994714143",
          "sha1": "d164345e6fcf25df9c64c75caadc53b32c9e69e2",
          "md5": "cb8ccda1fde3e809f793104f507e3cc7"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.0-alpha03"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.9.0-alpha03"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.9.0-alpha03-versionMetadata.json",
          "url": "activity-compose-1.9.0-alpha03-versionMetadata.json",
          "size": 2701,
          "sha512": "38e96fef550bc65a3cf2ef95fe4db98d47cef44c3db84ce19558c46543fce2b7f45b4dcad6c014993537706d3efd7d5d0b5b252b46c69d16a1e4b56fab8dee3f",
          "sha256": "edf2427da6f69559a4988536153f0826f46d319a7b2b80ef23c57fa83d23c7f3",
          "sha1": "3ce35c3833c670be76e757d0e68e8a9b4d0f6f15",
          "md5": "0866fd37c1abd4c3104bbf8b74e478d9"
        }
      ]
    }
  ]
}