{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-navigation",
    "version": "1.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-navigation-1.4.0-alpha03.aar",
          "url": "compose-navigation-1.4.0-alpha03.aar",
          "size": 61007,
          "sha512": "5bb94c162e723ddef18963525886cbf2d709b0d70b5e875ec4397492f5b09dbf0535c0e8945c26526de276e845534c55f204c5d8542527278e63e21dc8dcda31",
          "sha256": "b85b56b5fcf4c99bb58d978aa6708f7b97a1740f53036178424d72ef5e0022e8",
          "sha1": "b9fe0325c35028f12b5d108533346e44e09516a8",
          "md5": "c6946f996793e1e6cdb56d917523d176"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-navigation-1.4.0-alpha03.aar",
          "url": "compose-navigation-1.4.0-alpha03.aar",
          "size": 61007,
          "sha512": "5bb94c162e723ddef18963525886cbf2d709b0d70b5e875ec4397492f5b09dbf0535c0e8945c26526de276e845534c55f204c5d8542527278e63e21dc8dcda31",
          "sha256": "b85b56b5fcf4c99bb58d978aa6708f7b97a1740f53036178424d72ef5e0022e8",
          "sha1": "b9fe0325c35028f12b5d108533346e44e09516a8",
          "md5": "c6946f996793e1e6cdb56d917523d176"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-navigation-1.4.0-alpha03-sources.jar",
          "url": "compose-navigation-1.4.0-alpha03-sources.jar",
          "size": 8787,
          "sha512": "ebcad6e73aba567e6f241ab6ca1db728fcb56eebdfd6fe3c109bfd7b41424f54a5bc31f1f36b7ef6db2d5547e81d4fc16928150f59c634f8d8ab49a74940c25f",
          "sha256": "c6de45da268da7d47e0aa115f9bb405650415b194d2d64d31cbdcecc6e1c12f4",
          "sha1": "fb3f22ff2efc7ec408799cc6f370111f7910b2f6",
          "md5": "b4c6c5c3a7101a49d856f8295d6a7636"
        },
        {
          "name": "compose-navigation-1.4.0-alpha03-samples-sources.jar",
          "url": "compose-navigation-1.4.0-alpha03-samples-sources.jar",
          "size": 2364,
          "sha512": "ca81a346711ffb995b1dbdfd75ca38f83724b80fd50ba0ae51c44126238f4b48f7bc8627c6e812cb7a9c5fc6a6a5a01a2b84dec91e793c566df1d9875ae00323",
          "sha256": "cc3cbdd816d42ba2072a9e7629e37174d66a9ee1ed128f4e18f61e60e6576a74",
          "sha1": "c63d872e0730842a15af478fd0e9e13ab13d497e",
          "md5": "9d426a8117c50440f22ffe360eaabee6"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-navigation-1.4.0-alpha03-versionMetadata.json",
          "url": "compose-navigation-1.4.0-alpha03-versionMetadata.json",
          "size": 3098,
          "sha512": "a03f7fe3c36e30892fa73f1a7f69021cad47b599fef7d51ee14aba5c5da7f11133da9c93aaa91b8fa6374e02f004e97d2c0c0adc6fc95e607d43b6e7cd93fc04",
          "sha256": "7b0001c22a0ddfaa363e1dd3056468b159edc0be2bbb8c1c1c07941b21221e59",
          "sha1": "796656b7225490e3373b29735454d04a8c61dbb7",
          "md5": "193253154870d5a498c6e1f5dc069981"
        }
      ]
    }
  ]
}