version: "1.1.0-rc01"
dependency_list {
}
release_checklist {
}
build_id: "androidx.glance"
group_id: "androidx.glance"
artifact_id: "glance-appwidget-external-protobuf"
path: "/glance/glance-appwidget-external-protobuf"
sha: "6a548cd410cbbc419dd2b8444d893385d14e20d4"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.glance-glance-appwidget-external-protobuf-all-11937636-1.1.0-rc01.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
  dependency {
    group_id: "androidx.glance"
    artifact_id: "glance"
    version: "1.1.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.glance"
    artifact_id: "glance-appwidget"
    version: "1.1.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.glance"
    artifact_id: "glance-appwidget-preview"
    version: "1.1.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.glance"
    artifact_id: "glance-appwidget-proto"
    version: "1.1.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.glance"
    artifact_id: "glance-appwidget-testing"
    version: "1.1.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.glance"
    artifact_id: "glance-material"
    version: "1.1.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.glance"
    artifact_id: "glance-material3"
    version: "1.1.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.glance"
    artifact_id: "glance-preview"
    version: "1.1.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.glance"
    artifact_id: "glance-testing"
    version: "1.1.0-rc01"
    is_tip_of_tree: true
  }
}
should_publish_docs: false
is_kmp: false
