{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.glance",
    "module": "glance-appwidget-external-protobuf",
    "version": "1.1.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-external-protobuf-1.1.0-rc01.jar",
          "url": "glance-appwidget-external-protobuf-1.1.0-rc01.jar",
          "size": 706479,
          "sha512": "6de8f335e5a4e0883156c51d17d6d84946e7b7b3e23cb5534e89259ce2d9f5aefbf4b19e970eff391e33071a848667bf10825fd0a2a2c3afaab584de93cc8199",
          "sha256": "edb0f014f07cc9e95f0ca35066ead832d48728b762ad792bafdfa715c5f4b429",
          "sha1": "a529ac22cca28214b7dccf8d11288be8cc0708f9",
          "md5": "351b949f988b50b0ebc7feb0ec632e62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-external-protobuf-1.1.0-rc01.jar",
          "url": "glance-appwidget-external-protobuf-1.1.0-rc01.jar",
          "size": 706479,
          "sha512": "6de8f335e5a4e0883156c51d17d6d84946e7b7b3e23cb5534e89259ce2d9f5aefbf4b19e970eff391e33071a848667bf10825fd0a2a2c3afaab584de93cc8199",
          "sha256": "edb0f014f07cc9e95f0ca35066ead832d48728b762ad792bafdfa715c5f4b429",
          "sha1": "a529ac22cca28214b7dccf8d11288be8cc0708f9",
          "md5": "351b949f988b50b0ebc7feb0ec632e62"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-external-protobuf-1.1.0-rc01-sources.jar",
          "url": "glance-appwidget-external-protobuf-1.1.0-rc01-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-appwidget-external-protobuf is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-external-protobuf-1.1.0-rc01-versionMetadata.json",
          "url": "glance-appwidget-external-protobuf-1.1.0-rc01-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}