{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-core",
    "version": "1.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-core-1.4.0-beta01-sources.jar",
          "url": "camera-core-1.4.0-beta01-sources.jar",
          "size": 660746,
          "sha512": "2d4846d11d5e0dd7aecfa62064dbab6d7603a33d9417bb525bf0b9f274de901e841f356f4c3dd2de446ae2e29e2f6ba78522937e89f5d83f175adbc5a310651e",
          "sha256": "3d0415941d7689e86ebb6c37400041505cdf3350bc752a1b829aec41458ea57b",
          "sha1": "1e1a7d60ba00855c4e0a406d506363658e1b7e4d",
          "md5": "0e1f9334d9f5a4f30f80f4df21b3a0c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-core-1.4.0-beta01.aar",
          "url": "camera-core-1.4.0-beta01.aar",
          "size": 871403,
          "sha512": "758a9c1a691297a5102100d9ab76cb2a206a8ec8646fdff2bc0e26b2844a238001ea7a323cc501dd1363b619931a8acec9a53cad2b30dd7f5c6275975581302d",
          "sha256": "e139c65d07c83528b49488e6cb3fbe762a099069ae848af6ae9b973322cef5fe",
          "sha1": "80eb8839c0b838e6bd5d9de199660903d930dafa",
          "md5": "21969ce7b922e3c66446c659ab892881"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-core-1.4.0-beta01.aar",
          "url": "camera-core-1.4.0-beta01.aar",
          "size": 871403,
          "sha512": "758a9c1a691297a5102100d9ab76cb2a206a8ec8646fdff2bc0e26b2844a238001ea7a323cc501dd1363b619931a8acec9a53cad2b30dd7f5c6275975581302d",
          "sha256": "e139c65d07c83528b49488e6cb3fbe762a099069ae848af6ae9b973322cef5fe",
          "sha1": "80eb8839c0b838e6bd5d9de199660903d930dafa",
          "md5": "21969ce7b922e3c66446c659ab892881"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-core-1.4.0-beta01-versionMetadata.json",
          "url": "camera-core-1.4.0-beta01-versionMetadata.json",
          "size": 38684,
          "sha512": "630c0da94a9de8377bff5862ccba9023cb9cc9b6a573eca744daaca2bfe8f58cd4b216a159e542d9902011e0833ca7a5f5ef1ac320138630c60133a81dd303f8",
          "sha256": "f4362cdae347354d2e10b48a01fd33a99c82a4dd9c6aedf68f1a436ef396e6aa",
          "sha1": "a4c3fa677987e8051f4943cbc07dd0fb58892b43",
          "md5": "79770c9c9e8a51a7dad65710f36cbd61"
        }
      ]
    }
  ]
}