{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.credentials",
    "module": "credentials",
    "version": "1.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        },
        {
          "group": "androidx.credentials",
          "module": "credentials-e2ee",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.3.0-alpha01.aar",
          "url": "credentials-1.3.0-alpha01.aar",
          "size": 473236,
          "sha512": "35d5f62687639eeb73b7625a4ffa727f6b98b5ddc4bb4be92febca30f239d64a82d3084be9c8908c3dc4a7a67f9dedd11305798019a53e2c8ea009d4a8e017d9",
          "sha256": "af566a829cb6cbec8ff65f469c4bc5ff3b8edf37da6de7197e460f28bf93994f",
          "sha1": "9d686ee90ea9be42fd03c257b9f7208f4473f94e",
          "md5": "424c0e34d7f0f86422bceb8d536b9242"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        },
        {
          "group": "androidx.credentials",
          "module": "credentials-e2ee",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.3.0-alpha01.aar",
          "url": "credentials-1.3.0-alpha01.aar",
          "size": 473236,
          "sha512": "35d5f62687639eeb73b7625a4ffa727f6b98b5ddc4bb4be92febca30f239d64a82d3084be9c8908c3dc4a7a67f9dedd11305798019a53e2c8ea009d4a8e017d9",
          "sha256": "af566a829cb6cbec8ff65f469c4bc5ff3b8edf37da6de7197e460f28bf93994f",
          "sha1": "9d686ee90ea9be42fd03c257b9f7208f4473f94e",
          "md5": "424c0e34d7f0f86422bceb8d536b9242"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        },
        {
          "group": "androidx.credentials",
          "module": "credentials-e2ee",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.3.0-alpha01-sources.jar",
          "url": "credentials-1.3.0-alpha01-sources.jar",
          "size": 192570,
          "sha512": "d777546406cdfaaec35d5cd74e4e99080b9da11d9ef7192ce460c8e41c404d8cf8f19cde9e9d5e70c320d3dcd926cb02d08ffd3c9af2b4fb66b2744fbf6a64ef",
          "sha256": "4fe851851cd3d6fdc0ec5200916d9c7a20ad875a1e593d44d0895012eef0f1ac",
          "sha1": "ffc0f9e52881c3a472eaf44c140d73832632d98b",
          "md5": "ed27fa5e91202bbc82fbe98d4e3ce8ef"
        },
        {
          "name": "credentials-1.3.0-alpha01-samples-sources.jar",
          "url": "credentials-1.3.0-alpha01-samples-sources.jar",
          "size": 3043,
          "sha512": "42b75313f22875e1125c05f980313cec2cadb87cf4827e409add2ac2a75df707159fd3cd86be8c393cd2497ce9ebacccd34f9e9fd32c12c4bc0a5b961345733a",
          "sha256": "6dedd8c2da434280f212c5340b6154cd5cf9b0cc2ff3b701a606b660600e124f",
          "sha1": "614cfb5186c8123bff53b0acc66fe0b1ee9c6fa2",
          "md5": "de4849b9e3248c4a74b26628681bde78"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        },
        {
          "group": "androidx.credentials",
          "module": "credentials-e2ee",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.3.0-alpha01-versionMetadata.json",
          "url": "credentials-1.3.0-alpha01-versionMetadata.json",
          "size": 55900,
          "sha512": "cbb16d42f527029ae26d1d5559eb2f5f9b8462fdea0ceaf481d50d4c30871e2e0e8ba4d44352b927f57f768b6d2216690b91bcd988f9d8f0b37d98d154ac5c00",
          "sha256": "ac82098d09a37101a90b3947a11d84267eba39cebbc027e102ae60eabbaa8db4",
          "sha1": "876fa6c2a5653b574255f8d0490a697d5a05e838",
          "md5": "34740dc5c9d1a634706cbad51e11820d"
        }
      ]
    }
  ]
}