{
  "formatVersion": "1.1",
  "component": {
    "url": "../../datastore-core-okio/1.1.0-beta01/datastore-core-okio-1.1.0-beta01.module",
    "group": "androidx.datastore",
    "module": "datastore-core-okio",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-core-okio-jvm-1.1.0-beta01.jar",
          "url": "datastore-core-okio-jvm-1.1.0-beta01.jar",
          "size": 29754,
          "sha512": "234cc0c05814d0a1e498b3f804f174f6e6e348b79fc1d928b3e14876b7f40595dc7d99bf94a769138d9319a66dfaa5dd57fb4ae0c60fc75c9c7a22dc0fe32f1d",
          "sha256": "5071d03c7be9555fd81e5bd522b490a06a89694e4b937f307da72bc74e33c34a",
          "sha1": "cba5887aaa9316d650b3ebc667243ed3a05f4407",
          "md5": "c4214b6a493c31b39ae96b5fae3791f4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-core-okio-jvm-1.1.0-beta01.jar",
          "url": "datastore-core-okio-jvm-1.1.0-beta01.jar",
          "size": 29754,
          "sha512": "234cc0c05814d0a1e498b3f804f174f6e6e348b79fc1d928b3e14876b7f40595dc7d99bf94a769138d9319a66dfaa5dd57fb4ae0c60fc75c9c7a22dc0fe32f1d",
          "sha256": "5071d03c7be9555fd81e5bd522b490a06a89694e4b937f307da72bc74e33c34a",
          "sha1": "cba5887aaa9316d650b3ebc667243ed3a05f4407",
          "md5": "c4214b6a493c31b39ae96b5fae3791f4"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-core-okio-jvm-1.1.0-beta01-sources.jar",
          "url": "datastore-core-okio-jvm-1.1.0-beta01-sources.jar",
          "size": 6708,
          "sha512": "77f8a07c493d191f4f994176bffa618e25da8d10927a1f5b376e6a08abec671566faaedf18600b561cf29e55a29c20fa5db21659f0fde96e51bdd43ba73f8599",
          "sha256": "68b84f7449303e003d879bc383d6841a9df5a213cc33d4cd7fcda69d3bac1753",
          "sha1": "72e3c5daa01d155d3303703846a22d72a3e31eb9",
          "md5": "d43f8f8b5b60751b205250cdcedddae8"
        }
      ]
    }
  ]
}