{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-geometry/1.7.0-alpha03/ui-geometry-1.7.0-alpha03.module",
    "group": "androidx.compose.ui",
    "module": "ui-geometry",
    "version": "1.7.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-geometry-release.aar",
          "url": "ui-geometry-android-1.7.0-alpha03.aar",
          "size": 40533,
          "sha512": "27eb0643bcf1a6fe5f313806dac894861c07630709ab8f424d4375eaabc584b3672cf4764252942beadaacba15e36500e19687a35a64913046a965d90a0146ff",
          "sha256": "0a85d5a2e0e727e91197a3b595394b4bb56b52279baa244483cb43872fcd75e9",
          "sha1": "8a2d5051625bb30986636b4f002f68587e6b26b6",
          "md5": "1dfd17b85972495fe594e5727d3af08a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-geometry-release.aar",
          "url": "ui-geometry-android-1.7.0-alpha03.aar",
          "size": 40533,
          "sha512": "27eb0643bcf1a6fe5f313806dac894861c07630709ab8f424d4375eaabc584b3672cf4764252942beadaacba15e36500e19687a35a64913046a965d90a0146ff",
          "sha256": "0a85d5a2e0e727e91197a3b595394b4bb56b52279baa244483cb43872fcd75e9",
          "sha1": "8a2d5051625bb30986636b4f002f68587e6b26b6",
          "md5": "1dfd17b85972495fe594e5727d3af08a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-geometry-android-1.7.0-alpha03-sources.jar",
          "url": "ui-geometry-android-1.7.0-alpha03-sources.jar",
          "size": 19715,
          "sha512": "57782169cfd785740e1d22efc1a765537658a1e5f2d8a5d703e4afbd96e4968d78a40ae2bdd5377d5ae78f1ef6a932b000516fab28a8832d495a4b54c25a2695",
          "sha256": "bba924487ab26a20f986b90c75b495247a7771da6683207d82ebc4f399295f7f",
          "sha1": "c344e8696688e9e536844d94fa9272a5ef18d329",
          "md5": "38f1c60622f6cd70f99df0dc8e9e279e"
        }
      ]
    }
  ]
}