{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.watchface",
    "module": "watchface-complications-data-source",
    "version": "1.3.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-complications-data-source-1.3.0-alpha03-sources.jar",
          "url": "watchface-complications-data-source-1.3.0-alpha03-sources.jar",
          "size": 14910,
          "sha512": "00fc17f3b7cf4a681556437702331005ad15a78e7545d3b4d4f6d7e58816a31712c2516ee76a88cbef23aaf512b6e175bc290bfc39bd49176d867e912939a94b",
          "sha256": "14305ebc82d8e4ab27240b4142664fb5546cdce6cbcbbe76b06394bb4a0e0ad6",
          "sha1": "a9014dbf2fb13f3c177d49962825138fc553590e",
          "md5": "23e1feba51c1ab3cac4c1d6621bd8342"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-complications-data-source-1.3.0-alpha03.aar",
          "url": "watchface-complications-data-source-1.3.0-alpha03.aar",
          "size": 30926,
          "sha512": "aa0a8d8e96ca170fa7bcff141fd115c48842c30522037bf6af6d89b3e19977ed2e954d2dd9e8e422a45e67d4353945982646bc8c3bb0a6ff2fd1282ffe18aae6",
          "sha256": "39d7342a15379c62d9115e4ce3f9e04a31df5a56c7eaed9212ca5b35fee1040f",
          "sha1": "0470c69af8a9180dd838cb9cf4ba4a269e80890b",
          "md5": "5eadf1ec7555d2277e455e47c24b997f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-complications-data-source-1.3.0-alpha03.aar",
          "url": "watchface-complications-data-source-1.3.0-alpha03.aar",
          "size": 30926,
          "sha512": "aa0a8d8e96ca170fa7bcff141fd115c48842c30522037bf6af6d89b3e19977ed2e954d2dd9e8e422a45e67d4353945982646bc8c3bb0a6ff2fd1282ffe18aae6",
          "sha256": "39d7342a15379c62d9115e4ce3f9e04a31df5a56c7eaed9212ca5b35fee1040f",
          "sha1": "0470c69af8a9180dd838cb9cf4ba4a269e80890b",
          "md5": "5eadf1ec7555d2277e455e47c24b997f"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-complications-data-source-1.3.0-alpha03-versionMetadata.json",
          "url": "watchface-complications-data-source-1.3.0-alpha03-versionMetadata.json",
          "size": 5585,
          "sha512": "be64f217835c4a4ca93c3abe14c3f45a6c83eab9eefe9ca49ab2c50dbe87a7237688857503be927ed3fa2790238f22baa2235b65c6e1be940ff64abb7a108026",
          "sha256": "abb6254ffbffc5bc3196e6312ddc9152b574741d1c052258dfb58e7d6d5e911b",
          "sha1": "caaba016efa560718f6c6c6697a5ac871e6e3d52",
          "md5": "687b449d5f3db2a7efbc527987167c6f"
        }
      ]
    }
  ]
}