{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/1.7.0-alpha03/runtime-1.7.0-alpha03.module",
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.7.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-release.aar",
          "url": "runtime-android-1.7.0-alpha03.aar",
          "size": 2455058,
          "sha512": "8594fab7f59360dcd6817c66acc5b1c0f65adae2b8bbbc0f6c50bf7c9a49b82a1ef672bfd85c7a0418c66dbb263c3afd2169b74f42ec1df770a2490c87f6a7dd",
          "sha256": "832da5a6bcdcf479f517063349ed1e9902803df3a5ae1148bfe7acaffbca85f4",
          "sha1": "eddb07c7cfd806283e0b0f64f4d64c358a777672",
          "md5": "a14116388c57b9ffb32b6cf9e2e163ce"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-release.aar",
          "url": "runtime-android-1.7.0-alpha03.aar",
          "size": 2455058,
          "sha512": "8594fab7f59360dcd6817c66acc5b1c0f65adae2b8bbbc0f6c50bf7c9a49b82a1ef672bfd85c7a0418c66dbb263c3afd2169b74f42ec1df770a2490c87f6a7dd",
          "sha256": "832da5a6bcdcf479f517063349ed1e9902803df3a5ae1148bfe7acaffbca85f4",
          "sha1": "eddb07c7cfd806283e0b0f64f4d64c358a777672",
          "md5": "a14116388c57b9ffb32b6cf9e2e163ce"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-android-1.7.0-alpha03-sources.jar",
          "url": "runtime-android-1.7.0-alpha03-sources.jar",
          "size": 373454,
          "sha512": "43c21eeab5f21a3c768423ea84bb6fc3753e215db455fb0739640454c9431b9bb5b7f2456a9b75c6d294212321ae9fa586cb1cec53d06b455358b948d040d730",
          "sha256": "a7930e01e9b0720f0050967ef0c02e492ec3bbfca58255935df809fb428951a5",
          "sha1": "5ebe81d87d1782e8291879a743aeee654d7154ed",
          "md5": "f6b856e6fea211dfb620380ab0043834"
        }
      ]
    }
  ]
}