{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material",
    "version": "1.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.4.0-alpha03.aar",
          "url": "compose-material-1.4.0-alpha03.aar",
          "size": 1188776,
          "sha512": "ef474d43031d77dcdc22947dda3dc1cfc96f6892bdec824cbd0618bc5cb2bc7ff79a84808e04436a340d3846a689804ad64fb0f84e037f9275c4d1769d6da365",
          "sha256": "d77ca9ccd4aa56e683150d83b18ee2661198a80243f9d1a5882f5ce632e3de42",
          "sha1": "6730c33c692095da7f30c06154ce8552ef604e5d",
          "md5": "2380b8064f7c6286c04d4ad117f06385"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.4.0-alpha03.aar",
          "url": "compose-material-1.4.0-alpha03.aar",
          "size": 1188776,
          "sha512": "ef474d43031d77dcdc22947dda3dc1cfc96f6892bdec824cbd0618bc5cb2bc7ff79a84808e04436a340d3846a689804ad64fb0f84e037f9275c4d1769d6da365",
          "sha256": "d77ca9ccd4aa56e683150d83b18ee2661198a80243f9d1a5882f5ce632e3de42",
          "sha1": "6730c33c692095da7f30c06154ce8552ef604e5d",
          "md5": "2380b8064f7c6286c04d4ad117f06385"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.4.0-alpha03-sources.jar",
          "url": "compose-material-1.4.0-alpha03-sources.jar",
          "size": 172593,
          "sha512": "6cb89f3580b413e1b059ee11c74863d980645b6e2e44491007ac4297cf181447473a92afabc77cbdbbda786984fb416bf3cc8392172e3aef0ee6dcd8631bda34",
          "sha256": "f91997d161eb93849a760d19a6b23d70ed35efcb1c6819f7f9f9b044a7f44616",
          "sha1": "667b5c9c9fd5f25727ba9025505ac4846bc25cee",
          "md5": "68fbbe236e610d01315e73e2cdc5d12f"
        },
        {
          "name": "compose-material-1.4.0-alpha03-samples-sources.jar",
          "url": "compose-material-1.4.0-alpha03-samples-sources.jar",
          "size": 30732,
          "sha512": "cb1bf53247ed5e4d674ec60d7d5222bde75511e1a57fea9fd9d63ec95f97025f946dde5c28958bd4c46031bee4245abef83dcbc9a69c1160f22c50632a30a55e",
          "sha256": "ed1d70372861334ef1f7308d67fc09a3989ba7fbd3152f446e75e14ed970da07",
          "sha1": "f827b24338bc3b19529a395063a9d4343c01908e",
          "md5": "8ac94f65e1b67841a4e2c4bc0c8c3193"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.4.0-alpha03-versionMetadata.json",
          "url": "compose-material-1.4.0-alpha03-versionMetadata.json",
          "size": 78236,
          "sha512": "d79ec68fbb00fbf84fb08f56859282c68bed2c2bb985b9b7daf7d53cea9feb44abf76618c4e32f3cd51b64ea1847d66a151c4cae5618277062c578bcb17ce09c",
          "sha256": "b55644dd8717a705ee7b5e0d2bf2c05abe33d47e882baa04a2f2487f98655d82",
          "sha1": "b43d25d9aee00cb3fd65cb7578bd44d1b56513e2",
          "md5": "5558e227154d7b89daa54b8a7985a1a6"
        }
      ]
    }
  ]
}