{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment-testing-manifest",
    "version": "1.8.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-testing-manifest-1.8.0-rc01-sources.jar",
          "url": "fragment-testing-manifest-1.8.0-rc01-sources.jar",
          "size": 2843,
          "sha512": "4866b0201267f549eedd53088aa5673a2788482bba4e379896db48320a3ac45203dc808d765f1645790b8f1eb6e907a30d41da5951e0304f1614ed83fa527013",
          "sha256": "cfae9ebb6c64fa6ee3ca99d1afef2752003e395ef5ff2403aa2ad05b240f2437",
          "sha1": "cb021f9608c376403662786625af7fea6ade42bd",
          "md5": "0656cd9a98dd43e7f18724b111958ddc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-testing-manifest-1.8.0-rc01.aar",
          "url": "fragment-testing-manifest-1.8.0-rc01.aar",
          "size": 17405,
          "sha512": "fe599c51c9de571ef96ee998bf78568e176812736cdc43ce59ce3d8d952913f06b6cfc20cdec6484da1f01eecde20c8eff85ba56cd8c9523b8cfab14535e3e8a",
          "sha256": "60a1423cbe08abe1045edd56ef788d9317a897f91ea434eba63151005ca2aff3",
          "sha1": "7a03264f3176323f67dbf724ea501cf85bf2deb3",
          "md5": "a147834af6abb654c743b483356e12b6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-testing-manifest-1.8.0-rc01.aar",
          "url": "fragment-testing-manifest-1.8.0-rc01.aar",
          "size": 17405,
          "sha512": "fe599c51c9de571ef96ee998bf78568e176812736cdc43ce59ce3d8d952913f06b6cfc20cdec6484da1f01eecde20c8eff85ba56cd8c9523b8cfab14535e3e8a",
          "sha256": "60a1423cbe08abe1045edd56ef788d9317a897f91ea434eba63151005ca2aff3",
          "sha1": "7a03264f3176323f67dbf724ea501cf85bf2deb3",
          "md5": "a147834af6abb654c743b483356e12b6"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-testing-manifest-1.8.0-rc01-versionMetadata.json",
          "url": "fragment-testing-manifest-1.8.0-rc01-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}