{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.credentials",
    "module": "credentials",
    "version": "1.3.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.3.0-beta02-sources.jar",
          "url": "credentials-1.3.0-beta02-sources.jar",
          "size": 192012,
          "sha512": "116048f3e6456a4ab33843309f5df71d74630f6390cfa614e200a8bba14be00589474ebeff32449b04987e65611e935add63ed99fcbf4ef1e5dfebcef5c7dd09",
          "sha256": "e4350847b6cbb1d9fbb91325efff4c17b54b8426416e428b7082d29b31fa3e6a",
          "sha1": "3c0c5775c6e7397f5dea80d2047f1e776cc1784b",
          "md5": "52d7306da8cd43cdca587a7095234a2e"
        },
        {
          "name": "credentials-1.3.0-beta02-samples-sources.jar",
          "url": "credentials-1.3.0-beta02-samples-sources.jar",
          "size": 3052,
          "sha512": "8eb0fe19576ed82b8b83e1bb9454118855299a4af135f712bb2f2bb603ac926f196cedc4ce02dd42ba50451ecedf85ee025116f23aea0f10c1e89c747bc38f73",
          "sha256": "f14c6718dd7875b57b6574764ecea6578e7499ef0947e68c4c0c0351090e06e7",
          "sha1": "25fa17cd07e6dd3891f4ed32226bb478c2a7371f",
          "md5": "2769c616cb7fd20c7f7cb3b039de01ed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.3.0-beta02.aar",
          "url": "credentials-1.3.0-beta02.aar",
          "size": 451327,
          "sha512": "eb93777c2464b235123be9fc7928878cbefde381a28ace8f91572213afb12362fa9b808a1363247793d86aabde9a4466b745187b4d06f3d8a876df7e146e8b45",
          "sha256": "c68ab53c2b58b87ae793b6c6d0a304787f6ea5d37bc829e28fb731375a00ce38",
          "sha1": "4b35f5e3f5c403392db60148f2c241199b792447",
          "md5": "a58eeeccdd3b7c456d177ce3de05d78e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.3.0-beta02.aar",
          "url": "credentials-1.3.0-beta02.aar",
          "size": 451327,
          "sha512": "eb93777c2464b235123be9fc7928878cbefde381a28ace8f91572213afb12362fa9b808a1363247793d86aabde9a4466b745187b4d06f3d8a876df7e146e8b45",
          "sha256": "c68ab53c2b58b87ae793b6c6d0a304787f6ea5d37bc829e28fb731375a00ce38",
          "sha1": "4b35f5e3f5c403392db60148f2c241199b792447",
          "md5": "a58eeeccdd3b7c456d177ce3de05d78e"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.3.0-beta02-versionMetadata.json",
          "url": "credentials-1.3.0-beta02-versionMetadata.json",
          "size": 55577,
          "sha512": "addaca11f2bf6af070b61264d2b25a14e94cde4d7649fd5b7cdffbbddf46a3f2f17a93f79570c66a19ddd35195e45266f9a6d6f94e9fd24a05398a4fd9933bc6",
          "sha256": "48a0abed8ab57e5ec6628473842a65140577a027e42b48f494d61a7058f2726b",
          "sha1": "1137e4d4c35a3a3869bd5fd5bfcb0f11a0199062",
          "md5": "05c18df515ad12913e0d28e4533dca56"
        }
      ]
    }
  ]
}