{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.graphics",
    "module": "graphics-path",
    "version": "1.0.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphics-path-1.0.0-rc01-sources.jar",
          "url": "graphics-path-1.0.0-rc01-sources.jar",
          "size": 9881,
          "sha512": "7d376c78fbd6f51a68bfa24cb0f0a2fbb7f9209e54d48815f92b0f2bfa95ffdb46c29f59642cd144278c56769d649d6811a1d44826794531dcfa61a78166f01b",
          "sha256": "5cf80c494e1f2b044f579fb321b410ed63490ca3752588f87d71b491148c495d",
          "sha1": "40948c0c44c7ea9bb20c5fd6c1a095567902623f",
          "md5": "2cb031f7503fa70df01519b72e976312"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "graphics-path-1.0.0-rc01.aar",
          "url": "graphics-path-1.0.0-rc01.aar",
          "size": 38444,
          "sha512": "1a0ba69097eeafca540a72810856142c5a80175fa7b5ce84df6d1d5f59afc07851b41db25140ba3100d2283327339dfeba1b78e101d8283a5549735f77a9e693",
          "sha256": "3802097fa67366d0f77282a92602c7a61369d5240c00413c502fa72d2d26c135",
          "sha1": "dd3b00b51ebf6cd9fb7c07ee678d92a2f37ca28f",
          "md5": "30db00640a9d51b80860f5f74023dde3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "graphics-path-1.0.0-rc01.aar",
          "url": "graphics-path-1.0.0-rc01.aar",
          "size": 38444,
          "sha512": "1a0ba69097eeafca540a72810856142c5a80175fa7b5ce84df6d1d5f59afc07851b41db25140ba3100d2283327339dfeba1b78e101d8283a5549735f77a9e693",
          "sha256": "3802097fa67366d0f77282a92602c7a61369d5240c00413c502fa72d2d26c135",
          "sha1": "dd3b00b51ebf6cd9fb7c07ee678d92a2f37ca28f",
          "md5": "30db00640a9d51b80860f5f74023dde3"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "graphics-path-1.0.0-rc01-versionMetadata.json",
          "url": "graphics-path-1.0.0-rc01-versionMetadata.json",
          "size": 2212,
          "sha512": "4a44b74f73f05bb9c6fb5d280ddd12ce3969c3154c01549401f9ac0510a60599cd6811736ce38575c3638889ff792d4ab2f7a07fbfb9bea436653bd6210df4d5",
          "sha256": "779fad06eed4b0f6e5599d2c10ddb7f4f9e108efe7bdbda188f3cc57af51c652",
          "sha1": "fa3b9994d08c26c853c4eaece1e90aae5e64c423",
          "md5": "18a9e34c156e110d08c1b63ae1079878"
        }
      ]
    }
  ]
}