{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.compiler",
    "module": "compiler",
    "version": "1.5.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.compiler",
          "module": "compiler-hosted",
          "version": {
            "requires": "1.5.11"
          },
          "reason": "compiler is in atomic group androidx.compose.compiler"
        }
      ],
      "files": [
        {
          "name": "compiler-1.5.11.jar",
          "url": "compiler-1.5.11.jar",
          "size": 1165794,
          "sha512": "c6e15d2a7aca962d6d90624ab9b09ae7b53d6adddc5c05cab5afd53aee56c8a51382e87a89ef151bcccdd2cff343257dfb24389a7b8fab1b1d0cf2f7464ffa75",
          "sha256": "4265b3a89350bceeb799ca6145f6bfc74765c2915a6fbde54fe3af2818b9219f",
          "sha1": "79106fe22d93f8e1df3aa87a815063a7519f1793",
          "md5": "679cb836409322853c684be7b88621e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.compiler",
          "module": "compiler-hosted",
          "version": {
            "requires": "1.5.11"
          },
          "reason": "compiler is in atomic group androidx.compose.compiler"
        }
      ],
      "files": [
        {
          "name": "compiler-1.5.11.jar",
          "url": "compiler-1.5.11.jar",
          "size": 1165794,
          "sha512": "c6e15d2a7aca962d6d90624ab9b09ae7b53d6adddc5c05cab5afd53aee56c8a51382e87a89ef151bcccdd2cff343257dfb24389a7b8fab1b1d0cf2f7464ffa75",
          "sha256": "4265b3a89350bceeb799ca6145f6bfc74765c2915a6fbde54fe3af2818b9219f",
          "sha1": "79106fe22d93f8e1df3aa87a815063a7519f1793",
          "md5": "679cb836409322853c684be7b88621e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.compiler",
          "module": "compiler-hosted",
          "version": {
            "requires": "1.5.11"
          },
          "reason": "compiler is in atomic group androidx.compose.compiler"
        }
      ],
      "files": [
        {
          "name": "compiler-1.5.11-sources.jar",
          "url": "compiler-1.5.11-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}