{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.datastore",
    "module": "datastore-rxjava2",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-rxjava2-1.2.0-alpha01-sources.jar",
          "url": "datastore-rxjava2-1.2.0-alpha01-sources.jar",
          "size": 9984,
          "sha512": "770cd75975222bce8a12b8248f8ab5e97e3ff9243be086597ad63f70693991ec82fb758fd382f217ca1f8718f9d1930995c65c46e9b14678196ef6c6e328c62e",
          "sha256": "f65bd67fcc876142b74897c33f2445548f2412667aea01a60da804eddcbc2e9c",
          "sha1": "79194e31aaeeac767fd2b6abbb50c972627abcd3",
          "md5": "713e581b5e9cf128242591c36d6f143f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-rxjava2-1.2.0-alpha01.aar",
          "url": "datastore-rxjava2-1.2.0-alpha01.aar",
          "size": 32985,
          "sha512": "287b61ad619d16e9b595b49ff1818005bcd8929023b454f55ac3499aa87f833eb4139ef913cb53e86f8b294bd07687643e1e3cc78800cbccb3f99b6d054cf0b8",
          "sha256": "444ba5e70d3d30675807c74a948ec29c787d357bc5cdce2188e7df1e01cc586b",
          "sha1": "d6a05dbca231ab5bee941236246597637e717c17",
          "md5": "0fef920bc8d23426fc2fac40d7df25f2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx2",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-rxjava2-1.2.0-alpha01.aar",
          "url": "datastore-rxjava2-1.2.0-alpha01.aar",
          "size": 32985,
          "sha512": "287b61ad619d16e9b595b49ff1818005bcd8929023b454f55ac3499aa87f833eb4139ef913cb53e86f8b294bd07687643e1e3cc78800cbccb3f99b6d054cf0b8",
          "sha256": "444ba5e70d3d30675807c74a948ec29c787d357bc5cdce2188e7df1e01cc586b",
          "sha1": "d6a05dbca231ab5bee941236246597637e717c17",
          "md5": "0fef920bc8d23426fc2fac40d7df25f2"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-rxjava2-1.2.0-alpha01-versionMetadata.json",
          "url": "datastore-rxjava2-1.2.0-alpha01-versionMetadata.json",
          "size": 2600,
          "sha512": "587fc068f07a13c9fe63dea78053f122a3c92b5f542be55c2e29d7baa1f97ca328c4d1509402b8060f5330856694d0242cf8add40f5b76a9c1a2d0e45e090d8b",
          "sha256": "0eef6b29cc9975ee6c63d7bda267a395592459ca208b40d1a69582a959b55c1f",
          "sha1": "cfe40ccb12724e00538a1bbd3ddf0fdb9a7fc471",
          "md5": "04240550696b0ddaa1db1f82d323d003"
        }
      ]
    }
  ]
}