version: "1.6.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.7.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.8.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.window"
group_id: "androidx.window"
artifact_id: "window-java"
path: "/window/window-java"
sha: "4450cde2839c586b9792c006d22c6b4fc7721c35"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.window-window-java-all-11954461-1.6.0-alpha01.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
  dependency {
    group_id: "androidx.window"
    artifact_id: "window"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window-core"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window-rxjava2"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window-rxjava3"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window-testing"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
