{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.watchface",
    "module": "watchface-complications-rendering",
    "version": "1.3.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-complications-rendering-1.3.0-alpha03-sources.jar",
          "url": "watchface-complications-rendering-1.3.0-alpha03-sources.jar",
          "size": 47745,
          "sha512": "8640c5925ab3665827fa61c9b3f1ee3cfea792caa3f05ce89cfda93858dabdf4cce1f3eaeed226131309cac189e18337db1357ffa0ead6064e994e89d604c014",
          "sha256": "daa5d51ecb24430fc73c5ca3810ecf8f1291f357fbe5168be1a40d2cf7c18913",
          "sha1": "6ba108eceaaf4669ea613dfd44c56b3009c37265",
          "md5": "47f93d90033135f8a092439dc4820fc7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-complications-rendering-1.3.0-alpha03.aar",
          "url": "watchface-complications-rendering-1.3.0-alpha03.aar",
          "size": 69304,
          "sha512": "7cfe40c9123bf7f8293cbbed3e790ebde16c75cbbc16ae946fba37ed06134e55a0b1e09288fe1b136da4529e06b2295bcbea5dfcd478b8b0a8dd512a89784349",
          "sha256": "ec19384bede6ca2af0d0d8705f573e22cadbb757793d5008da2c1fc667a17ad5",
          "sha1": "376c0a3cc7f014c0ed5185a8a88de7b152168e42",
          "md5": "6d5f7eaf8b35e9dbfb8c12c73806acaf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-complications-rendering-1.3.0-alpha03.aar",
          "url": "watchface-complications-rendering-1.3.0-alpha03.aar",
          "size": 69304,
          "sha512": "7cfe40c9123bf7f8293cbbed3e790ebde16c75cbbc16ae946fba37ed06134e55a0b1e09288fe1b136da4529e06b2295bcbea5dfcd478b8b0a8dd512a89784349",
          "sha256": "ec19384bede6ca2af0d0d8705f573e22cadbb757793d5008da2c1fc667a17ad5",
          "sha1": "376c0a3cc7f014c0ed5185a8a88de7b152168e42",
          "md5": "6d5f7eaf8b35e9dbfb8c12c73806acaf"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications-rendering is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-complications-rendering-1.3.0-alpha03-versionMetadata.json",
          "url": "watchface-complications-rendering-1.3.0-alpha03-versionMetadata.json",
          "size": 6807,
          "sha512": "0b25075ad3415c6393b6cd75cb210e2d08ec2e8d70177d8a882099958f1015e4892583465013236481421b87c5c7a9979231b53bf5470a339aa9c47d619a5a0d",
          "sha256": "1da864d8ae4b7dbcda1f4d53f7c1e73fe06676c6804e786f2d3cf185cbcec7e9",
          "sha1": "2fa39ed363519a09a322843bcce3478dd5018b8a",
          "md5": "68ec1327ed3629b4dbd195bd918a00b1"
        }
      ]
    }
  ]
}