{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-fragment-ktx",
    "version": "2.8.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "Mirror navigation-fragment dependency graph for -ktx artifacts"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-ktx-2.8.0-alpha03.aar",
          "url": "navigation-fragment-ktx-2.8.0-alpha03.aar",
          "size": 2155,
          "sha512": "46fcea27f530785a0f3c5459f105caaeb4680974991dac0dcbbd490e138c1d326bcf4e14d102ef5a5358cd716c55e556cc2d5a1a130c2e80b019862741842b29",
          "sha256": "51cd09ebf0584cfe78decd91ce7db37264c701fa793bc2924718db89f7429584",
          "sha1": "0701d2a7b94cc70c598857851ab2c2ea1178a9a6",
          "md5": "e000f4dd6efc5c071092301c40bc48cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "Mirror navigation-fragment dependency graph for -ktx artifacts"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-ktx-2.8.0-alpha03.aar",
          "url": "navigation-fragment-ktx-2.8.0-alpha03.aar",
          "size": 2155,
          "sha512": "46fcea27f530785a0f3c5459f105caaeb4680974991dac0dcbbd490e138c1d326bcf4e14d102ef5a5358cd716c55e556cc2d5a1a130c2e80b019862741842b29",
          "sha256": "51cd09ebf0584cfe78decd91ce7db37264c701fa793bc2924718db89f7429584",
          "sha1": "0701d2a7b94cc70c598857851ab2c2ea1178a9a6",
          "md5": "e000f4dd6efc5c071092301c40bc48cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-ktx-2.8.0-alpha03-sources.jar",
          "url": "navigation-fragment-ktx-2.8.0-alpha03-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-ktx-2.8.0-alpha03-versionMetadata.json",
          "url": "navigation-fragment-ktx-2.8.0-alpha03-versionMetadata.json",
          "size": 3940,
          "sha512": "479e68a1bc895eedfc5a278ea3043cc0192449480b791c45eae572d25de8bf0e259c7b332476e8bd7948d0676af5f97af718bc34c4a2c7d358a38c51bd1311a7",
          "sha256": "b34485ebe0f3fee192573065288ea48db4c524e3a7be43a8cf51033b04306410",
          "sha1": "6da3af1a51cd71422c6413d6d81111ad5a108efb",
          "md5": "eab5779d224a2e384a04b72235fabb82"
        }
      ]
    }
  ]
}