version: "2.2.0-alpha13"
dependency_list {
  dependency {
    group_id: "androidx.appcompat"
    artifact_id: "appcompat"
    version: "1.2.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.constraintlayout"
    artifact_id: "constraintlayout-core"
    version: "1.1.0-alpha13"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.3.2"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.profileinstaller"
    artifact_id: "profileinstaller"
    version: "1.3.1"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.constraintlayout"
group_id: "androidx.constraintlayout"
artifact_id: "constraintlayout"
path: "/constraintlayout/constraintlayout"
sha: "3264c1f21ddfe2acf96a1d034f78367662cf9f65"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.constraintlayout-constraintlayout-all-11879057-2.2.0-alpha13.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
