{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-lifecycle",
    "version": "1.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.4.0-beta01-sources.jar",
          "url": "camera-lifecycle-1.4.0-beta01-sources.jar",
          "size": 20180,
          "sha512": "64be164c7e13f81fb269bf984adf3be26fa0835e402d7520a5fd581f556a3e1be73fe81e73ac9eba559187742d984aceaa73cceae1ab74efc20c1957c5b3c403",
          "sha256": "6ce8b455cbc7133e5775835380f4a25c8e44f59cbff199af3a9388eff1f5feb7",
          "sha1": "7e02df7e06e465d0b965a80915658f056cbf42a4",
          "md5": "94e75e103c2d49a571aba5205d479175"
        },
        {
          "name": "camera-lifecycle-1.4.0-beta01-samples-sources.jar",
          "url": "camera-lifecycle-1.4.0-beta01-samples-sources.jar",
          "size": 2292,
          "sha512": "f0f2192c568215248ba35d7ea83155ef78516d83a38b4e4653ebc6465b96bd50c26290dfb123df6e68f4dd57fd24ac4d0778fa318a04beb09d46d62531e8220b",
          "sha256": "9934dcc215a6addfd5076cff534bac973739d6f3c5abe6c3855803851fcdb6a0",
          "sha1": "18cdbbce25772f68c1bc076686b7cb20727787d9",
          "md5": "34e18f1174a8e375d3dc0b2966369d5e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.4.0-beta01.aar",
          "url": "camera-lifecycle-1.4.0-beta01.aar",
          "size": 29736,
          "sha512": "1c69286cc1ff81dba9eded13d273df415de097a6805eb2407020830c15146ca6ef425fed49896b4256676f21a2945ad446215238e33fa5a78277fa6de41fa3f5",
          "sha256": "6babcb4a4762030181d1111337d4ebc7d4c3804bf86202c0db4a7a3055476432",
          "sha1": "2d2bb23dd514bf2684b4f67d3edb7ac1211c66ad",
          "md5": "39df769cb499632562e87c27236413d7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.4.0-beta01.aar",
          "url": "camera-lifecycle-1.4.0-beta01.aar",
          "size": 29736,
          "sha512": "1c69286cc1ff81dba9eded13d273df415de097a6805eb2407020830c15146ca6ef425fed49896b4256676f21a2945ad446215238e33fa5a78277fa6de41fa3f5",
          "sha256": "6babcb4a4762030181d1111337d4ebc7d4c3804bf86202c0db4a7a3055476432",
          "sha1": "2d2bb23dd514bf2684b4f67d3edb7ac1211c66ad",
          "md5": "39df769cb499632562e87c27236413d7"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.4.0-beta01-versionMetadata.json",
          "url": "camera-lifecycle-1.4.0-beta01-versionMetadata.json",
          "size": 2081,
          "sha512": "8149d8909245a4ec3a20e92e5e040fd9803c04744acfc7efaeed28ad2fc29d70df11e05608a607d38e0dd1d222ec62660eb37891718a1b7ffa244b2e4fba4537",
          "sha256": "8ef1b29a8b6f8f14f70d649ae257e1818d468403c70d0f0bfa05a3d9f811529a",
          "sha1": "4c35f1bde81d7c1a08118bd3598d18b75782c0f9",
          "md5": "85e83872dfc7751efef988a126e4c4b1"
        }
      ]
    }
  ]
}