{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.protolayout",
    "module": "protolayout-external-protobuf",
    "version": "1.2.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-external-protobuf-1.2.0-alpha04.jar",
          "url": "protolayout-external-protobuf-1.2.0-alpha04.jar",
          "size": 705876,
          "sha512": "2ec5d5785920057d8c7ee9e980f97e4928b3575ce5e684064fcc9f0c9103459de54a22616e6ef630e24576546fee0441018a21e3024f591720cb23468ac335bf",
          "sha256": "8cd8853bfb5d1bd581d0fd45917bc9910a2ba62ac56c42bb0cad34c6ce336cdf",
          "sha1": "bf16dad8a850886a1519e9da318963b2e7700ec5",
          "md5": "4258e02042765b621b686f4caa17f009"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-external-protobuf-1.2.0-alpha04.jar",
          "url": "protolayout-external-protobuf-1.2.0-alpha04.jar",
          "size": 705876,
          "sha512": "2ec5d5785920057d8c7ee9e980f97e4928b3575ce5e684064fcc9f0c9103459de54a22616e6ef630e24576546fee0441018a21e3024f591720cb23468ac335bf",
          "sha256": "8cd8853bfb5d1bd581d0fd45917bc9910a2ba62ac56c42bb0cad34c6ce336cdf",
          "sha1": "bf16dad8a850886a1519e9da318963b2e7700ec5",
          "md5": "4258e02042765b621b686f4caa17f009"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-external-protobuf-1.2.0-alpha04-sources.jar",
          "url": "protolayout-external-protobuf-1.2.0-alpha04-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-external-protobuf is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-external-protobuf-1.2.0-alpha04-versionMetadata.json",
          "url": "protolayout-external-protobuf-1.2.0-alpha04-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}