version: "1.7.0-beta01"
dependency_list {
  dependency {
    group_id: "androidx.activity"
    artifact_id: "activity"
    version: "1.8.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.1.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-experimental"
    version: "1.4.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection"
    version: "1.1.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core-ktx"
    version: "1.2.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-livedata-core"
    version: "2.6.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-runtime"
    version: "2.6.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-viewmodel"
    version: "2.6.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-viewmodel-savedstate"
    version: "2.6.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.loader"
    artifact_id: "loader"
    version: "1.0.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.profileinstaller"
    artifact_id: "profileinstaller"
    version: "1.3.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate"
    version: "1.2.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.viewpager"
    artifact_id: "viewpager"
    version: "1.0.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.fragment"
group_id: "androidx.fragment"
artifact_id: "fragment"
path: "/fragment/fragment"
sha: "2b2e31535335d12b762d56d14e252c05c6b542e6"
require_same_version_group_build: true
group_zip_path: "per-group-zips/gmaven-androidx-fragment-11497185.zip"
project_zip_path: "per-project-zips/androidx.fragment-fragment-all-11497185-1.7.0-beta01.zip"
kotlin_version: "1.9.22"
dependency_constraint_list {
  dependency {
    group_id: "androidx.fragment"
    artifact_id: "fragment-compose"
    version: "1.7.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.fragment"
    artifact_id: "fragment-ktx"
    version: "1.7.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.fragment"
    artifact_id: "fragment-testing"
    version: "1.7.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.fragment"
    artifact_id: "fragment-testing-manifest"
    version: "1.7.0-beta01"
    is_tip_of_tree: true
  }
}
