{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment",
    "version": "1.7.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.loader",
          "module": "loader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.7.0-beta01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.0-beta01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.7.0-beta01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.7.0-beta01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-1.7.0-beta01.aar",
          "url": "fragment-1.7.0-beta01.aar",
          "size": 380891,
          "sha512": "29f0710ab28215d9759a5e8f9daf2a258791eb9cf3611c01dcba2acbbaa86912d8a3b91f474e29e9155142aceb1ae8609780c94eb1ce5c460d677d570b3d8785",
          "sha256": "044d421a431fd00732c867b4839d729189917cd0708c4feab1f5c555dd1166e3",
          "sha1": "0d5e6afb5f60d0b756f949090d87a6f779101e45",
          "md5": "04d7158d7baadbb689274b474bae3cd9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.loader",
          "module": "loader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.7.0-beta01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.0-beta01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.7.0-beta01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.7.0-beta01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-1.7.0-beta01.aar",
          "url": "fragment-1.7.0-beta01.aar",
          "size": 380891,
          "sha512": "29f0710ab28215d9759a5e8f9daf2a258791eb9cf3611c01dcba2acbbaa86912d8a3b91f474e29e9155142aceb1ae8609780c94eb1ce5c460d677d570b3d8785",
          "sha256": "044d421a431fd00732c867b4839d729189917cd0708c4feab1f5c555dd1166e3",
          "sha1": "0d5e6afb5f60d0b756f949090d87a6f779101e45",
          "md5": "04d7158d7baadbb689274b474bae3cd9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.7.0-beta01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.0-beta01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.7.0-beta01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.7.0-beta01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-1.7.0-beta01-sources.jar",
          "url": "fragment-1.7.0-beta01-sources.jar",
          "size": 198780,
          "sha512": "150c40eb1cf3eb105b03332a59072b4d51ed6c1ab8c47c76e92206731a029c188e1b7067e22e962f8462e22a5325a730809bdacd238c4315b1e6c3343b8a7e4a",
          "sha256": "c96e350ed88594e9cc2a42d2ab253e3ac5dfac63b0489ae20ce68e40a456b92a",
          "sha1": "c16d89662259400f2cfdcab7994066459bc41238",
          "md5": "643b795b96fde5914d9826138b935d3e"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.7.0-beta01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.0-beta01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.7.0-beta01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.7.0-beta01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-1.7.0-beta01-versionMetadata.json",
          "url": "fragment-1.7.0-beta01-versionMetadata.json",
          "size": 37010,
          "sha512": "3495762e54ba3f059bb8ae943f336e5a384173f5a8de91d8285d6727b8454c04413706a48b546cd3573a947eb47aaac7d02a7b4bb9b7145a5c3f971b5e81de4a",
          "sha256": "ba65b5ddc9d2a47c05c183970b1f65144c2fe6f21f56b079900918d27085f5e3",
          "sha1": "622a06004928aabbf9eea648feb069ea43efe3aa",
          "md5": "80a5619acb43e943163c390c4535b514"
        }
      ]
    }
  ]
}