{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-ktx",
    "version": "2.9.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.9.0-alpha01-sources.jar",
          "url": "lifecycle-livedata-ktx-2.9.0-alpha01-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.9.0-alpha01.aar",
          "url": "lifecycle-livedata-ktx-2.9.0-alpha01.aar",
          "size": 1349,
          "sha512": "147db3e6cec056e0d8c5b7195696dfc44234304ff715b8d5641113935f55a84d0d0a7ee86b417d4f4b948c165ed03b84cf7c66f4959f60f4076a5cd43a376aa8",
          "sha256": "5d0025ea1f84b8d1caf13b7ba5ccfa52ad7e9ebdcd53fb4a2e73c86f2731abdc",
          "sha1": "6c87b00e3fc79a8d9878b856468dc54142816df2",
          "md5": "ac553cb467ffcab2d226ca48eb8b00f6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.9.0-alpha01.aar",
          "url": "lifecycle-livedata-ktx-2.9.0-alpha01.aar",
          "size": 1349,
          "sha512": "147db3e6cec056e0d8c5b7195696dfc44234304ff715b8d5641113935f55a84d0d0a7ee86b417d4f4b948c165ed03b84cf7c66f4959f60f4076a5cd43a376aa8",
          "sha256": "5d0025ea1f84b8d1caf13b7ba5ccfa52ad7e9ebdcd53fb4a2e73c86f2731abdc",
          "sha1": "6c87b00e3fc79a8d9878b856468dc54142816df2",
          "md5": "ac553cb467ffcab2d226ca48eb8b00f6"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "lifecycle-livedata-ktx is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.9.0-alpha01-versionMetadata.json",
          "url": "lifecycle-livedata-ktx-2.9.0-alpha01-versionMetadata.json",
          "size": 2097,
          "sha512": "14230a2f97721bb605b5a54bb36576da7600dfb4f4351253d0f5de2564f47f4e6ab1d7e542f2314ba6fbf22fe9b3f7daf2517dd726b7c323b98102a69758ca45",
          "sha256": "26f750bdf35afe0013268ff5b20b9c84d1e0346497042bdf3c7995db663c4d97",
          "sha1": "cf4e4f082641bd9284e3e3f22bed1e44974551f3",
          "md5": "c921c372c7db86aec6d7c04e905974d0"
        }
      ]
    }
  ]
}