{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.ui",
    "module": "ui-core",
    "version": "1.0.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-provider",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-core-1.0.0-alpha08-sources.jar",
          "url": "ui-core-1.0.0-alpha08-sources.jar",
          "size": 6320,
          "sha512": "fd42f5be4533ee9806e20667a8fdd859c2fd42cc1e180097c86978d443e356e4005252c96af5749d9cd95f4204569c9a663cb5d28400d159a8a13030b5fc1ad1",
          "sha256": "e277706835753f62033c3fce818b68ffbee707559ca29574ee3f4bd2cb04bef3",
          "sha1": "ccab06a950d185b6d5035bd22a8b44ca787510a3",
          "md5": "375604fa22876db4de6c073da9fe989e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-provider",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-core-1.0.0-alpha08.aar",
          "url": "ui-core-1.0.0-alpha08.aar",
          "size": 26515,
          "sha512": "2cab55c07efaa150bf6da9c4a9a899a1e784ad37e885aa7d0de3db829d25dca50975cc78813f58dff3c956b41800b6da81361e1f93bceeecc19e8ea4581f026f",
          "sha256": "e97fb086e6b8de8da755106f1b812641501fb0a47e49298d1f82e5cb4cf60dde",
          "sha1": "bf4ec1672e5bfccd5a3ce146764c7f9cd6607315",
          "md5": "cf8d250374250aab93048d756f013a05"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-provider",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-core-1.0.0-alpha08.aar",
          "url": "ui-core-1.0.0-alpha08.aar",
          "size": 26515,
          "sha512": "2cab55c07efaa150bf6da9c4a9a899a1e784ad37e885aa7d0de3db829d25dca50975cc78813f58dff3c956b41800b6da81361e1f93bceeecc19e8ea4581f026f",
          "sha256": "e97fb086e6b8de8da755106f1b812641501fb0a47e49298d1f82e5cb4cf60dde",
          "sha1": "bf4ec1672e5bfccd5a3ce146764c7f9cd6607315",
          "md5": "cf8d250374250aab93048d756f013a05"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-provider",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-core-1.0.0-alpha08-versionMetadata.json",
          "url": "ui-core-1.0.0-alpha08-versionMetadata.json",
          "size": 1733,
          "sha512": "ac1420315f815d74f07b28ea1ed017d3208b5c708b03d9bdb40870a45ead603995ef1f9ea6a80660f5429168efe2542068b286189503c7b66a0ee125ca7bcb71",
          "sha256": "0f214fe7a7f7a5177845d22a39bfbe7e320498148c7326798f2f80db84371729",
          "sha1": "7739ae9442c00b8b047351017dec169324b7332d",
          "md5": "b6102aa74725050012b45c6406f66d35"
        }
      ]
    }
  ]
}