{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.protolayout",
    "module": "protolayout-expression",
    "version": "1.2.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-1.2.0-alpha04-sources.jar",
          "url": "protolayout-expression-1.2.0-alpha04-sources.jar",
          "size": 60767,
          "sha512": "c1dff95cd88713143b18661f6c0221389bc6bec952e01acabe9de41ad7409ea453b86f548026fb4dd528137696dc60e77ad265ef7f1392beadfe68fa8e1791c0",
          "sha256": "4d4148e4ed1b794905fd7b25190fffa9ebf052b2379d190d94c9ea7987c6efd6",
          "sha1": "ba17396d323ce6b1ac82bf1f4316d5639b5974f8",
          "md5": "d075f819306435564e8e2e6fd31756f1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-1.2.0-alpha04.aar",
          "url": "protolayout-expression-1.2.0-alpha04.aar",
          "size": 222935,
          "sha512": "3eaad125744c4bd7f1957ae0058cb4427fa997a661be4a1148e1b25d7b6eab10c379c169a4280405f9d4d62305e64fa85025f8a351d4285a18083d7dd84a333c",
          "sha256": "38cf99ec532d607b808f1fd887c4383e7b4555434d9a1d8c1e99f2bd3a400a9f",
          "sha1": "eba43f644ef8c777c9a8ed979fefc81f4fce34a3",
          "md5": "6bccf68d6ed21af64c0932f4e366cf53"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-1.2.0-alpha04.aar",
          "url": "protolayout-expression-1.2.0-alpha04.aar",
          "size": 222935,
          "sha512": "3eaad125744c4bd7f1957ae0058cb4427fa997a661be4a1148e1b25d7b6eab10c379c169a4280405f9d4d62305e64fa85025f8a351d4285a18083d7dd84a333c",
          "sha256": "38cf99ec532d607b808f1fd887c4383e7b4555434d9a1d8c1e99f2bd3a400a9f",
          "sha1": "eba43f644ef8c777c9a8ed979fefc81f4fce34a3",
          "md5": "6bccf68d6ed21af64c0932f4e366cf53"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-1.2.0-alpha04-versionMetadata.json",
          "url": "protolayout-expression-1.2.0-alpha04-versionMetadata.json",
          "size": 24636,
          "sha512": "da90b4f957717eda17bc88ef21241444c764bd06209d6c6011f7986da72a4d1394c37d9a15360bc61d8cf9c40ea855f56a5ac4d94d62fbb3e21c5e3db560a3bf",
          "sha256": "379dc8dd2630fcbbb5e4ebe223137275246d59b5b4d383208b898baff417d9aa",
          "sha1": "2dee78167c1c574b78d1e6cebee042d8f9a7a555",
          "md5": "fb4cc049d52ea74109566a0f69f0804e"
        }
      ]
    }
  ]
}