{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.protolayout",
    "module": "protolayout-expression-pipeline",
    "version": "1.2.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-pipeline-1.2.0-alpha04-sources.jar",
          "url": "protolayout-expression-pipeline-1.2.0-alpha04-sources.jar",
          "size": 68433,
          "sha512": "7a869adddd652453e47335a83c12afb23db2bc520024fae11d609f2221a657b3e7478d4147a28c218869c5ad29abe67a51c4f242433ca5ec78cb0ea9ded6526c",
          "sha256": "549baee15ab94e1c214145fc2a1fad9f28db8bd48250fa14e339a35dd549e96a",
          "sha1": "b62f128d4e9d3b04ce86010cccf0925d7c49ca53",
          "md5": "f6b352db315cc0234a41103b8f67174d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-pipeline-1.2.0-alpha04.aar",
          "url": "protolayout-expression-pipeline-1.2.0-alpha04.aar",
          "size": 136241,
          "sha512": "99309d68ce312ff08aff5cbf20e3bb3ce6ce7b9bb70f4f8799e4a693cf5586957ac1815dc0f48ea0ade0943c0462222628d6264ba3eff4f51aa549a5ab0a6599",
          "sha256": "5315b315a31c0ae81805d951c596a6afabaff04086c46d59838b586a3a77a0f9",
          "sha1": "0fe1c0d5624a3f5e160062afa6aef29666c1efed",
          "md5": "d8ea81b6d1f33b0a0b78d926be586427"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-pipeline-1.2.0-alpha04.aar",
          "url": "protolayout-expression-pipeline-1.2.0-alpha04.aar",
          "size": 136241,
          "sha512": "99309d68ce312ff08aff5cbf20e3bb3ce6ce7b9bb70f4f8799e4a693cf5586957ac1815dc0f48ea0ade0943c0462222628d6264ba3eff4f51aa549a5ab0a6599",
          "sha256": "5315b315a31c0ae81805d951c596a6afabaff04086c46d59838b586a3a77a0f9",
          "sha1": "0fe1c0d5624a3f5e160062afa6aef29666c1efed",
          "md5": "d8ea81b6d1f33b0a0b78d926be586427"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0-alpha04"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-pipeline-1.2.0-alpha04-versionMetadata.json",
          "url": "protolayout-expression-pipeline-1.2.0-alpha04-versionMetadata.json",
          "size": 5880,
          "sha512": "df667da0f4f4a20ef6b0e37c5b451e643df20db9758e9367d48c97860240391032d861a79d2e04b66fe74d0fb434c4685b497e88ed4a1eaf594f392076ea88f3",
          "sha256": "cf451ddbde3d3cfc6be15431fba32dcbe514791fe8f6bdb79e6d35b65eb870d5",
          "sha1": "994f9f70fb804c19386d7fc7724e0cf1a70e9886",
          "md5": "796c75c8c38591dae19cd077d6067b5a"
        }
      ]
    }
  ]
}