version: "1.0.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.camera"
    artifact_id: "camera-viewfinder-core"
    version: "1.4.0-alpha06"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.foundation"
    artifact_id: "foundation"
    version: "1.6.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.compose.foundation"
    artifact_id: "foundation-layout"
    version: "1.6.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime"
    version: "1.6.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core-ktx"
    version: "1.12.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.camera"
group_id: "androidx.camera"
artifact_id: "camera-viewfinder-compose"
path: "/camera/camera-viewfinder-compose"
sha: "2defcd0b1304c392f511d8536e0582143b40edf5"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.camera-camera-viewfinder-compose-all-11904523-1.0.0-alpha01.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
