{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-viewfinder-compose",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-viewfinder-compose-1.0.0-alpha01-sources.jar",
          "url": "camera-viewfinder-compose-1.0.0-alpha01-sources.jar",
          "size": 12895,
          "sha512": "7eda2a19c5b8a103f2ec55c986a61fe98ea15f3aaa6ba2f730029d364a19a853b28ba11870005f319fb782390c1dd98a5c8ed304d817452238f8cadbf4b9da86",
          "sha256": "2498693b18d260d5a11e65b754553d83132370ff52eedf5361c72ed98fcaa5ed",
          "sha1": "2b0ef004e7e78dd43c430e77847dbef4e0c4dd09",
          "md5": "35f168c889cc045c0ac43fb9e9bd4f6e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder-core",
          "version": {
            "requires": "1.4.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "camera-viewfinder-compose-1.0.0-alpha01.aar",
          "url": "camera-viewfinder-compose-1.0.0-alpha01.aar",
          "size": 38455,
          "sha512": "0a0f37fd6dbed58c9c3fd5daef561a78e882270c6bfe486741948299d039c0aeea17d15e03897a6cda3b19573219751bb9ec588b39fd058d4a53ce9805c49fd2",
          "sha256": "2bb7972b82107b2e19e881f676cc1a89428284191bd2d3a710cd8ac3a67d0637",
          "sha1": "3bf5462fda4f0a6c87227d7a2ca6933758eff439",
          "md5": "f1ce490aa529f547b9b18fadfb35e79a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder-core",
          "version": {
            "requires": "1.4.0-alpha06"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera-viewfinder-compose-1.0.0-alpha01.aar",
          "url": "camera-viewfinder-compose-1.0.0-alpha01.aar",
          "size": 38455,
          "sha512": "0a0f37fd6dbed58c9c3fd5daef561a78e882270c6bfe486741948299d039c0aeea17d15e03897a6cda3b19573219751bb9ec588b39fd058d4a53ce9805c49fd2",
          "sha256": "2bb7972b82107b2e19e881f676cc1a89428284191bd2d3a710cd8ac3a67d0637",
          "sha1": "3bf5462fda4f0a6c87227d7a2ca6933758eff439",
          "md5": "f1ce490aa529f547b9b18fadfb35e79a"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "camera-viewfinder-compose-1.0.0-alpha01-versionMetadata.json",
          "url": "camera-viewfinder-compose-1.0.0-alpha01-versionMetadata.json",
          "size": 1222,
          "sha512": "dd7593d0f88fde14d661c6cf4a84d479260d3fdfed639e944fe5af7cad7fa5e5d62e6e20f1e129357b189b3b8cc45540e04eb460204424d6d58f7ef88d777f65",
          "sha256": "35fa5a87376afbb5661a0377bde8b1de4e5124ca469c55c6259cfcec69f50818",
          "sha1": "2741ad4b690575b785da74ed24f4fed1b52be76f",
          "md5": "ee4e6f0b3e0ddf16b1ebfe9b09ef857d"
        }
      ]
    }
  ]
}