version: "1.7.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.compose.material"
    artifact_id: "material-icons-core"
    version: "1.7.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.material"
    artifact_id: "material-icons-extended-android"
    version: "1.7.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.material"
    artifact_id: "material-icons-extended-desktop"
    version: "1.7.0-alpha01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.compose.material"
group_id: "androidx.compose.material"
artifact_id: "material-icons-extended"
path: "/compose/material/material-icons-extended"
sha: "585856c4f35f12b93a8ce64f4eedd1d0adedf32e"
require_same_version_group_build: true
group_zip_path: "per-group-zips/gmaven-androidx-compose-material-11264751.zip"
project_zip_path: "per-project-zips/androidx.compose.material-material-icons-extended-all-11264751-1.7.0-alpha01.zip"
kotlin_version: "1.9.22"
dependency_constraint_list {
  dependency {
    group_id: "androidx.compose.material"
    artifact_id: "material"
    version: "1.7.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.material"
    artifact_id: "material-icons-core"
    version: "1.7.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.material"
    artifact_id: "material-ripple"
    version: "1.7.0-alpha01"
    is_tip_of_tree: true
  }
}
