{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.datastore",
    "module": "datastore-preferences-proto",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-proto-1.2.0-alpha01.jar",
          "url": "datastore-preferences-proto-1.2.0-alpha01.jar",
          "size": 25836,
          "sha512": "f2ceebbb66167b6aa128d42d8bf4e0930b8df6d28178dc03a44e692fbd7a870a86b2e6c1f6f07da87474800fe109b0e7879f6eb5781c59778c6cfc5a5bf81ea1",
          "sha256": "6267d90cc38490205738b9650af11e6398d4fab90a0031ae900853072446450b",
          "sha1": "60811d810955fd6625231629d5aa27f4d5bf958b",
          "md5": "23fd9135f9ed5436295a30604309d2a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-proto-1.2.0-alpha01.jar",
          "url": "datastore-preferences-proto-1.2.0-alpha01.jar",
          "size": 25836,
          "sha512": "f2ceebbb66167b6aa128d42d8bf4e0930b8df6d28178dc03a44e692fbd7a870a86b2e6c1f6f07da87474800fe109b0e7879f6eb5781c59778c6cfc5a5bf81ea1",
          "sha256": "6267d90cc38490205738b9650af11e6398d4fab90a0031ae900853072446450b",
          "sha1": "60811d810955fd6625231629d5aa27f4d5bf958b",
          "md5": "23fd9135f9ed5436295a30604309d2a8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-proto is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-proto-1.2.0-alpha01-sources.jar",
          "url": "datastore-preferences-proto-1.2.0-alpha01-sources.jar",
          "size": 7418,
          "sha512": "0e202776800719c4a352f6ef08a9d2a76889431a7515c54181d8a2d0e3b7e046ba3151ba6c6605437b24bf02b96feb8a5b010b83a4e6c05303f5b7dec9ad3605",
          "sha256": "80d9a729c19cb95b6a56b1861684c28e4acc919737cfda374d557b8aba3c43c2",
          "sha1": "6d3f3b320406507bab4a7caa87cdb962e6a1be8a",
          "md5": "73c4c9cdf5b2807d3864c616850dfa71"
        }
      ]
    }
  ]
}