{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.datastore",
    "module": "datastore-preferences-external-protobuf",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-external-protobuf-1.2.0-alpha01.jar",
          "url": "datastore-preferences-external-protobuf-1.2.0-alpha01.jar",
          "size": 711655,
          "sha512": "c3eb33fd541fa9d04e6bd1794a888df520fe9a4ef33ad4efa659312d29dbaa233681e3691ec1e7ed18b7d07cbed1aaceebcc8777660aa6a778da38eaa25a9c74",
          "sha256": "aaefaa5472a70ad74c1c0e7a8941193abceeb1d38e31621d42b3d2ffd293fe6c",
          "sha1": "c9877a8b3f25a9cff98b9272f88f38b800906984",
          "md5": "820cb2d3398a7b97729fdbf4d65a38de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-external-protobuf-1.2.0-alpha01.jar",
          "url": "datastore-preferences-external-protobuf-1.2.0-alpha01.jar",
          "size": 711655,
          "sha512": "c3eb33fd541fa9d04e6bd1794a888df520fe9a4ef33ad4efa659312d29dbaa233681e3691ec1e7ed18b7d07cbed1aaceebcc8777660aa6a778da38eaa25a9c74",
          "sha256": "aaefaa5472a70ad74c1c0e7a8941193abceeb1d38e31621d42b3d2ffd293fe6c",
          "sha1": "c9877a8b3f25a9cff98b9272f88f38b800906984",
          "md5": "820cb2d3398a7b97729fdbf4d65a38de"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-external-protobuf-1.2.0-alpha01-sources.jar",
          "url": "datastore-preferences-external-protobuf-1.2.0-alpha01-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-external-protobuf is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-external-protobuf-1.2.0-alpha01-versionMetadata.json",
          "url": "datastore-preferences-external-protobuf-1.2.0-alpha01-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}