{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.tools",
    "module": "tools-core",
    "version": "1.0.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-core-1.0.0-alpha08.jar",
          "url": "tools-core-1.0.0-alpha08.jar",
          "size": 313456,
          "sha512": "8b37de417024e6ecf043ce86e29c9ac38f4bfd375f60e734f6f71b11c1946e239ecce2d9f9e1608005d18989befb347ce32c9c3ff909be9cec566fb8d45f6c1f",
          "sha256": "bff782b22b68ecf419ba3ee148f12507089b81f05c175694441436a9af271403",
          "sha1": "f6da92144df8b2efc437baa811af31779732dbbe",
          "md5": "03c75845d47496a826c91ec270dad6fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-core-1.0.0-alpha08.jar",
          "url": "tools-core-1.0.0-alpha08.jar",
          "size": 313456,
          "sha512": "8b37de417024e6ecf043ce86e29c9ac38f4bfd375f60e734f6f71b11c1946e239ecce2d9f9e1608005d18989befb347ce32c9c3ff909be9cec566fb8d45f6c1f",
          "sha256": "bff782b22b68ecf419ba3ee148f12507089b81f05c175694441436a9af271403",
          "sha1": "f6da92144df8b2efc437baa811af31779732dbbe",
          "md5": "03c75845d47496a826c91ec270dad6fc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-core-1.0.0-alpha08-sources.jar",
          "url": "tools-core-1.0.0-alpha08-sources.jar",
          "size": 51400,
          "sha512": "3b676db051ac2a5f13b066f941a53a7cf61a80ce87076d0aee4e7a26617580419e8d0bf378329417443020d6f7a599d51376b4bad49991219cb2ec7cb573fe1b",
          "sha256": "18c01cada893b2c93dd62139da74fde8df1c975e32d4e8770429a5390534ff2b",
          "sha1": "55c64d18a26b2eff8453a47f3422ac03fc03378c",
          "md5": "bae46daac6620d6ea4fb6277621358f3"
        }
      ]
    }
  ]
}