{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.tools",
    "module": "tools",
    "version": "1.0.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-1.0.0-alpha08.jar",
          "url": "tools-1.0.0-alpha08.jar",
          "size": 4198,
          "sha512": "996a2ef00cda0f03f537b74706fda7adb5360fa5326cdffcd96e6f510f6a6bf588efb1fb215cce76cd8b92c7cf7ca591fbf9bc5c669cba9f2360f2ec5c04ec04",
          "sha256": "83b78a665834bb554e8fb6cee1bc8fb81f0c55383f9fb44aedea44682393d4c8",
          "sha1": "426cb481f10bc00cdfef647d593dac0e3906ab0c",
          "md5": "12075add64b66d3722387d7178374ba7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-1.0.0-alpha08.jar",
          "url": "tools-1.0.0-alpha08.jar",
          "size": 4198,
          "sha512": "996a2ef00cda0f03f537b74706fda7adb5360fa5326cdffcd96e6f510f6a6bf588efb1fb215cce76cd8b92c7cf7ca591fbf9bc5c669cba9f2360f2ec5c04ec04",
          "sha256": "83b78a665834bb554e8fb6cee1bc8fb81f0c55383f9fb44aedea44682393d4c8",
          "sha1": "426cb481f10bc00cdfef647d593dac0e3906ab0c",
          "md5": "12075add64b66d3722387d7178374ba7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-1.0.0-alpha08-sources.jar",
          "url": "tools-1.0.0-alpha08-sources.jar",
          "size": 6373,
          "sha512": "a1eef85bbd797a98b211e3273a39e9176add6473f547c6fd01375ceb924ca62b546b2adc76ad23888024142d2e4f40e1d01674cd6a03b71624e34f1cd3c63542",
          "sha256": "ef751827acfb1f5e3c8986e3d83e088dc01c955561cd38364d3cd4055fb1db2e",
          "sha1": "cda5a4a3f67ef45d8342972f81d2c998fd3bb3f4",
          "md5": "e4afcff9bffd267c58c13a6478932122"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-1.0.0-alpha08-versionMetadata.json",
          "url": "tools-1.0.0-alpha08-versionMetadata.json",
          "size": 462,
          "sha512": "05a86a3ce48cdf2cca1e243747d0be81e8451068aa9b3d6c5b1afa567eb4a424c5c4690ae06bc7527a5428ee46cefad4d3a9644aeab7f78b53b9c37f8c995761",
          "sha256": "0fd3ddbacfadc5ff828a0a749b1c01b9ce213b1bd992c4c1e8be7c127bd0ec1e",
          "sha1": "c87bb8ffd36cfad37a427091828a625db1f60368",
          "md5": "8f908a16df69bfcd1c29290d865ff697"
        }
      ]
    }
  ]
}