{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.mediarouter",
    "module": "mediarouter",
    "version": "1.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.mediarouter",
          "module": "mediarouter-testing",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "mediarouter-1.5.0-alpha01.aar",
          "url": "mediarouter-1.5.0-alpha01.aar",
          "size": 749311,
          "sha512": "2f5fd0feb2513069ef423758f0aab97715fc0df79dcbd196102004742d191004d03d2c58de216b5346fc13c7ed888a3d99ef515482442fd6a655f0e8cb7b4ad2",
          "sha256": "a5c7c6cefc09c2a681a95f397b132b303a694e8a1e4518a017fefdba413d4943",
          "sha1": "196b1c123b97f143feea982270aa0800c9de6e06",
          "md5": "5e1b34ff3685af1ec652f245aa926bff"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.palette",
          "module": "palette",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.mediarouter",
          "module": "mediarouter-testing",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "mediarouter-1.5.0-alpha01.aar",
          "url": "mediarouter-1.5.0-alpha01.aar",
          "size": 749311,
          "sha512": "2f5fd0feb2513069ef423758f0aab97715fc0df79dcbd196102004742d191004d03d2c58de216b5346fc13c7ed888a3d99ef515482442fd6a655f0e8cb7b4ad2",
          "sha256": "a5c7c6cefc09c2a681a95f397b132b303a694e8a1e4518a017fefdba413d4943",
          "sha1": "196b1c123b97f143feea982270aa0800c9de6e06",
          "md5": "5e1b34ff3685af1ec652f245aa926bff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.mediarouter",
          "module": "mediarouter-testing",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "mediarouter-1.5.0-alpha01-sources.jar",
          "url": "mediarouter-1.5.0-alpha01-sources.jar",
          "size": 198348,
          "sha512": "caa0f1a25b2347556d214e09dcf935d16b2fa9947c06fe7bc4d9e37493cb6df6615d5edb2c619e0b355dd9bd46ecb0b659880f0d99bbde3a7ee2d2aea7920b22",
          "sha256": "d6f201b3d05ed19c3eef4048a7a90e107226467021f65131caa68b5f3947bde7",
          "sha1": "aff22489d8eef45652be0701e3e5258fa0fa7d8e",
          "md5": "f68598e82aeda261e52639ac81aeb7d6"
        }
      ]
    }
  ]
}