{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.browser",
    "module": "browser",
    "version": "1.9.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "browser-1.9.0-alpha01-sources.jar",
          "url": "browser-1.9.0-alpha01-sources.jar",
          "size": 111768,
          "sha512": "a2a5b2ab6ef3539113ea9a92c9a18acd58b476941815c1216e7c05ca34b657db1cf25cc8ba13b4cf4f2a6d3987d691b9a3c58f8ee5ae520ff59e89638bbe2a68",
          "sha256": "53581109d60588b7b2c513e62392eacd6bacd521e2d786c235c089ab437b3c98",
          "sha1": "5804ee3a5786c4f6341353923b8095801cf372d7",
          "md5": "6f1d5b5542c3c3ef388cc94dde71cc0e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "browser-1.9.0-alpha01.aar",
          "url": "browser-1.9.0-alpha01.aar",
          "size": 230364,
          "sha512": "0d24d3864ebf7515d63df1d511cc75b9fd4616a81bd676b4b6cb2710e81ec712b35e45dc53e74f4c61dc549f7eb195bb51db96d690c81b5e850e672d59e3741c",
          "sha256": "45e0d70636afb66fe836b83d697c99dec37c3899f6e779b1f94be69586935a60",
          "sha1": "89563de32c48117ffcccdcc32fff86b1268a65b4",
          "md5": "b1d4c478cd8c446979aa1b7e2015befc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.interpolator",
          "module": "interpolator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "browser-1.9.0-alpha01.aar",
          "url": "browser-1.9.0-alpha01.aar",
          "size": 230364,
          "sha512": "0d24d3864ebf7515d63df1d511cc75b9fd4616a81bd676b4b6cb2710e81ec712b35e45dc53e74f4c61dc549f7eb195bb51db96d690c81b5e850e672d59e3741c",
          "sha256": "45e0d70636afb66fe836b83d697c99dec37c3899f6e779b1f94be69586935a60",
          "sha1": "89563de32c48117ffcccdcc32fff86b1268a65b4",
          "md5": "b1d4c478cd8c446979aa1b7e2015befc"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "browser-1.9.0-alpha01-versionMetadata.json",
          "url": "browser-1.9.0-alpha01-versionMetadata.json",
          "size": 33825,
          "sha512": "1f9ed054ef9e8b20359fd5b977ba4fcd827e61a83eeb3a784781549601afa6b4e8ee31579be4c771f1d5d0d5fe871fe2bce80d09dabc25aafb1c6c1e695bc0b9",
          "sha256": "f241c0dfe26331e3f564764efb9bcb53607d07dc9d0772daacdd7a3ea4ab75a7",
          "sha1": "8e753532274bf5227d714910f4a9a2c720be9b04",
          "md5": "265a7a8dd8ffcb1558e3e0585367a88c"
        }
      ]
    }
  ]
}