{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui-ktx",
    "version": "2.8.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "Mirror navigation-ui dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-alpha03"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.8.0-alpha03.aar",
          "url": "navigation-ui-ktx-2.8.0-alpha03.aar",
          "size": 2143,
          "sha512": "3473904025fcff013ef248436fa41345d2049a1fc84bb5f323bd6f8a11a8fb8b831ba76a4578e899649a0d7c590249a661704675ab19682e6b892badab3c65b9",
          "sha256": "609903190d1597bd0097a98bd854c58f16b05fc74ff6499adf39eaf1ca45f526",
          "sha1": "12dc1a9ef65fafed9538b5e4f90d67c83884dfb7",
          "md5": "f1b5288d205b6d391713dd2bdd5fc40b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "Mirror navigation-ui dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-alpha03"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.8.0-alpha03.aar",
          "url": "navigation-ui-ktx-2.8.0-alpha03.aar",
          "size": 2143,
          "sha512": "3473904025fcff013ef248436fa41345d2049a1fc84bb5f323bd6f8a11a8fb8b831ba76a4578e899649a0d7c590249a661704675ab19682e6b892badab3c65b9",
          "sha256": "609903190d1597bd0097a98bd854c58f16b05fc74ff6499adf39eaf1ca45f526",
          "sha1": "12dc1a9ef65fafed9538b5e4f90d67c83884dfb7",
          "md5": "f1b5288d205b6d391713dd2bdd5fc40b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.8.0-alpha03-sources.jar",
          "url": "navigation-ui-ktx-2.8.0-alpha03-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.8.0-alpha03-versionMetadata.json",
          "url": "navigation-ui-ktx-2.8.0-alpha03-versionMetadata.json",
          "size": 6082,
          "sha512": "fb0750efd222f3f11e47b60aad4ddd51f9a17365c98a1d5b7b82e6ddbc9d9c5435d87f27af46c2f1525de64dfd08752ee31283393a5a5a5c416b714270228abb",
          "sha256": "be5b0e997e90e2d3d35778ae22da0ae2652be0e401c16bec50c6401dbc690fe7",
          "sha1": "cd7941a9f68e29512f8c113226f398a7ccd3cc4b",
          "md5": "599b2555933a2ccf868aaddeee44b632"
        }
      ]
    }
  ]
}