{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-saveable/1.7.0-beta02/runtime-saveable-1.7.0-beta02.module",
    "group": "androidx.compose.runtime",
    "module": "runtime-saveable",
    "version": "1.7.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-beta02"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-release.aar",
          "url": "runtime-saveable-android-1.7.0-beta02.aar",
          "size": 1116236,
          "sha512": "163427a93618c509afc6af8a7be43460eb04520ce7ede9f9e3396dc2d69ada0e41f597ad9f66a548d91637d53f5a94c8fa5482c117fb44e3f65b19fc946556ba",
          "sha256": "c6a36ffe14539db24322c876b814ce6d4d2c7c71f826e3000881122a46f602a8",
          "sha1": "014d7630a39609cd7dec3a84758d44aacff6ebb7",
          "md5": "e581b17c7bdfa293e272cb85996ca748"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-release.aar",
          "url": "runtime-saveable-android-1.7.0-beta02.aar",
          "size": 1116236,
          "sha512": "163427a93618c509afc6af8a7be43460eb04520ce7ede9f9e3396dc2d69ada0e41f597ad9f66a548d91637d53f5a94c8fa5482c117fb44e3f65b19fc946556ba",
          "sha256": "c6a36ffe14539db24322c876b814ce6d4d2c7c71f826e3000881122a46f602a8",
          "sha1": "014d7630a39609cd7dec3a84758d44aacff6ebb7",
          "md5": "e581b17c7bdfa293e272cb85996ca748"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-1.7.0-beta02-samples-sources.jar",
          "url": "runtime-saveable-android-1.7.0-beta02-samples-sources.jar",
          "size": 4242,
          "sha512": "e5f63bc82457d1c674a170db0a329465d93b190448a285c5ab6ba21ac4dcafed89579d908c2adf5f2cc8da805f8e2c734fae396cd0d337cab26479675d8413a9",
          "sha256": "798fb6b311ed459c2028126a3deb7596b2742d8a0694db5fc93e236aa2a1316b",
          "sha1": "f455c0e1f32983bec40d871459943835e3d10c96",
          "md5": "54da7c450cadd9706f836a217bfa469f"
        },
        {
          "name": "runtime-saveable-android-1.7.0-beta02-sources.jar",
          "url": "runtime-saveable-android-1.7.0-beta02-sources.jar",
          "size": 11727,
          "sha512": "d8bde7ba3fa12d25632bb43f60f8227314f3f6d025abaa87b480327c283a9e0d8faf8130be038ddb69af7c6eec263b468366f79a748c1665a0cea85cb33b026a",
          "sha256": "909185ecf261fa573b8b3b8819df240da4ee6cc1b09e41fcde715a5150c25f71",
          "sha1": "02db055bc54471c10b9696d85a59b517aee3a909",
          "md5": "600770ca0e47350fd22b2c369ca469dc"
        }
      ]
    }
  ]
}