{
  "formatVersion": "1.1",
  "component": {
    "url": "../../room-runtime/2.7.0-alpha01/room-runtime-2.7.0-alpha01.module",
    "group": "androidx.room",
    "module": "room-runtime",
    "version": "2.7.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0-alpha01"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha01"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-runtime-release.aar",
          "url": "room-runtime-android-2.7.0-alpha01.aar",
          "size": 426273,
          "sha512": "484cc259e24b05a2249ce8ca646ec1bb7427375826cc46169db3eba33af7938c02ef5d137b7634498f94ee9f1ab861164c8a4b57176cc4ec3e4b201c9d2b03d5",
          "sha256": "6798510c3fdfad962f2e857b81fc3dab786e599a13e88531e11ef6472baa3d0d",
          "sha1": "ff5931181cefc8a30c80bdd92cef430f7f5fdaa1",
          "md5": "14673067389460491c55db2f8c31b62f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0-rc01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-runtime-release.aar",
          "url": "room-runtime-android-2.7.0-alpha01.aar",
          "size": 426273,
          "sha512": "484cc259e24b05a2249ce8ca646ec1bb7427375826cc46169db3eba33af7938c02ef5d137b7634498f94ee9f1ab861164c8a4b57176cc4ec3e4b201c9d2b03d5",
          "sha256": "6798510c3fdfad962f2e857b81fc3dab786e599a13e88531e11ef6472baa3d0d",
          "sha1": "ff5931181cefc8a30c80bdd92cef430f7f5fdaa1",
          "md5": "14673067389460491c55db2f8c31b62f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-runtime-android-2.7.0-alpha01-sources.jar",
          "url": "room-runtime-android-2.7.0-alpha01-sources.jar",
          "size": 142499,
          "sha512": "84004fc49707a98784475acbc173ce50a258a6d29fa3b0b6befac3c4b410a2773eb7b18bc7071142bec99e9671e99d00343ec58fda8defa10796871e5ae2c3eb",
          "sha256": "17831fc398629c2080d84fff9e7d5fed6157c5d5a5290256d7c1906bc88b5902",
          "sha1": "ef0f585893fe8a67705178cd8a5af7734d4b8aa1",
          "md5": "97287370cd509aa4758a09d5fece4dd9"
        }
      ]
    }
  ]
}