{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-camera2",
    "version": "1.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.4.0-beta01-sources.jar",
          "url": "camera-camera2-1.4.0-beta01-sources.jar",
          "size": 365513,
          "sha512": "52e6cfa55a1e8f9071787ac374a0875884483b86abcdf2ae62b89183a1e00d6c3ca6d53a37fc3f7839ef9311dced7f2936f168e677b234e000c3b5d811468c22",
          "sha256": "36525d30caec37976ae077d47c77792f8aec7c5b1976252ddfc4a9fc63e8a1b8",
          "sha1": "9d4de27cb9c18242c5bfbb20c27417dfdc0da934",
          "md5": "76edaf6403fd70c2d23489848df2f33e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.4.0-beta01.aar",
          "url": "camera-camera2-1.4.0-beta01.aar",
          "size": 468338,
          "sha512": "9fec62a713d33238ca22b0a12e2c9489382719c15bc23a475e55789cd57449015110b7fa5f92cfb5ef330d8e5fc31117a5d162dea3c9dbe8568c6d61fa59f3ad",
          "sha256": "fb17e13cb140e1c2b7c492944f4a9ef103e0cc650d523d34201c6cf11f407f36",
          "sha1": "d3fc619fd92a0f1f249d1ec97a0faeb8f75d8bbb",
          "md5": "a4196856df4b7b3edca42c83db5dccd5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.4.0-beta01.aar",
          "url": "camera-camera2-1.4.0-beta01.aar",
          "size": 468338,
          "sha512": "9fec62a713d33238ca22b0a12e2c9489382719c15bc23a475e55789cd57449015110b7fa5f92cfb5ef330d8e5fc31117a5d162dea3c9dbe8568c6d61fa59f3ad",
          "sha256": "fb17e13cb140e1c2b7c492944f4a9ef103e0cc650d523d34201c6cf11f407f36",
          "sha1": "d3fc619fd92a0f1f249d1ec97a0faeb8f75d8bbb",
          "md5": "a4196856df4b7b3edca42c83db5dccd5"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.4.0-beta01-versionMetadata.json",
          "url": "camera-camera2-1.4.0-beta01-versionMetadata.json",
          "size": 3277,
          "sha512": "3457aaf1daae3c23df1afa125444b2c9febccd6c8eee62fddb37b74e4d217ea8183aafd55fe757191cd7be2d45e078616d54dbb1f172558a02fe063cbec75f1f",
          "sha256": "d8cec82581880afa10cba43907db64357c3f6a765fd7598a042eb7943b1019f4",
          "sha1": "f1e5deb7118484ad497eec922b64b108f5993b67",
          "md5": "6d6e3a9187e23ee6c4cd6dfcaa04b2b9"
        }
      ]
    }
  ]
}