{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-compose",
    "version": "2.8.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.8.0-beta03-sources.jar",
          "url": "navigation-compose-2.8.0-beta03-sources.jar",
          "size": 19073,
          "sha512": "db00f70a0e53ad7fa2fe705274cdfb3aafe9b09701f9c08136ae371390b0b5715533285728448dafb9d1e1e75a2d76e1094a4c973617570dec5de531e7d084c1",
          "sha256": "f0d2bd24fe7b2bad6330daf172c23085685123874e9081ddc1081956dfc531d8",
          "sha1": "0cfdcf891f53c82b01d7d646d98ff2103b46320f",
          "md5": "57bf54aed0236746711ee30036ab2bff"
        },
        {
          "name": "navigation-compose-2.8.0-beta03-samples-sources.jar",
          "url": "navigation-compose-2.8.0-beta03-samples-sources.jar",
          "size": 7083,
          "sha512": "88eb06b4b4dc62057b7080a6643345c5e986d246a3e0ba8b7df4c8dc7be9729fbef8a4af79f42e306f3d05be388fe816ac0eab4f99727cf613e083d5aab861de",
          "sha256": "95d01a4598d7998240020ffe775c704c95981233e5fb8cbfed2c3c5444f8398e",
          "sha1": "2a99da4e6c8e69119c47fdc7683336459abdea13",
          "md5": "8a1999948f06237b11df4a1f8af40a99"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-beta03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-beta03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.7.0-beta03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-beta03"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.8.0-beta03.aar",
          "url": "navigation-compose-2.8.0-beta03.aar",
          "size": 1206326,
          "sha512": "d14f48424c3c47923987086b590d967c84eb8d2f9448d39887cd1c7411bd4e8a71758991ba3277030d3ccec0eeff53525793550ead6b382c82428d4da25cd245",
          "sha256": "a277427168c79079e24512d0edf90d05cca566d5cb9b17a6ce4ddcf1fa7a306f",
          "sha1": "c91f01b95d91f71e4b2834b8a82ec9a5db7fe509",
          "md5": "bfa3ae36ddeb1522047885fdc7a3f1ad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-beta03"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-beta03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-beta03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.7.0-beta03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-beta03"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.8.0-beta03.aar",
          "url": "navigation-compose-2.8.0-beta03.aar",
          "size": 1206326,
          "sha512": "d14f48424c3c47923987086b590d967c84eb8d2f9448d39887cd1c7411bd4e8a71758991ba3277030d3ccec0eeff53525793550ead6b382c82428d4da25cd245",
          "sha256": "a277427168c79079e24512d0edf90d05cca566d5cb9b17a6ce4ddcf1fa7a306f",
          "sha1": "c91f01b95d91f71e4b2834b8a82ec9a5db7fe509",
          "md5": "bfa3ae36ddeb1522047885fdc7a3f1ad"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0-beta03"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.8.0-beta03-versionMetadata.json",
          "url": "navigation-compose-2.8.0-beta03-versionMetadata.json",
          "size": 22099,
          "sha512": "662e31ba00f2741f0d860f96e73cc46c69c1239ea470ab980f50cbbb92b147da257ac0832a092386b2ca7e9cfb5ac5ade1758cb7ef4bfd5c4696038d3c1749c9",
          "sha256": "ddff084bafbe7f13bfb53908136dd8feb335063551092cd4364bb3d4a1696cc9",
          "sha1": "e79576a41c96e6e2886842efc8101050fab8d28e",
          "md5": "87a4033bd0614eedbef3e693c5fd5529"
        }
      ]
    }
  ]
}