version: "2.10.0-alpha02"
dependency_list {
  dependency {
    group_id: "androidx.work"
    artifact_id: "work-runtime"
    version: "2.10.0-alpha02"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.work"
group_id: "androidx.work"
artifact_id: "work-runtime-ktx"
path: "/work/work-runtime-ktx"
sha: "f7e7d1939c03cfe2480ecd45ee9b33ab4a863638"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.work-work-runtime-ktx-all-11963838-2.10.0-alpha02.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
  dependency {
    group_id: "androidx.work"
    artifact_id: "work-gcm"
    version: "2.10.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.work"
    artifact_id: "work-multiprocess"
    version: "2.10.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.work"
    artifact_id: "work-runtime"
    version: "2.10.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.work"
    artifact_id: "work-rxjava2"
    version: "2.10.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.work"
    artifact_id: "work-rxjava3"
    version: "2.10.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.work"
    artifact_id: "work-testing"
    version: "2.10.0-alpha02"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
