{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.glance",
    "module": "glance-material3",
    "version": "1.1.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-material3-1.1.0-rc01-sources.jar",
          "url": "glance-material3-1.1.0-rc01-sources.jar",
          "size": 2443,
          "sha512": "1cde3d0a7dca006b08eceb33b8703ebf69d0737f6ce9ed23e1d03bba3f499d3f17f77a767dd13a7e36ec3ddd0dbca972e07295c77be79251c1b29690330b4e22",
          "sha256": "37a58f463ebb5fb36555675470da810f68f4e9e065f41aeefe1fd78deb90659a",
          "sha1": "ef341bd0e245f2e99d29884ba4dfdef0bbb9df28",
          "md5": "090acf07f39d0eac6fdfcacb1eb31d14"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.0-rc01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-material3-1.1.0-rc01.aar",
          "url": "glance-material3-1.1.0-rc01.aar",
          "size": 3835,
          "sha512": "5ef861a726fd2b7addf25828e42ab1d73469069bb5ce27e8725c2aee1da21b55cde6dd57aa43e4da1c2de99a372fb00789aed40f80942555501889e160bd7ed9",
          "sha256": "34fd53a6c9a51baba8e301d7bff8b779dbac37f39ad86c62ad1f7bdfa77bdbfd",
          "sha1": "edf22cf5ae6e3fd00e7d259a770bfbf1056ace53",
          "md5": "76ad6d4be003c6a1861ffff328b0608f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-material3-1.1.0-rc01.aar",
          "url": "glance-material3-1.1.0-rc01.aar",
          "size": 3835,
          "sha512": "5ef861a726fd2b7addf25828e42ab1d73469069bb5ce27e8725c2aee1da21b55cde6dd57aa43e4da1c2de99a372fb00789aed40f80942555501889e160bd7ed9",
          "sha256": "34fd53a6c9a51baba8e301d7bff8b779dbac37f39ad86c62ad1f7bdfa77bdbfd",
          "sha1": "edf22cf5ae6e3fd00e7d259a770bfbf1056ace53",
          "md5": "76ad6d4be003c6a1861ffff328b0608f"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.0-rc01"
          },
          "reason": "glance-material3 is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-material3-1.1.0-rc01-versionMetadata.json",
          "url": "glance-material3-1.1.0-rc01-versionMetadata.json",
          "size": 310,
          "sha512": "9ad981a05296f6e6cc957e9f9688756520999e65dfd639e0d15f252da77e09fc0a071fb1f0cb4c012ef63f6104909afbe3ce0354ede078a7d0953567cf90df4d",
          "sha256": "b2eb7599eeeb21db3d225c744b6e1a8378dc1382870b0f2b998a0554a76f5d12",
          "sha1": "bc4d5e85ee8400771093ce841eb6ffb88f565571",
          "md5": "59a51770f492c71ab5c8760668b0cee5"
        }
      ]
    }
  ]
}