{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.remotecallback",
    "module": "remotecallback",
    "version": "1.0.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.remotecallback",
          "module": "remotecallback-processor",
          "version": {
            "requires": "1.0.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "remotecallback-1.0.0-alpha02.aar",
          "url": "remotecallback-1.0.0-alpha02.aar",
          "size": 18190,
          "sha512": "c9d35ca9780f5f32b4c831ddd8422f4cac0c519a654db4c4caf4935840a16335eaa93709ae2bb634ea17a444f34146c58c033e6076a6802cdf75b2a33c74db9f",
          "sha256": "0a1a4f8346ea8773584e4d458a564e2852056704ef964d4a94e1c3955ea3c1de",
          "sha1": "891132093cbbd9cab156bfbef98998ef42a4f96e",
          "md5": "520df6348e07ea94392610b581b91594"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.3.0-alpha05"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.remotecallback",
          "module": "remotecallback-processor",
          "version": {
            "requires": "1.0.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "remotecallback-1.0.0-alpha02.aar",
          "url": "remotecallback-1.0.0-alpha02.aar",
          "size": 18190,
          "sha512": "c9d35ca9780f5f32b4c831ddd8422f4cac0c519a654db4c4caf4935840a16335eaa93709ae2bb634ea17a444f34146c58c033e6076a6802cdf75b2a33c74db9f",
          "sha256": "0a1a4f8346ea8773584e4d458a564e2852056704ef964d4a94e1c3955ea3c1de",
          "sha1": "891132093cbbd9cab156bfbef98998ef42a4f96e",
          "md5": "520df6348e07ea94392610b581b91594"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.remotecallback",
          "module": "remotecallback-processor",
          "version": {
            "requires": "1.0.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "remotecallback-1.0.0-alpha02-sources.jar",
          "url": "remotecallback-1.0.0-alpha02-sources.jar",
          "size": 14883,
          "sha512": "ddee37d2383f8d00b7f1a3a0c3a8d62ee4923999cada00a834f846edbfb363901e403c85bf83110366a7b06db7383da2e1fd7a4b3765e03ec834e5d9d7f915e5",
          "sha256": "04b311dec23f75d53eafa225b26000321872fe9415dc5ed59ab227880560b26f",
          "sha1": "da0cef4c3da11dac9b242be29fcd0c121d815366",
          "md5": "a95f6a8a1b8821c882edb81f3c64e410"
        }
      ]
    }
  ]
}