{
  "formatVersion": "1.1",
  "component": {
    "url": "../../datastore-core/1.2.0-alpha01/datastore-core-1.2.0-alpha01.module",
    "group": "androidx.datastore",
    "module": "datastore-core",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-core-release.aar",
          "url": "datastore-core-android-1.2.0-alpha01.aar",
          "size": 207425,
          "sha512": "21e9ef370b3dc7ce020e73a01d68d82478641c7ecc110a2cc3c2d6ca2105dd01ad82ba86672fe17935a281fb99d1a4e62e1833e0be8df2985b012947a1cac6ef",
          "sha256": "716141b085a5cdcef5f2d9f4bc18dceb64e1e576de5b1d0811977511d85cd8f0",
          "sha1": "887ae4d90cb260b0729025a03b5dcd7000818c9a",
          "md5": "6d12efafa208037efa0b7810ab65d552"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.24"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-core-release.aar",
          "url": "datastore-core-android-1.2.0-alpha01.aar",
          "size": 207425,
          "sha512": "21e9ef370b3dc7ce020e73a01d68d82478641c7ecc110a2cc3c2d6ca2105dd01ad82ba86672fe17935a281fb99d1a4e62e1833e0be8df2985b012947a1cac6ef",
          "sha256": "716141b085a5cdcef5f2d9f4bc18dceb64e1e576de5b1d0811977511d85cd8f0",
          "sha1": "887ae4d90cb260b0729025a03b5dcd7000818c9a",
          "md5": "6d12efafa208037efa0b7810ab65d552"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-core-android-1.2.0-alpha01-sources.jar",
          "url": "datastore-core-android-1.2.0-alpha01-sources.jar",
          "size": 52178,
          "sha512": "3bee2902efe516ef510b41a881cbe962b33c26276586f0f1df034017c03287af7f08d76c0bde7494e6565c36a238fe341f2f96699f461bf14a27279fb7a83519",
          "sha256": "686b46bf17ec5a10c2e83a5005ebc75b7646e3af27ab82960466b0a9b16eb465",
          "sha1": "9542d93849d351041ce9fcb993c0051f11413e7f",
          "md5": "f1f0a716bb3b86d00f223d0932d2663d"
        }
      ]
    }
  ]
}