{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.savedstate",
    "module": "savedstate-ktx",
    "version": "1.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.3.0-alpha01.aar",
          "url": "savedstate-ktx-1.3.0-alpha01.aar",
          "size": 3021,
          "sha512": "01cf401c0726c07ebc90024c5ab5f6eb517bd9de03c47e7549474ba933afefbcf3955836abc0dbed048829ce821c56d8d15eb96a174100e593f6a0be3cb39925",
          "sha256": "02e4100d2111109764c78d8df3119e8d1ef79fbdc908371f975b6b605da99cbe",
          "sha1": "3d677ad2b6192113dded4462334ab4a31bdc4ab3",
          "md5": "5580206d72eb4e96d4c0215ccbc4db13"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.3.0-alpha01.aar",
          "url": "savedstate-ktx-1.3.0-alpha01.aar",
          "size": 3021,
          "sha512": "01cf401c0726c07ebc90024c5ab5f6eb517bd9de03c47e7549474ba933afefbcf3955836abc0dbed048829ce821c56d8d15eb96a174100e593f6a0be3cb39925",
          "sha256": "02e4100d2111109764c78d8df3119e8d1ef79fbdc908371f975b6b605da99cbe",
          "sha1": "3d677ad2b6192113dded4462334ab4a31bdc4ab3",
          "md5": "5580206d72eb4e96d4c0215ccbc4db13"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.3.0-alpha01-sources.jar",
          "url": "savedstate-ktx-1.3.0-alpha01-sources.jar",
          "size": 1225,
          "sha512": "c22f31974b323e4490f052e34818283817c70764ae3f01aa98d61cce6f6713bfa72a512e7429f72885d3243cd2cd1b83090d7e9fa8cdbe1e7b43524173f9048d",
          "sha256": "45f49fe9075235c62d409f2d11d795b3c7308bccb475ed43ed8312638119cc27",
          "sha1": "396eb83ce13cac3986e1e8a8b60f60ac0447ffbf",
          "md5": "0dd36a3a26c3ff2ccac7c085855f1176"
        }
      ]
    }
  ]
}