{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.gridlayout",
    "module": "gridlayout",
    "version": "1.1.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "gridlayout-1.1.0-alpha02.aar",
          "url": "gridlayout-1.1.0-alpha02.aar",
          "size": 41446,
          "sha512": "07f6e7ff526d8fbc963ec0aa5334cadece0bcf0598da6b19dedfa5e2597a14dd800402ec348c6e9825be93a0342bbce02cf78d993a41b1c78c016d20908a51af",
          "sha256": "2f5477085b9529ed3f2caaac7441d86a4469f63c0284ffd1dcba62e1aeeda517",
          "sha1": "d486f58f05ff683cb2d47b2158e55f7bf1d0f2a1",
          "md5": "20d9a5e9458a1494ef4e63e8db0659dc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "gridlayout-1.1.0-alpha02.aar",
          "url": "gridlayout-1.1.0-alpha02.aar",
          "size": 41446,
          "sha512": "07f6e7ff526d8fbc963ec0aa5334cadece0bcf0598da6b19dedfa5e2597a14dd800402ec348c6e9825be93a0342bbce02cf78d993a41b1c78c016d20908a51af",
          "sha256": "2f5477085b9529ed3f2caaac7441d86a4469f63c0284ffd1dcba62e1aeeda517",
          "sha1": "d486f58f05ff683cb2d47b2158e55f7bf1d0f2a1",
          "md5": "20d9a5e9458a1494ef4e63e8db0659dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gridlayout-1.1.0-alpha02-sources.jar",
          "url": "gridlayout-1.1.0-alpha02-sources.jar",
          "size": 24251,
          "sha512": "01ed12132d71c52075fabbd86c3d9713b8f81aef8e8d0eb3c402f8f282a1d69f185b33ddeb42715861976f1ae48bee77e969aea8d8d50b4b07aea6d850b07fb2",
          "sha256": "c4e5aa63dc03e44427198b6255f93bf73f94c6fcca6259c81e63490e58c1774a",
          "sha1": "d217a2c03fe182e6d8cd09cb7f26bc934a4a645a",
          "md5": "9a0db73abf88b8cd769db30c9fac6662"
        }
      ]
    }
  ]
}