version: "1.3.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.compose.material3"
    artifact_id: "material3-window-size-class-android"
    version: "1.3.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.material3"
    artifact_id: "material3-window-size-class-desktop"
    version: "1.3.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime"
    version: "1.6.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui"
    version: "1.6.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-unit"
    version: "1.6.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.compose.material3"
group_id: "androidx.compose.material3"
artifact_id: "material3-window-size-class"
path: "/compose/material3/material3-window-size-class"
sha: "6051cad23e2ba97fd1fdeea218cec5119d8213de"
require_same_version_group_build: true
group_zip_path: "per-group-zips/gmaven-androidx-compose-material3-11436812.zip"
project_zip_path: "per-project-zips/androidx.compose.material3-material3-window-size-class-all-11436812-1.3.0-alpha01.zip"
kotlin_version: "1.9.22"
dependency_constraint_list {
  dependency {
    group_id: "androidx.compose.material3"
    artifact_id: "material3"
    version: "1.3.0-alpha01"
    is_tip_of_tree: true
  }
}
