version: "1.0.0-alpha08"
dependency_list {
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools"
    version: "1.0.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-core"
    version: "1.0.0-alpha08"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.privacysandbox.tools"
group_id: "androidx.privacysandbox.tools"
artifact_id: "tools-apipackager"
path: "/privacysandbox/tools/tools-apipackager"
sha: "319668a0bb17aaa0caa7dda23b37b170b1bf02cd"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.privacysandbox.tools-tools-apipackager-all-11904167-1.0.0-alpha08.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools"
    version: "1.0.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-apicompiler"
    version: "1.0.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-apigenerator"
    version: "1.0.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-core"
    version: "1.0.0-alpha08"
    is_tip_of_tree: true
  }
}
should_publish_docs: false
is_kmp: false
