version: "2.8.0-beta03"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-experimental"
    version: "1.4.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.customview"
    artifact_id: "customview"
    version: "1.1.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.drawerlayout"
    artifact_id: "drawerlayout"
    version: "1.1.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-runtime"
    version: "2.8.0-beta03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.transition"
    artifact_id: "transition"
    version: "1.3.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.navigation"
group_id: "androidx.navigation"
artifact_id: "navigation-ui"
path: "/navigation/navigation-ui"
sha: "8e24ec7cf4ee1c5afe2b4a3a108f926420140662"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.navigation-navigation-ui-all-11954666-2.8.0-beta03.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-common"
    version: "2.8.0-beta03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-common-ktx"
    version: "2.8.0-beta03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-compose"
    version: "2.8.0-beta03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-dynamic-features-fragment"
    version: "2.8.0-beta03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-dynamic-features-runtime"
    version: "2.8.0-beta03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-fragment"
    version: "2.8.0-beta03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-fragment-compose"
    version: "2.8.0-beta03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-fragment-ktx"
    version: "2.8.0-beta03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-runtime"
    version: "2.8.0-beta03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-runtime-ktx"
    version: "2.8.0-beta03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-safe-args-generator"
    version: "2.8.0-beta03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-safe-args-gradle-plugin"
    version: "2.8.0-beta03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-testing"
    version: "2.8.0-beta03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-ui-ktx"
    version: "2.8.0-beta03"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
