{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material-core",
    "version": "1.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.4.0-alpha03.aar",
          "url": "compose-material-core-1.4.0-alpha03.aar",
          "size": 153419,
          "sha512": "b0e87a185620658922486375f369f6203fa62d96917bb6b52ecb6778bac2a688a2098092dfa7e83d5cc81ce40bcdfe10eee4032576dffe2724681614b994f5ee",
          "sha256": "ac85e40649e2fe2af19d04cad22bc36556f65a1448ea4cfbb8aa4c22110a317e",
          "sha1": "8b7379bea41d04263dd6d1737b68e7ac1a88cc77",
          "md5": "b5e101892906d2168150a4d267a722e9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.4.0-alpha03.aar",
          "url": "compose-material-core-1.4.0-alpha03.aar",
          "size": 153419,
          "sha512": "b0e87a185620658922486375f369f6203fa62d96917bb6b52ecb6778bac2a688a2098092dfa7e83d5cc81ce40bcdfe10eee4032576dffe2724681614b994f5ee",
          "sha256": "ac85e40649e2fe2af19d04cad22bc36556f65a1448ea4cfbb8aa4c22110a317e",
          "sha1": "8b7379bea41d04263dd6d1737b68e7ac1a88cc77",
          "md5": "b5e101892906d2168150a4d267a722e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.4.0-alpha03-sources.jar",
          "url": "compose-material-core-1.4.0-alpha03-sources.jar",
          "size": 29657,
          "sha512": "23b9717e02bcda9a2ca162cd5dd37ca2800d9a1f69ab74a0f8e1a1b860681ba6e377998ab4c700a452f55ed5dba64be0e996fb30882751482dc5fe3ec0cde219",
          "sha256": "32fb37582c0a534c4455fe96708d917d352bd8cb0e6a68fab95a5c7a8e95a9d2",
          "sha1": "7e86a64a6b4b1a3824d8693675e659d988c31c43",
          "md5": "d432e4ab6f6426e6f2e669c68739b5cf"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.4.0-alpha03-versionMetadata.json",
          "url": "compose-material-core-1.4.0-alpha03-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}