{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-util/1.7.0-beta02/ui-util-1.7.0-beta02.module",
    "group": "androidx.compose.ui",
    "module": "ui-util",
    "version": "1.7.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-util-release.aar",
          "url": "ui-util-android-1.7.0-beta02.aar",
          "size": 15704,
          "sha512": "6cca88a3b85a931a948ccce99d23e83eae005574a40d238df5a351567bf1b42768fa0d6601803ac9d03164d9d058d6f762296bf3e43c433ba72e0eb8b93e1f66",
          "sha256": "a05232748c9c4581fcf8b3cb5c96dcf50f3f7702b5da32a0038103747c54b385",
          "sha1": "3b62ace6989ad4517d696455f4eae6490a1a4827",
          "md5": "11553cfccda3520c859fa4ad291eed7b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-util-release.aar",
          "url": "ui-util-android-1.7.0-beta02.aar",
          "size": 15704,
          "sha512": "6cca88a3b85a931a948ccce99d23e83eae005574a40d238df5a351567bf1b42768fa0d6601803ac9d03164d9d058d6f762296bf3e43c433ba72e0eb8b93e1f66",
          "sha256": "a05232748c9c4581fcf8b3cb5c96dcf50f3f7702b5da32a0038103747c54b385",
          "sha1": "3b62ace6989ad4517d696455f4eae6490a1a4827",
          "md5": "11553cfccda3520c859fa4ad291eed7b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-util-android-1.7.0-beta02-sources.jar",
          "url": "ui-util-android-1.7.0-beta02-sources.jar",
          "size": 13630,
          "sha512": "9b595f7b8080e00244c2241c6ff2c8a915afc617377930230e9ae08d25c66db5e4678e7eb095fb62db00b0f94f032df45286660a1a9ca1dec1184125217339e0",
          "sha256": "ee128e663af03a00a6301537c061c2df583fd8eae243af2fac6bfe3a1b555f3e",
          "sha1": "8533d5b40174e5cbd6b70ad99710429e7eadbb64",
          "md5": "8b7bc1e9e9e5bc7450fcf4c019a0d0f0"
        }
      ]
    }
  ]
}