{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-compose",
    "version": "1.10.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.10.0-alpha01-sources.jar",
          "url": "activity-compose-1.10.0-alpha01-sources.jar",
          "size": 10901,
          "sha512": "7b986da1d1e1d9397db84f57de12942449a42fbe37eb91ab14e1b87f3af7dc080e516fbfd7f0df0244906a50cfc41c21177f4854db251c2dce70bcecb0c0809c",
          "sha256": "b47ef42f69e2e2bcbd46b66e33a49523c3c8b765e5624b31f87458c4489aa1a9",
          "sha1": "43083865eae4abef1d967e6ede892aa826fa238b",
          "md5": "25da4863987573017951514694aadd1c"
        },
        {
          "name": "activity-compose-1.10.0-alpha01-samples-sources.jar",
          "url": "activity-compose-1.10.0-alpha01-samples-sources.jar",
          "size": 3661,
          "sha512": "904e640aac5f92462f97083d2ecf8fafd57d41fe79a56cd17200290c770da45b8e68f93e2e47c14b6d7dd9e6c6768f87054cf16b7715144f8afdf0faf5265e14",
          "sha256": "eb6faec8713cd98e209e12aa8298aabc93df60ca81c9f5c3e4c89b6dbc8a4292",
          "sha1": "70d9d99b84f92f4760a59f9c7a63575f2c46c297",
          "md5": "ff77727e192cb5918e4f2116fb9b9755"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.10.0-alpha01.aar",
          "url": "activity-compose-1.10.0-alpha01.aar",
          "size": 1148452,
          "sha512": "4cf697d62ad28decd720556d43bcfda01c5c48232614acb62be129857b900047435083d601c25e5e49502c41b4cb2a1e8244ac29fd0898384a02062cbd16559f",
          "sha256": "b73ba693e6fe8e333128e16feb33a35c3c6164002cfc907a3c25b1c959caa85c",
          "sha1": "d5bf02ef7b7acadc0474aa429f38f8ed03c8eac4",
          "md5": "175eb06c4253be05d6c39222b330bb23"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.10.0-alpha01.aar",
          "url": "activity-compose-1.10.0-alpha01.aar",
          "size": 1148452,
          "sha512": "4cf697d62ad28decd720556d43bcfda01c5c48232614acb62be129857b900047435083d601c25e5e49502c41b4cb2a1e8244ac29fd0898384a02062cbd16559f",
          "sha256": "b73ba693e6fe8e333128e16feb33a35c3c6164002cfc907a3c25b1c959caa85c",
          "sha1": "d5bf02ef7b7acadc0474aa429f38f8ed03c8eac4",
          "md5": "175eb06c4253be05d6c39222b330bb23"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.10.0-alpha01-versionMetadata.json",
          "url": "activity-compose-1.10.0-alpha01-versionMetadata.json",
          "size": 2701,
          "sha512": "38e96fef550bc65a3cf2ef95fe4db98d47cef44c3db84ce19558c46543fce2b7f45b4dcad6c014993537706d3efd7d5d0b5b252b46c69d16a1e4b56fab8dee3f",
          "sha256": "edf2427da6f69559a4988536153f0826f46d319a7b2b80ef23c57fa83d23c7f3",
          "sha1": "3ce35c3833c670be76e757d0e68e8a9b4d0f6f15",
          "md5": "0866fd37c1abd4c3104bbf8b74e478d9"
        }
      ]
    }
  ]
}