version: "2.4.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.4.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.tracing"
    artifact_id: "tracing"
    version: "1.1.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.test.uiautomator"
group_id: "androidx.test.uiautomator"
artifact_id: "uiautomator"
path: "/test/uiautomator/uiautomator"
sha: "c1559fca7faae47d40a3c498fb77ca2707c1f56c"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.test.uiautomator-uiautomator-all-11909744-2.4.0-alpha01.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
