{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-extensions",
    "version": "1.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-extensions-1.4.0-beta01-sources.jar",
          "url": "camera-extensions-1.4.0-beta01-sources.jar",
          "size": 92287,
          "sha512": "969c2b102f1df69ee9d8b0099d509c5557c5a47a99393c7a1514adbf61d6679e13567743c63d05371a0be1ae96006668b8f1e2103db58246aba3c360fd0735d7",
          "sha256": "298f9f9a200604da78b68699094010c13a25879dea89d1c1d6f026c5c2e66eb6",
          "sha1": "0d42506ba7920bf6e0fd82b11d98a6dca92d2d18",
          "md5": "cb2a416b94c267b4e42c62428687f900"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-extensions-1.4.0-beta01.aar",
          "url": "camera-extensions-1.4.0-beta01.aar",
          "size": 133594,
          "sha512": "a61e7194c472f63d7b5b16f6f6ae6776b068832b99bc236abd12f289d4fa272bf811fc1ec8e73f7f5e9db3329ae82b8d15f65999063d49752cd7729b0f2764ff",
          "sha256": "35b878bac4404400ed09ed5a30ab730de3940bfceeed17c5ba042d069ecd0467",
          "sha1": "6cc6dfba38bc25fdf57617cb1180946c525d5905",
          "md5": "41a749210ce1aaf9554c2bc17ba3a54f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-extensions-1.4.0-beta01.aar",
          "url": "camera-extensions-1.4.0-beta01.aar",
          "size": 133594,
          "sha512": "a61e7194c472f63d7b5b16f6f6ae6776b068832b99bc236abd12f289d4fa272bf811fc1ec8e73f7f5e9db3329ae82b8d15f65999063d49752cd7729b0f2764ff",
          "sha256": "35b878bac4404400ed09ed5a30ab730de3940bfceeed17c5ba042d069ecd0467",
          "sha1": "6cc6dfba38bc25fdf57617cb1180946c525d5905",
          "md5": "41a749210ce1aaf9554c2bc17ba3a54f"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-extensions-1.4.0-beta01-versionMetadata.json",
          "url": "camera-extensions-1.4.0-beta01-versionMetadata.json",
          "size": 1670,
          "sha512": "17adea318f558c6c457b06d867e82ca0ff3497e771bb9af4765a103855a9decd2437eb8dd7085ccc79f0583ff1339f33090721296f2266961d31186c2876b29d",
          "sha256": "a204bdeeb8fbd7c41a5598803850e43a1635c86cfcce8af60ba1374a2a046a83",
          "sha1": "51f70ad5c1ab775ce187fcc46168350da93ac1a7",
          "md5": "4a3146433e753bcd64c2f56847882186"
        }
      ]
    }
  ]
}