{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.10.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "activity is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "activity is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-1.10.0-alpha01-sources.jar",
          "url": "activity-1.10.0-alpha01-sources.jar",
          "size": 57372,
          "sha512": "215510fe1a39c1f14000d4c43b277228fd5fae4af02545ffa879d95fa22cf07150b9af45fe0b4513a733027d41941fc06be82c261172fd8a58c6d18c295d4f4a",
          "sha256": "59cb340d28b3dd297d24b17430c1e64f9b13cd6d16fdfaba66201950efbf9fc2",
          "sha1": "e67758a21b5043111645a625640fa18a80bc52d3",
          "md5": "d35fffde0766eb7d4f00a1ca287b8f22"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "activity is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "activity is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-1.10.0-alpha01.aar",
          "url": "activity-1.10.0-alpha01.aar",
          "size": 214762,
          "sha512": "23ac27068fd3d00704d83d5058d9f4003c5515af0e6acadc87b20f9f5c49dfa6547633a9dbc46e74eb86587fc0a7cb1119e94961611e16ec0b61738c7e316936",
          "sha256": "8e5155e16ab61c17f0cedf1a95d8dea56d1abc58b952664d0611806ba3ddea1c",
          "sha1": "f93c93419ea9ab7cae11892f878b1b12667fe4cf",
          "md5": "9eb825c9d52639d6a179c20b803b4312"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "activity is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "activity is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-1.10.0-alpha01.aar",
          "url": "activity-1.10.0-alpha01.aar",
          "size": 214762,
          "sha512": "23ac27068fd3d00704d83d5058d9f4003c5515af0e6acadc87b20f9f5c49dfa6547633a9dbc46e74eb86587fc0a7cb1119e94961611e16ec0b61738c7e316936",
          "sha256": "8e5155e16ab61c17f0cedf1a95d8dea56d1abc58b952664d0611806ba3ddea1c",
          "sha1": "f93c93419ea9ab7cae11892f878b1b12667fe4cf",
          "md5": "9eb825c9d52639d6a179c20b803b4312"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "activity is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "activity is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-1.10.0-alpha01-versionMetadata.json",
          "url": "activity-1.10.0-alpha01-versionMetadata.json",
          "size": 29726,
          "sha512": "a95ad8afca18eb22945bbdd34b8b82a7ef249a9f7c53ae3d695808a3e277575bbfa3be393cfaffc15189d2dd84059150b7ee2711fab55f487ce45bfd3eeceb92",
          "sha256": "f8dbd866d6cbf42628b5434b605fca25a8ff93a33ea9c41be88b7ae9b90fbd99",
          "sha1": "9c4e3f19db56bd9133d5a0e257723a73227ca4ff",
          "md5": "949f462f0a0cd7df297a849ceeff3121"
        }
      ]
    }
  ]
}