version: "2.8.0-alpha03"
dependency_list {
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-common-ktx"
    version: "2.8.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-runtime"
    version: "2.8.0-alpha03"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.navigation"
group_id: "androidx.navigation"
artifact_id: "navigation-runtime-ktx"
path: "/navigation/navigation-runtime-ktx"
sha: "6051cad23e2ba97fd1fdeea218cec5119d8213de"
require_same_version_group_build: true
group_zip_path: "per-group-zips/gmaven-androidx-navigation-11436812.zip"
project_zip_path: "per-project-zips/androidx.navigation-navigation-runtime-ktx-all-11436812-2.8.0-alpha03.zip"
kotlin_version: "1.9.22"
dependency_constraint_list {
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-common"
    version: "2.8.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-common-ktx"
    version: "2.8.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-compose"
    version: "2.8.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-dynamic-features-fragment"
    version: "2.8.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-dynamic-features-runtime"
    version: "2.8.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-fragment"
    version: "2.8.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-fragment-ktx"
    version: "2.8.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-runtime"
    version: "2.8.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-safe-args-generator"
    version: "2.8.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-safe-args-gradle-plugin"
    version: "2.8.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-testing"
    version: "2.8.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-ui"
    version: "2.8.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-ui-ktx"
    version: "2.8.0-alpha03"
    is_tip_of_tree: true
  }
}
