version: "1.14.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.1.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.14.0-alpha01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.core"
group_id: "androidx.core"
artifact_id: "core-ktx"
path: "/core/core-ktx"
sha: "f7e7d1939c03cfe2480ecd45ee9b33ab4a863638"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.core-core-ktx-all-11963838-1.14.0-alpha01.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.14.0-alpha01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
