{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-ktx",
    "version": "1.14.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ktx-1.14.0-alpha01-sources.jar",
          "url": "core-ktx-1.14.0-alpha01-sources.jar",
          "size": 70066,
          "sha512": "f0633f783af91e6ec138c5c536aad95fa8e3abcccf75643b6e9939b5ac4f44d3601eab240075a75aa3745009d120e9ba94902680b4bfb4f1eb63e2ec59f76e14",
          "sha256": "2e72bcdc7c2bc3705a37a7c6d2e80954fa7866fc8c93f1c2abd56cadc39ab4f6",
          "sha1": "9e4d33681dd1df39543757c2ccf64b2ac018df23",
          "md5": "0614529ed93e0c6dd1c8cc82a16a075d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.14.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-ktx-1.14.0-alpha01.aar",
          "url": "core-ktx-1.14.0-alpha01.aar",
          "size": 170760,
          "sha512": "ca1a1fc3d7f8ccc6fd4ff1e1b779dd520f53b4f90525ab7be70fd64ea56b9ecd4ecea6baba8de66456e044676c11ec264af4ad58a868d4da28ddadc1e9b544df",
          "sha256": "2b7ca2136cbdfaa22b1c9783bb132075e673aa57cad19a465d7aafb1c4dd8a84",
          "sha1": "ff02648bc5bf2f5844114ea2b2d43d966837a3d1",
          "md5": "e9628bf63bd84b82d3355445c9eeb074"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.14.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.14.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "core-ktx-1.14.0-alpha01.aar",
          "url": "core-ktx-1.14.0-alpha01.aar",
          "size": 170760,
          "sha512": "ca1a1fc3d7f8ccc6fd4ff1e1b779dd520f53b4f90525ab7be70fd64ea56b9ecd4ecea6baba8de66456e044676c11ec264af4ad58a868d4da28ddadc1e9b544df",
          "sha256": "2b7ca2136cbdfaa22b1c9783bb132075e673aa57cad19a465d7aafb1c4dd8a84",
          "sha1": "ff02648bc5bf2f5844114ea2b2d43d966837a3d1",
          "md5": "e9628bf63bd84b82d3355445c9eeb074"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-ktx-1.14.0-alpha01-versionMetadata.json",
          "url": "core-ktx-1.14.0-alpha01-versionMetadata.json",
          "size": 42717,
          "sha512": "d94e7af20884072ba66f3e89dbd1b4e1823156d64bae821674229d47b5a48aa8d552ab42628b5a4d51286814390f8bf4a848006c3653a783e1d324ac6e643eea",
          "sha256": "261dcd3c8616cae91271d5163997c45b8b509af204786420649a0b7e0f245281",
          "sha1": "9ccd1b46b95778109472c0a16ddd08e4bef021f0",
          "md5": "e320a403a93dad70e1c5d328f07a9e93"
        }
      ]
    }
  ]
}