{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation/1.7.0-beta02/foundation-1.7.0-beta02.module",
    "group": "androidx.compose.foundation",
    "module": "foundation",
    "version": "1.7.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-beta02"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-release.aar",
          "url": "foundation-android-1.7.0-beta02.aar",
          "size": 4827295,
          "sha512": "fd90ae1a907b518847985689f312f9487e6f4f833f4a5582f223cd0bb57765df4c102677624267ec0243d49ebb8728952cc7224ce2e7ab67cf80c4591a9c1f27",
          "sha256": "547eb3a7fbcc7e62bfd187e4b259b73836589c56d89c76640d9937f6fa0bab1e",
          "sha1": "3a0193f4d257b1a5cca06426155378c5210a9aa3",
          "md5": "503c680df15feba4ba816b2b48fd401c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-release.aar",
          "url": "foundation-android-1.7.0-beta02.aar",
          "size": 4827295,
          "sha512": "fd90ae1a907b518847985689f312f9487e6f4f833f4a5582f223cd0bb57765df4c102677624267ec0243d49ebb8728952cc7224ce2e7ab67cf80c4591a9c1f27",
          "sha256": "547eb3a7fbcc7e62bfd187e4b259b73836589c56d89c76640d9937f6fa0bab1e",
          "sha1": "3a0193f4d257b1a5cca06426155378c5210a9aa3",
          "md5": "503c680df15feba4ba816b2b48fd401c"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-beta02"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-1.7.0-beta02-samples-sources.jar",
          "url": "foundation-android-1.7.0-beta02-samples-sources.jar",
          "size": 70960,
          "sha512": "e6915fda8c84b27f1fb4ef88ad8fecf0946b6bb5ed172c17baeec6ea1c7f178203f3e8877e6fe31c05f4b48ae924697aa34fce3e48971495e938535a707372ad",
          "sha256": "5a6b849641c2a695f3a0581b3c0580ea75330660c32a6fd60ebaf475fdfc7b3f",
          "sha1": "73cc34ad1d4dc4fd23d3af615e71abf6880c7510",
          "md5": "644d279dff3106b5f276edd15a0ec1f1"
        },
        {
          "name": "foundation-android-1.7.0-beta02-sources.jar",
          "url": "foundation-android-1.7.0-beta02-sources.jar",
          "size": 871677,
          "sha512": "1afa41e52cf5012b5bb5f426e083929ceca52a7cc0c0b221aed9c420202dd4c6d33330c11890a9d6b8327a6867a39c30b4aefbc331d87dd8eaf896217837cf98",
          "sha256": "488ca99146089a8b55a6fd1866f9e053926ee20d0932046916435ecab167f055",
          "sha1": "1292a23af26a2eedd94f93052613a1f7c072f203",
          "md5": "9b467265be6d2136eb48e49f930353e6"
        }
      ]
    }
  ]
}