{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tracing",
    "module": "tracing-perfetto-handshake",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto-handshake is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-binary",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto-handshake is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-handshake-1.0.0.jar",
          "url": "tracing-perfetto-handshake-1.0.0.jar",
          "size": 25877,
          "sha512": "0eee32b5799551b368c87e496a04137c0133e239c508f6dbb2c50257e33024183acf55ed89badcd4f65b01ddc09cec2119421744942b91168f5eb71ed4577b04",
          "sha256": "2f2ee5c58561d72cabe9207c43669fe92d6c1386f8c1c2624489e6ab367b121e",
          "sha1": "b84cee5765fdde53d1be9be361db51951b908acd",
          "md5": "c264fe66be545db7c1804402c0a54ff1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto-handshake is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-binary",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto-handshake is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-handshake-1.0.0.jar",
          "url": "tracing-perfetto-handshake-1.0.0.jar",
          "size": 25877,
          "sha512": "0eee32b5799551b368c87e496a04137c0133e239c508f6dbb2c50257e33024183acf55ed89badcd4f65b01ddc09cec2119421744942b91168f5eb71ed4577b04",
          "sha256": "2f2ee5c58561d72cabe9207c43669fe92d6c1386f8c1c2624489e6ab367b121e",
          "sha1": "b84cee5765fdde53d1be9be361db51951b908acd",
          "md5": "c264fe66be545db7c1804402c0a54ff1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto-handshake is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-binary",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto-handshake is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-handshake-1.0.0-sources.jar",
          "url": "tracing-perfetto-handshake-1.0.0-sources.jar",
          "size": 8864,
          "sha512": "faf9f6e034a96d1aaf3dd671b08838c33eae24a4b5365067c56ca90a02f2b9edc6f0f2459bf96256736d4d83e8ce5afa5322f6f94a40197928df269f4e00b254",
          "sha256": "cc81aab7ffa85c77ee982b24e60be67c3a0ed41f134548fb01854ec445cdce36",
          "sha1": "1d42d3c1ff441f132b54c5572fd0ec7bd0ec27ea",
          "md5": "7abbe4f89e6d50f81c6d0647de824adc"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto-handshake is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-binary",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto-handshake is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-handshake-1.0.0-versionMetadata.json",
          "url": "tracing-perfetto-handshake-1.0.0-versionMetadata.json",
          "size": 2583,
          "sha512": "e0b214e0da917e9a36277f2070c30d205ad613e5b45e617bf466924e1b04c8fbc4df9d7138754936a9a440ebb261db448bd6564665d366489cf601f09d6964f5",
          "sha256": "abb023c90a9e99b7d88f24f3a3ae81cf96885680a3c3a682e688c6ccb6e76c95",
          "sha1": "0ef641334dfa426e9ca72a85225cf08079006e22",
          "md5": "0d6523af351f4e2da6a44c9d7b60fb01"
        }
      ]
    }
  ]
}