{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-testing",
    "version": "2.10.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-testing is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-testing-2.10.0-alpha02-sources.jar",
          "url": "work-testing-2.10.0-alpha02-sources.jar",
          "size": 20913,
          "sha512": "0eedb802a6558176ac06dde469d3c87bcb65454ec62c1a016e6337aa3a95996624cad2da40ae4de2780001a259495288cbb1d7976effaaff3cf1380934a245f3",
          "sha256": "e65135698b585ad74f4fcabe4fae142e7ec5e4e689edbd748a2302e754bf6f19",
          "sha1": "eff2a551fbbb38b5cc67a1f28f36c86cb8def1c6",
          "md5": "1f809de8822d304f04b007198082413a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.0-alpha02"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-testing is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-testing-2.10.0-alpha02.aar",
          "url": "work-testing-2.10.0-alpha02.aar",
          "size": 33831,
          "sha512": "1c29f298eebab5d752cb00a851ca6debecf41768167a4eeb25cf26703976d2714b9472ff7758dca45f638e1f5865898a4c134a32ea272d02bd0f9d80f8cd2017",
          "sha256": "0107e86e8630af93728b9649d15ad13e9d4def120f130495dfeb3e79b6e0aea1",
          "sha1": "4074b6362982f004a1d23f784a740e906ed107c1",
          "md5": "5c651f79560611fd7463ffe60a386999"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.0-alpha02"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-testing is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-testing-2.10.0-alpha02.aar",
          "url": "work-testing-2.10.0-alpha02.aar",
          "size": 33831,
          "sha512": "1c29f298eebab5d752cb00a851ca6debecf41768167a4eeb25cf26703976d2714b9472ff7758dca45f638e1f5865898a4c134a32ea272d02bd0f9d80f8cd2017",
          "sha256": "0107e86e8630af93728b9649d15ad13e9d4def120f130495dfeb3e79b6e0aea1",
          "sha1": "4074b6362982f004a1d23f784a740e906ed107c1",
          "md5": "5c651f79560611fd7463ffe60a386999"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.0-alpha02"
          },
          "reason": "work-testing is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-testing-2.10.0-alpha02-versionMetadata.json",
          "url": "work-testing-2.10.0-alpha02-versionMetadata.json",
          "size": 4448,
          "sha512": "18dbaedff5c62182e01a40acb98db736e2d28718f2ca56d6bac3004c8cfe8927bc99983e22806e7697416ec10d7d74810fce2bde1610b60fe4ec1777b910fa2f",
          "sha256": "7837b8f1f4ec58b417bcc50952e6275b510d66f8d8b52ab249cc9097504ee3d8",
          "sha1": "54654616320ac71fa36ab0e51fa2be48ca960221",
          "md5": "5a63bbd97548a31eb06356c5e9e82a12"
        }
      ]
    }
  ]
}