{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sqlite/2.5.0-alpha04/sqlite-2.5.0-alpha04.module",
    "group": "androidx.sqlite",
    "module": "sqlite",
    "version": "2.5.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.0-alpha04"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0-alpha04"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0-alpha04"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-release.aar",
          "url": "sqlite-android-2.5.0-alpha04.aar",
          "size": 31254,
          "sha512": "48d766932fb9f4def1fda2117e9c829234d756a01392b90e998253b8897644d5704b2e06fab59e35d38cf905aba78a72725b46845be1a2710a2173583eb531b1",
          "sha256": "f0cf653ca0add7ab640173548b19bbb0b576f2e35b2a8e9bdc35faa692817b85",
          "sha1": "d6e6525a807914f194947b7f3510f9b0f36ee9cd",
          "md5": "73cd96e1068656df6487a4bfc64db651"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.0-alpha04"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0-alpha04"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0-alpha04"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-release.aar",
          "url": "sqlite-android-2.5.0-alpha04.aar",
          "size": 31254,
          "sha512": "48d766932fb9f4def1fda2117e9c829234d756a01392b90e998253b8897644d5704b2e06fab59e35d38cf905aba78a72725b46845be1a2710a2173583eb531b1",
          "sha256": "f0cf653ca0add7ab640173548b19bbb0b576f2e35b2a8e9bdc35faa692817b85",
          "sha1": "d6e6525a807914f194947b7f3510f9b0f36ee9cd",
          "md5": "73cd96e1068656df6487a4bfc64db651"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.0-alpha04"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0-alpha04"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0-alpha04"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-android-2.5.0-alpha04-sources.jar",
          "url": "sqlite-android-2.5.0-alpha04-sources.jar",
          "size": 25871,
          "sha512": "38a4c2818bd4d6ba3b85a22b3051fb7d3bb6844539a54a502f9778af30ea9fc0084463175789e82bb81bab604ddad9ebb1e9cb01fe05952881123a8c494cd89e",
          "sha256": "eae80774b7ac010acf7bc79bbd18cfeb3173616c917a73e8efe12075767a5bdf",
          "sha1": "0b7dc0ce3f5f3d805baf216a91da342eb7374e82",
          "md5": "6e1cad1e39d77ad5234604db4b00be50"
        }
      ]
    }
  ]
}