{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-compiler",
    "version": "2.7.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-compiler-2.7.0-alpha01.jar",
          "url": "room-compiler-2.7.0-alpha01.jar",
          "size": 5332555,
          "sha512": "5c44acd0445f494d606acd122c55310b36286ee43dd518a53e42888ab7ecf095da13078f0c5a8270eb0d52b84d4342e00ff179f6ef361c17fb4f81208373ab7c",
          "sha256": "db6f7a1109bc2c8dcbd27b4fd5d8f8fe13077292157821c9ffd50fdcc9e363c4",
          "sha1": "1c2b13e5371c9c5d430c0b6f93fc9f30fc2d6d1a",
          "md5": "93e107932f335952fb4c45a6d821fe4a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha01"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha01"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha01"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.9.22-1.0.17"
          }
        },
        {
          "group": "com.intellij",
          "module": "annotations",
          "version": {
            "requires": "12.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-javapoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.41.2.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-compiler-2.7.0-alpha01.jar",
          "url": "room-compiler-2.7.0-alpha01.jar",
          "size": 5332555,
          "sha512": "5c44acd0445f494d606acd122c55310b36286ee43dd518a53e42888ab7ecf095da13078f0c5a8270eb0d52b84d4342e00ff179f6ef361c17fb4f81208373ab7c",
          "sha256": "db6f7a1109bc2c8dcbd27b4fd5d8f8fe13077292157821c9ffd50fdcc9e363c4",
          "sha1": "1c2b13e5371c9c5d430c0b6f93fc9f30fc2d6d1a",
          "md5": "93e107932f335952fb4c45a6d821fe4a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-compiler-2.7.0-alpha01.jar",
          "url": "room-compiler-2.7.0-alpha01.jar",
          "size": 5332555,
          "sha512": "5c44acd0445f494d606acd122c55310b36286ee43dd518a53e42888ab7ecf095da13078f0c5a8270eb0d52b84d4342e00ff179f6ef361c17fb4f81208373ab7c",
          "sha256": "db6f7a1109bc2c8dcbd27b4fd5d8f8fe13077292157821c9ffd50fdcc9e363c4",
          "sha1": "1c2b13e5371c9c5d430c0b6f93fc9f30fc2d6d1a",
          "md5": "93e107932f335952fb4c45a6d821fe4a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha01"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-compiler-2.7.0-alpha01-sources.jar",
          "url": "room-compiler-2.7.0-alpha01-sources.jar",
          "size": 497254,
          "sha512": "c1ca6d89521c4750f5c1665f2fe563e94ccfde1dae8d0c872afc6fa915b199c8fb78a99b1ef8fbe0ee95d937f579c291b0c9b38a456002672fc0d4b505db9f49",
          "sha256": "cca24d7fe0d5c1b56a0156e8d11e5f113367d2aae0e30c06901a1faf6ae9858b",
          "sha1": "0826fbad3846f749b02b5a08318544631205992e",
          "md5": "91a37284cc1e07ea72c8cfd6f2696467"
        }
      ]
    }
  ]
}