{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-runtime",
    "version": "2.10.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.10.0-alpha01.aar",
          "url": "work-runtime-2.10.0-alpha01.aar",
          "size": 1937804,
          "sha512": "eb1005c8afd1fcfac46f6f5c48de276f55d7876dbbb41242c0298056ad239d0c6e71f8ef2fba1483de29d62f4451022aee5782768786346fb709e9e83102c742",
          "sha256": "97e4e5da55932de26e0ef52f7fdadb87dded8cc8853310a8d938a68a077104aa",
          "sha1": "f4115f4aef97665be497f82ab7a242729ee9828a",
          "md5": "4d4f0f0bc3ec15b765b3b4fb324d8fae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.10.0-alpha01.aar",
          "url": "work-runtime-2.10.0-alpha01.aar",
          "size": 1937804,
          "sha512": "eb1005c8afd1fcfac46f6f5c48de276f55d7876dbbb41242c0298056ad239d0c6e71f8ef2fba1483de29d62f4451022aee5782768786346fb709e9e83102c742",
          "sha256": "97e4e5da55932de26e0ef52f7fdadb87dded8cc8853310a8d938a68a077104aa",
          "sha1": "f4115f4aef97665be497f82ab7a242729ee9828a",
          "md5": "4d4f0f0bc3ec15b765b3b4fb324d8fae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.10.0-alpha01-sources.jar",
          "url": "work-runtime-2.10.0-alpha01-sources.jar",
          "size": 287233,
          "sha512": "427669269fde2769d02a64848182dad3dd9612863e3eb68a5eb7feac08391d7317eec882c450a6c47d0bc74cf98935439aed25d3910753d6f8e6a5f416395264",
          "sha256": "976e832cb8136d90883d4ec4239d54bdcb29356d29f50eaf605e98cee974881b",
          "sha1": "ec389f8de7aac07cd5f485076fccf7e52fe2f4c0",
          "md5": "e1c8e6435bdd6c4b994a3b9c9bbc2446"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.0-alpha01"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.10.0-alpha01-versionMetadata.json",
          "url": "work-runtime-2.10.0-alpha01-versionMetadata.json",
          "size": 35404,
          "sha512": "3ce362daf214c1fd1a20021cd6cc00e8d66b0391bfcaa645eed500d33f08058b01319ebed19b1d4b3e8fd2f5786d966d91792f4c63e3cdee7f1ecb5803bb9050",
          "sha256": "70ad6212dae5947f69c43d02ce6666c632d4c293602e608061dc820044b3185f",
          "sha1": "e7a8cf11cee23c704161332d39176453813d8ec5",
          "md5": "893a9349a727eef637fce2c17e8db78f"
        }
      ]
    }
  ]
}