version: "2.9.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.2.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-runtime"
    version: "2.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.startup"
    artifact_id: "startup-runtime"
    version: "1.1.1"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.lifecycle"
group_id: "androidx.lifecycle"
artifact_id: "lifecycle-process"
path: "/lifecycle/lifecycle-process"
sha: "3264c1f21ddfe2acf96a1d034f78367662cf9f65"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.lifecycle-lifecycle-process-all-11879057-2.9.0-alpha01.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-common"
    version: "2.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-common-java8"
    version: "2.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-compiler"
    version: "2.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-livedata"
    version: "2.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-livedata-core"
    version: "2.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-livedata-core-ktx"
    version: "2.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-livedata-ktx"
    version: "2.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-reactivestreams"
    version: "2.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-reactivestreams-ktx"
    version: "2.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-runtime"
    version: "2.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-runtime-compose"
    version: "2.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-runtime-ktx"
    version: "2.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-runtime-testing"
    version: "2.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-service"
    version: "2.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-viewmodel"
    version: "2.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-viewmodel-compose"
    version: "2.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-viewmodel-ktx"
    version: "2.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-viewmodel-savedstate"
    version: "2.9.0-alpha01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
